// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientesColumns holds the columns for the "clientes" table.
	ClientesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nombre_completo", Type: field.TypeString},
		{Name: "telefono", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "direccion", Type: field.TypeString, Nullable: true},
	}
	// ClientesTable holds the schema information for the "clientes" table.
	ClientesTable = &schema.Table{
		Name:       "clientes",
		Columns:    ClientesColumns,
		PrimaryKey: []*schema.Column{ClientesColumns[0]},
	}
	// DetallesPedidoColumns holds the columns for the "detalles_pedido" table.
	DetallesPedidoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "cantidad", Type: field.TypeInt},
		{Name: "precio_unitario", Type: field.TypeFloat64},
		{Name: "subtotal", Type: field.TypeFloat64},
		{Name: "pedido_id", Type: field.TypeInt},
		{Name: "producto_id", Type: field.TypeInt},
	}
	// DetallesPedidoTable holds the schema information for the "detalles_pedido" table.
	DetallesPedidoTable = &schema.Table{
		Name:       "detalles_pedido",
		Columns:    DetallesPedidoColumns,
		PrimaryKey: []*schema.Column{DetallesPedidoColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "detalles_pedido_pedidos_detalles",
				Columns:    []*schema.Column{DetallesPedidoColumns[4]},
				RefColumns: []*schema.Column{PedidosColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "detalles_pedido_productos_menu_detalles_pedido",
				Columns:    []*schema.Column{DetallesPedidoColumns[5]},
				RefColumns: []*schema.Column{ProductosMenuColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MateriaPrimaColumns holds the columns for the "materia_prima" table.
	MateriaPrimaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nombre_insumo", Type: field.TypeString},
		{Name: "categoria", Type: field.TypeString},
		{Name: "proveedor", Type: field.TypeString},
		{Name: "unidad_medida", Type: field.TypeString},
		{Name: "costo_unitario", Type: field.TypeFloat64},
		{Name: "stock_actual", Type: field.TypeFloat64},
		{Name: "punto_reorden", Type: field.TypeFloat64},
	}
	// MateriaPrimaTable holds the schema information for the "materia_prima" table.
	MateriaPrimaTable = &schema.Table{
		Name:       "materia_prima",
		Columns:    MateriaPrimaColumns,
		PrimaryKey: []*schema.Column{MateriaPrimaColumns[0]},
	}
	// PedidosColumns holds the columns for the "pedidos" table.
	PedidosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "fecha_pedido", Type: field.TypeTime},
		{Name: "estado", Type: field.TypeString, Default: "COMPLETADO"},
		{Name: "total_pedido", Type: field.TypeFloat64},
		{Name: "cliente_id", Type: field.TypeInt, Nullable: true},
	}
	// PedidosTable holds the schema information for the "pedidos" table.
	PedidosTable = &schema.Table{
		Name:       "pedidos",
		Columns:    PedidosColumns,
		PrimaryKey: []*schema.Column{PedidosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pedidos_clientes_pedidos",
				Columns:    []*schema.Column{PedidosColumns[4]},
				RefColumns: []*schema.Column{ClientesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProductosMenuColumns holds the columns for the "productos_menu" table.
	ProductosMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nombre_producto", Type: field.TypeString},
		{Name: "categoria_menu", Type: field.TypeString},
		{Name: "precio_venta", Type: field.TypeFloat64},
	}
	// ProductosMenuTable holds the schema information for the "productos_menu" table.
	ProductosMenuTable = &schema.Table{
		Name:       "productos_menu",
		Columns:    ProductosMenuColumns,
		PrimaryKey: []*schema.Column{ProductosMenuColumns[0]},
	}
	// RecetasColumns holds the columns for the "recetas" table.
	RecetasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "cantidad_necesaria", Type: field.TypeFloat64},
		{Name: "materia_prima_recetas", Type: field.TypeInt},
		{Name: "productos_menu_recetas", Type: field.TypeInt},
	}
	// RecetasTable holds the schema information for the "recetas" table.
	RecetasTable = &schema.Table{
		Name:       "recetas",
		Columns:    RecetasColumns,
		PrimaryKey: []*schema.Column{RecetasColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "recetas_materia_prima_recetas",
				Columns:    []*schema.Column{RecetasColumns[2]},
				RefColumns: []*schema.Column{MateriaPrimaColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "recetas_productos_menu_recetas",
				Columns:    []*schema.Column{RecetasColumns[3]},
				RefColumns: []*schema.Column{ProductosMenuColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientesTable,
		DetallesPedidoTable,
		MateriaPrimaTable,
		PedidosTable,
		ProductosMenuTable,
		RecetasTable,
	}
)

func init() {
	ClientesTable.Annotation = &entsql.Annotation{
		Table: "clientes",
	}
	DetallesPedidoTable.ForeignKeys[0].RefTable = PedidosTable
	DetallesPedidoTable.ForeignKeys[1].RefTable = ProductosMenuTable
	DetallesPedidoTable.Annotation = &entsql.Annotation{
		Table: "detalles_pedido",
	}
	MateriaPrimaTable.Annotation = &entsql.Annotation{
		Table: "materia_prima",
	}
	PedidosTable.ForeignKeys[0].RefTable = ClientesTable
	PedidosTable.Annotation = &entsql.Annotation{
		Table: "pedidos",
	}
	ProductosMenuTable.Annotation = &entsql.Annotation{
		Table: "productos_menu",
	}
	RecetasTable.ForeignKeys[0].RefTable = MateriaPrimaTable
	RecetasTable.ForeignKeys[1].RefTable = ProductosMenuTable
	RecetasTable.Annotation = &entsql.Annotation{
		Table: "recetas",
	}
}
