services:
  # 1. CONTENEDOR DE LA BASE DE DATOS
  postgres_boloneria:
    image: postgres:15-alpine
    container_name: db_boloneria
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_boloneria:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_bodega

  # 2. CONTENEDOR DE n8n
  n8n_reportes:
    image: n8nio/n8n:latest
    container_name: n8n_boloneria
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=America/Guayaquil
      - N8N_ENCRYPTION_KEY=${N8N_KEY}
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - red_bodega
    depends_on:
      - postgres_boloneria

  # 3. CONTENEDOR DEL DASHBOARD (STREAMLIT)
  streamlit_dashboard:
    image: python:3.10-slim
    container_name: streamlit_boloneria
    restart: always
    ports:
      - "8501:8501"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install streamlit psycopg2-binary pandas && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    networks:
      - red_bodega
    depends_on:
      - postgres_boloneria

# VOLÚMENES PERSISTENTES
volumes:
  pgdata_boloneria:
  n8n_data:

# REDES INTERNAS
networks:
  red_bodega:
    driver: bridge