// Code generated by ent, DO NOT EDIT.

package detallespedido

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the detallespedido type in the database.
	Label = "detalles_pedido"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPedidoID holds the string denoting the pedido_id field in the database.
	FieldPedidoID = "pedido_id"
	// FieldProductoID holds the string denoting the producto_id field in the database.
	FieldProductoID = "producto_id"
	// FieldCantidad holds the string denoting the cantidad field in the database.
	FieldCantidad = "cantidad"
	// FieldPrecioUnitario holds the string denoting the precio_unitario field in the database.
	FieldPrecioUnitario = "precio_unitario"
	// FieldSubtotal holds the string denoting the subtotal field in the database.
	FieldSubtotal = "subtotal"
	// EdgePedido holds the string denoting the pedido edge name in mutations.
	EdgePedido = "pedido"
	// EdgeProducto holds the string denoting the producto edge name in mutations.
	EdgeProducto = "producto"
	// Table holds the table name of the detallespedido in the database.
	Table = "detalles_pedido"
	// PedidoTable is the table that holds the pedido relation/edge.
	PedidoTable = "detalles_pedido"
	// PedidoInverseTable is the table name for the Pedidos entity.
	// It exists in this package in order to avoid circular dependency with the "pedidos" package.
	PedidoInverseTable = "pedidos"
	// PedidoColumn is the table column denoting the pedido relation/edge.
	PedidoColumn = "pedido_id"
	// ProductoTable is the table that holds the producto relation/edge.
	ProductoTable = "detalles_pedido"
	// ProductoInverseTable is the table name for the ProductosMenu entity.
	// It exists in this package in order to avoid circular dependency with the "productosmenu" package.
	ProductoInverseTable = "productos_menu"
	// ProductoColumn is the table column denoting the producto relation/edge.
	ProductoColumn = "producto_id"
)

// Columns holds all SQL columns for detallespedido fields.
var Columns = []string{
	FieldID,
	FieldPedidoID,
	FieldProductoID,
	FieldCantidad,
	FieldPrecioUnitario,
	FieldSubtotal,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the DetallesPedido queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPedidoID orders the results by the pedido_id field.
func ByPedidoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPedidoID, opts...).ToFunc()
}

// ByProductoID orders the results by the producto_id field.
func ByProductoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductoID, opts...).ToFunc()
}

// ByCantidad orders the results by the cantidad field.
func ByCantidad(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCantidad, opts...).ToFunc()
}

// ByPrecioUnitario orders the results by the precio_unitario field.
func ByPrecioUnitario(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrecioUnitario, opts...).ToFunc()
}

// BySubtotal orders the results by the subtotal field.
func BySubtotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtotal, opts...).ToFunc()
}

// ByPedidoField orders the results by pedido field.
func ByPedidoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPedidoStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductoField orders the results by producto field.
func ByProductoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductoStep(), sql.OrderByField(field, opts...))
	}
}
func newPedidoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PedidoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PedidoTable, PedidoColumn),
	)
}
func newProductoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductoTable, ProductoColumn),
	)
}
