// Code generated by ent, DO NOT EDIT.

package detallespedido

import (
	"boloneria-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLTE(FieldID, id))
}

// PedidoID applies equality check predicate on the "pedido_id" field. It's identical to PedidoIDEQ.
func PedidoID(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldPedidoID, v))
}

// ProductoID applies equality check predicate on the "producto_id" field. It's identical to ProductoIDEQ.
func ProductoID(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldProductoID, v))
}

// Cantidad applies equality check predicate on the "cantidad" field. It's identical to CantidadEQ.
func Cantidad(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldCantidad, v))
}

// PrecioUnitario applies equality check predicate on the "precio_unitario" field. It's identical to PrecioUnitarioEQ.
func PrecioUnitario(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldPrecioUnitario, v))
}

// Subtotal applies equality check predicate on the "subtotal" field. It's identical to SubtotalEQ.
func Subtotal(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldSubtotal, v))
}

// PedidoIDEQ applies the EQ predicate on the "pedido_id" field.
func PedidoIDEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldPedidoID, v))
}

// PedidoIDNEQ applies the NEQ predicate on the "pedido_id" field.
func PedidoIDNEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldPedidoID, v))
}

// PedidoIDIn applies the In predicate on the "pedido_id" field.
func PedidoIDIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldPedidoID, vs...))
}

// PedidoIDNotIn applies the NotIn predicate on the "pedido_id" field.
func PedidoIDNotIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldPedidoID, vs...))
}

// ProductoIDEQ applies the EQ predicate on the "producto_id" field.
func ProductoIDEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldProductoID, v))
}

// ProductoIDNEQ applies the NEQ predicate on the "producto_id" field.
func ProductoIDNEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldProductoID, v))
}

// ProductoIDIn applies the In predicate on the "producto_id" field.
func ProductoIDIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldProductoID, vs...))
}

// ProductoIDNotIn applies the NotIn predicate on the "producto_id" field.
func ProductoIDNotIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldProductoID, vs...))
}

// CantidadEQ applies the EQ predicate on the "cantidad" field.
func CantidadEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldCantidad, v))
}

// CantidadNEQ applies the NEQ predicate on the "cantidad" field.
func CantidadNEQ(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldCantidad, v))
}

// CantidadIn applies the In predicate on the "cantidad" field.
func CantidadIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldCantidad, vs...))
}

// CantidadNotIn applies the NotIn predicate on the "cantidad" field.
func CantidadNotIn(vs ...int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldCantidad, vs...))
}

// CantidadGT applies the GT predicate on the "cantidad" field.
func CantidadGT(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGT(FieldCantidad, v))
}

// CantidadGTE applies the GTE predicate on the "cantidad" field.
func CantidadGTE(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGTE(FieldCantidad, v))
}

// CantidadLT applies the LT predicate on the "cantidad" field.
func CantidadLT(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLT(FieldCantidad, v))
}

// CantidadLTE applies the LTE predicate on the "cantidad" field.
func CantidadLTE(v int) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLTE(FieldCantidad, v))
}

// PrecioUnitarioEQ applies the EQ predicate on the "precio_unitario" field.
func PrecioUnitarioEQ(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldPrecioUnitario, v))
}

// PrecioUnitarioNEQ applies the NEQ predicate on the "precio_unitario" field.
func PrecioUnitarioNEQ(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldPrecioUnitario, v))
}

// PrecioUnitarioIn applies the In predicate on the "precio_unitario" field.
func PrecioUnitarioIn(vs ...float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldPrecioUnitario, vs...))
}

// PrecioUnitarioNotIn applies the NotIn predicate on the "precio_unitario" field.
func PrecioUnitarioNotIn(vs ...float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldPrecioUnitario, vs...))
}

// PrecioUnitarioGT applies the GT predicate on the "precio_unitario" field.
func PrecioUnitarioGT(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGT(FieldPrecioUnitario, v))
}

// PrecioUnitarioGTE applies the GTE predicate on the "precio_unitario" field.
func PrecioUnitarioGTE(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGTE(FieldPrecioUnitario, v))
}

// PrecioUnitarioLT applies the LT predicate on the "precio_unitario" field.
func PrecioUnitarioLT(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLT(FieldPrecioUnitario, v))
}

// PrecioUnitarioLTE applies the LTE predicate on the "precio_unitario" field.
func PrecioUnitarioLTE(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLTE(FieldPrecioUnitario, v))
}

// SubtotalEQ applies the EQ predicate on the "subtotal" field.
func SubtotalEQ(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldEQ(FieldSubtotal, v))
}

// SubtotalNEQ applies the NEQ predicate on the "subtotal" field.
func SubtotalNEQ(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNEQ(FieldSubtotal, v))
}

// SubtotalIn applies the In predicate on the "subtotal" field.
func SubtotalIn(vs ...float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldIn(FieldSubtotal, vs...))
}

// SubtotalNotIn applies the NotIn predicate on the "subtotal" field.
func SubtotalNotIn(vs ...float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldNotIn(FieldSubtotal, vs...))
}

// SubtotalGT applies the GT predicate on the "subtotal" field.
func SubtotalGT(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGT(FieldSubtotal, v))
}

// SubtotalGTE applies the GTE predicate on the "subtotal" field.
func SubtotalGTE(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldGTE(FieldSubtotal, v))
}

// SubtotalLT applies the LT predicate on the "subtotal" field.
func SubtotalLT(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLT(FieldSubtotal, v))
}

// SubtotalLTE applies the LTE predicate on the "subtotal" field.
func SubtotalLTE(v float64) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.FieldLTE(FieldSubtotal, v))
}

// HasPedido applies the HasEdge predicate on the "pedido" edge.
func HasPedido() predicate.DetallesPedido {
	return predicate.DetallesPedido(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PedidoTable, PedidoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPedidoWith applies the HasEdge predicate on the "pedido" edge with a given conditions (other predicates).
func HasPedidoWith(preds ...predicate.Pedidos) predicate.DetallesPedido {
	return predicate.DetallesPedido(func(s *sql.Selector) {
		step := newPedidoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProducto applies the HasEdge predicate on the "producto" edge.
func HasProducto() predicate.DetallesPedido {
	return predicate.DetallesPedido(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductoTable, ProductoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductoWith applies the HasEdge predicate on the "producto" edge with a given conditions (other predicates).
func HasProductoWith(preds ...predicate.ProductosMenu) predicate.DetallesPedido {
	return predicate.DetallesPedido(func(s *sql.Selector) {
		step := newProductoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DetallesPedido) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DetallesPedido) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DetallesPedido) predicate.DetallesPedido {
	return predicate.DetallesPedido(sql.NotPredicates(p))
}
