services:
  # 1. CONTENEDOR DE LA BASE DE DATOS
  postgres_boloneria:
    image: postgres:15-alpine
    container_name: db_boloneria
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - red_bodega

  # 2. CONTENEDOR DE n8n
  n8n_reportes:
    image: n8nio/n8n:latest
    container_name: n8n_boloneria
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=America/Guayaquil
      - N8N_ENCRYPTION_KEY=${N8N_KEY:-proyectodistribuidos2026}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - red_bodega
    depends_on:
      - postgres_boloneria


# VOLÚMENES PERSISTENTES
volumes:
  n8n_data:

# REDES INTERNAS
networks:
  red_bodega:
    driver: bridge