// Code generated by ent, DO NOT EDIT.

package materiaprima

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the materiaprima type in the database.
	Label = "materia_prima"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNombreInsumo holds the string denoting the nombre_insumo field in the database.
	FieldNombreInsumo = "nombre_insumo"
	// FieldCategoria holds the string denoting the categoria field in the database.
	FieldCategoria = "categoria"
	// FieldProveedor holds the string denoting the proveedor field in the database.
	FieldProveedor = "proveedor"
	// FieldUnidadMedida holds the string denoting the unidad_medida field in the database.
	FieldUnidadMedida = "unidad_medida"
	// FieldCostoUnitario holds the string denoting the costo_unitario field in the database.
	FieldCostoUnitario = "costo_unitario"
	// FieldStockActual holds the string denoting the stock_actual field in the database.
	FieldStockActual = "stock_actual"
	// FieldPuntoReorden holds the string denoting the punto_reorden field in the database.
	FieldPuntoReorden = "punto_reorden"
	// EdgeRecetas holds the string denoting the recetas edge name in mutations.
	EdgeRecetas = "recetas"
	// Table holds the table name of the materiaprima in the database.
	Table = "materia_prima"
	// RecetasTable is the table that holds the recetas relation/edge.
	RecetasTable = "recetas"
	// RecetasInverseTable is the table name for the Recetas entity.
	// It exists in this package in order to avoid circular dependency with the "recetas" package.
	RecetasInverseTable = "recetas"
	// RecetasColumn is the table column denoting the recetas relation/edge.
	RecetasColumn = "materia_prima_recetas"
)

// Columns holds all SQL columns for materiaprima fields.
var Columns = []string{
	FieldID,
	FieldNombreInsumo,
	FieldCategoria,
	FieldProveedor,
	FieldUnidadMedida,
	FieldCostoUnitario,
	FieldStockActual,
	FieldPuntoReorden,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NombreInsumoValidator is a validator for the "nombre_insumo" field. It is called by the builders before save.
	NombreInsumoValidator func(string) error
	// CategoriaValidator is a validator for the "categoria" field. It is called by the builders before save.
	CategoriaValidator func(string) error
	// ProveedorValidator is a validator for the "proveedor" field. It is called by the builders before save.
	ProveedorValidator func(string) error
	// UnidadMedidaValidator is a validator for the "unidad_medida" field. It is called by the builders before save.
	UnidadMedidaValidator func(string) error
)

// OrderOption defines the ordering options for the MateriaPrima queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNombreInsumo orders the results by the nombre_insumo field.
func ByNombreInsumo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNombreInsumo, opts...).ToFunc()
}

// ByCategoria orders the results by the categoria field.
func ByCategoria(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoria, opts...).ToFunc()
}

// ByProveedor orders the results by the proveedor field.
func ByProveedor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProveedor, opts...).ToFunc()
}

// ByUnidadMedida orders the results by the unidad_medida field.
func ByUnidadMedida(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnidadMedida, opts...).ToFunc()
}

// ByCostoUnitario orders the results by the costo_unitario field.
func ByCostoUnitario(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostoUnitario, opts...).ToFunc()
}

// ByStockActual orders the results by the stock_actual field.
func ByStockActual(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockActual, opts...).ToFunc()
}

// ByPuntoReorden orders the results by the punto_reorden field.
func ByPuntoReorden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPuntoReorden, opts...).ToFunc()
}

// ByRecetasCount orders the results by recetas count.
func ByRecetasCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecetasStep(), opts...)
	}
}

// ByRecetas orders the results by recetas terms.
func ByRecetas(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecetasStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecetasStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecetasInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecetasTable, RecetasColumn),
	)
}
