// Code generated by ent, DO NOT EDIT.

package materiaprima

import (
	"boloneria-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldID, id))
}

// NombreInsumo applies equality check predicate on the "nombre_insumo" field. It's identical to NombreInsumoEQ.
func NombreInsumo(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldNombreInsumo, v))
}

// Categoria applies equality check predicate on the "categoria" field. It's identical to CategoriaEQ.
func Categoria(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldCategoria, v))
}

// Proveedor applies equality check predicate on the "proveedor" field. It's identical to ProveedorEQ.
func Proveedor(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldProveedor, v))
}

// UnidadMedida applies equality check predicate on the "unidad_medida" field. It's identical to UnidadMedidaEQ.
func UnidadMedida(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldUnidadMedida, v))
}

// CostoUnitario applies equality check predicate on the "costo_unitario" field. It's identical to CostoUnitarioEQ.
func CostoUnitario(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldCostoUnitario, v))
}

// StockActual applies equality check predicate on the "stock_actual" field. It's identical to StockActualEQ.
func StockActual(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldStockActual, v))
}

// PuntoReorden applies equality check predicate on the "punto_reorden" field. It's identical to PuntoReordenEQ.
func PuntoReorden(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldPuntoReorden, v))
}

// NombreInsumoEQ applies the EQ predicate on the "nombre_insumo" field.
func NombreInsumoEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldNombreInsumo, v))
}

// NombreInsumoNEQ applies the NEQ predicate on the "nombre_insumo" field.
func NombreInsumoNEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldNombreInsumo, v))
}

// NombreInsumoIn applies the In predicate on the "nombre_insumo" field.
func NombreInsumoIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldNombreInsumo, vs...))
}

// NombreInsumoNotIn applies the NotIn predicate on the "nombre_insumo" field.
func NombreInsumoNotIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldNombreInsumo, vs...))
}

// NombreInsumoGT applies the GT predicate on the "nombre_insumo" field.
func NombreInsumoGT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldNombreInsumo, v))
}

// NombreInsumoGTE applies the GTE predicate on the "nombre_insumo" field.
func NombreInsumoGTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldNombreInsumo, v))
}

// NombreInsumoLT applies the LT predicate on the "nombre_insumo" field.
func NombreInsumoLT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldNombreInsumo, v))
}

// NombreInsumoLTE applies the LTE predicate on the "nombre_insumo" field.
func NombreInsumoLTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldNombreInsumo, v))
}

// NombreInsumoContains applies the Contains predicate on the "nombre_insumo" field.
func NombreInsumoContains(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContains(FieldNombreInsumo, v))
}

// NombreInsumoHasPrefix applies the HasPrefix predicate on the "nombre_insumo" field.
func NombreInsumoHasPrefix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasPrefix(FieldNombreInsumo, v))
}

// NombreInsumoHasSuffix applies the HasSuffix predicate on the "nombre_insumo" field.
func NombreInsumoHasSuffix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasSuffix(FieldNombreInsumo, v))
}

// NombreInsumoEqualFold applies the EqualFold predicate on the "nombre_insumo" field.
func NombreInsumoEqualFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEqualFold(FieldNombreInsumo, v))
}

// NombreInsumoContainsFold applies the ContainsFold predicate on the "nombre_insumo" field.
func NombreInsumoContainsFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContainsFold(FieldNombreInsumo, v))
}

// CategoriaEQ applies the EQ predicate on the "categoria" field.
func CategoriaEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldCategoria, v))
}

// CategoriaNEQ applies the NEQ predicate on the "categoria" field.
func CategoriaNEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldCategoria, v))
}

// CategoriaIn applies the In predicate on the "categoria" field.
func CategoriaIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldCategoria, vs...))
}

// CategoriaNotIn applies the NotIn predicate on the "categoria" field.
func CategoriaNotIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldCategoria, vs...))
}

// CategoriaGT applies the GT predicate on the "categoria" field.
func CategoriaGT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldCategoria, v))
}

// CategoriaGTE applies the GTE predicate on the "categoria" field.
func CategoriaGTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldCategoria, v))
}

// CategoriaLT applies the LT predicate on the "categoria" field.
func CategoriaLT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldCategoria, v))
}

// CategoriaLTE applies the LTE predicate on the "categoria" field.
func CategoriaLTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldCategoria, v))
}

// CategoriaContains applies the Contains predicate on the "categoria" field.
func CategoriaContains(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContains(FieldCategoria, v))
}

// CategoriaHasPrefix applies the HasPrefix predicate on the "categoria" field.
func CategoriaHasPrefix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasPrefix(FieldCategoria, v))
}

// CategoriaHasSuffix applies the HasSuffix predicate on the "categoria" field.
func CategoriaHasSuffix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasSuffix(FieldCategoria, v))
}

// CategoriaEqualFold applies the EqualFold predicate on the "categoria" field.
func CategoriaEqualFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEqualFold(FieldCategoria, v))
}

// CategoriaContainsFold applies the ContainsFold predicate on the "categoria" field.
func CategoriaContainsFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContainsFold(FieldCategoria, v))
}

// ProveedorEQ applies the EQ predicate on the "proveedor" field.
func ProveedorEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldProveedor, v))
}

// ProveedorNEQ applies the NEQ predicate on the "proveedor" field.
func ProveedorNEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldProveedor, v))
}

// ProveedorIn applies the In predicate on the "proveedor" field.
func ProveedorIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldProveedor, vs...))
}

// ProveedorNotIn applies the NotIn predicate on the "proveedor" field.
func ProveedorNotIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldProveedor, vs...))
}

// ProveedorGT applies the GT predicate on the "proveedor" field.
func ProveedorGT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldProveedor, v))
}

// ProveedorGTE applies the GTE predicate on the "proveedor" field.
func ProveedorGTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldProveedor, v))
}

// ProveedorLT applies the LT predicate on the "proveedor" field.
func ProveedorLT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldProveedor, v))
}

// ProveedorLTE applies the LTE predicate on the "proveedor" field.
func ProveedorLTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldProveedor, v))
}

// ProveedorContains applies the Contains predicate on the "proveedor" field.
func ProveedorContains(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContains(FieldProveedor, v))
}

// ProveedorHasPrefix applies the HasPrefix predicate on the "proveedor" field.
func ProveedorHasPrefix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasPrefix(FieldProveedor, v))
}

// ProveedorHasSuffix applies the HasSuffix predicate on the "proveedor" field.
func ProveedorHasSuffix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasSuffix(FieldProveedor, v))
}

// ProveedorEqualFold applies the EqualFold predicate on the "proveedor" field.
func ProveedorEqualFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEqualFold(FieldProveedor, v))
}

// ProveedorContainsFold applies the ContainsFold predicate on the "proveedor" field.
func ProveedorContainsFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContainsFold(FieldProveedor, v))
}

// UnidadMedidaEQ applies the EQ predicate on the "unidad_medida" field.
func UnidadMedidaEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldUnidadMedida, v))
}

// UnidadMedidaNEQ applies the NEQ predicate on the "unidad_medida" field.
func UnidadMedidaNEQ(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldUnidadMedida, v))
}

// UnidadMedidaIn applies the In predicate on the "unidad_medida" field.
func UnidadMedidaIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldUnidadMedida, vs...))
}

// UnidadMedidaNotIn applies the NotIn predicate on the "unidad_medida" field.
func UnidadMedidaNotIn(vs ...string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldUnidadMedida, vs...))
}

// UnidadMedidaGT applies the GT predicate on the "unidad_medida" field.
func UnidadMedidaGT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldUnidadMedida, v))
}

// UnidadMedidaGTE applies the GTE predicate on the "unidad_medida" field.
func UnidadMedidaGTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldUnidadMedida, v))
}

// UnidadMedidaLT applies the LT predicate on the "unidad_medida" field.
func UnidadMedidaLT(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldUnidadMedida, v))
}

// UnidadMedidaLTE applies the LTE predicate on the "unidad_medida" field.
func UnidadMedidaLTE(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldUnidadMedida, v))
}

// UnidadMedidaContains applies the Contains predicate on the "unidad_medida" field.
func UnidadMedidaContains(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContains(FieldUnidadMedida, v))
}

// UnidadMedidaHasPrefix applies the HasPrefix predicate on the "unidad_medida" field.
func UnidadMedidaHasPrefix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasPrefix(FieldUnidadMedida, v))
}

// UnidadMedidaHasSuffix applies the HasSuffix predicate on the "unidad_medida" field.
func UnidadMedidaHasSuffix(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldHasSuffix(FieldUnidadMedida, v))
}

// UnidadMedidaEqualFold applies the EqualFold predicate on the "unidad_medida" field.
func UnidadMedidaEqualFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEqualFold(FieldUnidadMedida, v))
}

// UnidadMedidaContainsFold applies the ContainsFold predicate on the "unidad_medida" field.
func UnidadMedidaContainsFold(v string) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldContainsFold(FieldUnidadMedida, v))
}

// CostoUnitarioEQ applies the EQ predicate on the "costo_unitario" field.
func CostoUnitarioEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldCostoUnitario, v))
}

// CostoUnitarioNEQ applies the NEQ predicate on the "costo_unitario" field.
func CostoUnitarioNEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldCostoUnitario, v))
}

// CostoUnitarioIn applies the In predicate on the "costo_unitario" field.
func CostoUnitarioIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldCostoUnitario, vs...))
}

// CostoUnitarioNotIn applies the NotIn predicate on the "costo_unitario" field.
func CostoUnitarioNotIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldCostoUnitario, vs...))
}

// CostoUnitarioGT applies the GT predicate on the "costo_unitario" field.
func CostoUnitarioGT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldCostoUnitario, v))
}

// CostoUnitarioGTE applies the GTE predicate on the "costo_unitario" field.
func CostoUnitarioGTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldCostoUnitario, v))
}

// CostoUnitarioLT applies the LT predicate on the "costo_unitario" field.
func CostoUnitarioLT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldCostoUnitario, v))
}

// CostoUnitarioLTE applies the LTE predicate on the "costo_unitario" field.
func CostoUnitarioLTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldCostoUnitario, v))
}

// StockActualEQ applies the EQ predicate on the "stock_actual" field.
func StockActualEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldStockActual, v))
}

// StockActualNEQ applies the NEQ predicate on the "stock_actual" field.
func StockActualNEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldStockActual, v))
}

// StockActualIn applies the In predicate on the "stock_actual" field.
func StockActualIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldStockActual, vs...))
}

// StockActualNotIn applies the NotIn predicate on the "stock_actual" field.
func StockActualNotIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldStockActual, vs...))
}

// StockActualGT applies the GT predicate on the "stock_actual" field.
func StockActualGT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldStockActual, v))
}

// StockActualGTE applies the GTE predicate on the "stock_actual" field.
func StockActualGTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldStockActual, v))
}

// StockActualLT applies the LT predicate on the "stock_actual" field.
func StockActualLT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldStockActual, v))
}

// StockActualLTE applies the LTE predicate on the "stock_actual" field.
func StockActualLTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldStockActual, v))
}

// PuntoReordenEQ applies the EQ predicate on the "punto_reorden" field.
func PuntoReordenEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldEQ(FieldPuntoReorden, v))
}

// PuntoReordenNEQ applies the NEQ predicate on the "punto_reorden" field.
func PuntoReordenNEQ(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNEQ(FieldPuntoReorden, v))
}

// PuntoReordenIn applies the In predicate on the "punto_reorden" field.
func PuntoReordenIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldIn(FieldPuntoReorden, vs...))
}

// PuntoReordenNotIn applies the NotIn predicate on the "punto_reorden" field.
func PuntoReordenNotIn(vs ...float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldNotIn(FieldPuntoReorden, vs...))
}

// PuntoReordenGT applies the GT predicate on the "punto_reorden" field.
func PuntoReordenGT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGT(FieldPuntoReorden, v))
}

// PuntoReordenGTE applies the GTE predicate on the "punto_reorden" field.
func PuntoReordenGTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldGTE(FieldPuntoReorden, v))
}

// PuntoReordenLT applies the LT predicate on the "punto_reorden" field.
func PuntoReordenLT(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLT(FieldPuntoReorden, v))
}

// PuntoReordenLTE applies the LTE predicate on the "punto_reorden" field.
func PuntoReordenLTE(v float64) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.FieldLTE(FieldPuntoReorden, v))
}

// HasRecetas applies the HasEdge predicate on the "recetas" edge.
func HasRecetas() predicate.MateriaPrima {
	return predicate.MateriaPrima(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecetasTable, RecetasColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecetasWith applies the HasEdge predicate on the "recetas" edge with a given conditions (other predicates).
func HasRecetasWith(preds ...predicate.Recetas) predicate.MateriaPrima {
	return predicate.MateriaPrima(func(s *sql.Selector) {
		step := newRecetasStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MateriaPrima) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MateriaPrima) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MateriaPrima) predicate.MateriaPrima {
	return predicate.MateriaPrima(sql.NotPredicates(p))
}
