// Code generated by ent, DO NOT EDIT.

package productosmenu

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the productosmenu type in the database.
	Label = "productos_menu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNombreProducto holds the string denoting the nombre_producto field in the database.
	FieldNombreProducto = "nombre_producto"
	// FieldCategoriaMenu holds the string denoting the categoria_menu field in the database.
	FieldCategoriaMenu = "categoria_menu"
	// FieldPrecioVenta holds the string denoting the precio_venta field in the database.
	FieldPrecioVenta = "precio_venta"
	// EdgeRecetas holds the string denoting the recetas edge name in mutations.
	EdgeRecetas = "recetas"
	// EdgeDetallesPedido holds the string denoting the detalles_pedido edge name in mutations.
	EdgeDetallesPedido = "detalles_pedido"
	// Table holds the table name of the productosmenu in the database.
	Table = "productos_menu"
	// RecetasTable is the table that holds the recetas relation/edge.
	RecetasTable = "recetas"
	// RecetasInverseTable is the table name for the Recetas entity.
	// It exists in this package in order to avoid circular dependency with the "recetas" package.
	RecetasInverseTable = "recetas"
	// RecetasColumn is the table column denoting the recetas relation/edge.
	RecetasColumn = "productos_menu_recetas"
	// DetallesPedidoTable is the table that holds the detalles_pedido relation/edge.
	DetallesPedidoTable = "detalles_pedido"
	// DetallesPedidoInverseTable is the table name for the DetallesPedido entity.
	// It exists in this package in order to avoid circular dependency with the "detallespedido" package.
	DetallesPedidoInverseTable = "detalles_pedido"
	// DetallesPedidoColumn is the table column denoting the detalles_pedido relation/edge.
	DetallesPedidoColumn = "producto_id"
)

// Columns holds all SQL columns for productosmenu fields.
var Columns = []string{
	FieldID,
	FieldNombreProducto,
	FieldCategoriaMenu,
	FieldPrecioVenta,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NombreProductoValidator is a validator for the "nombre_producto" field. It is called by the builders before save.
	NombreProductoValidator func(string) error
	// CategoriaMenuValidator is a validator for the "categoria_menu" field. It is called by the builders before save.
	CategoriaMenuValidator func(string) error
)

// OrderOption defines the ordering options for the ProductosMenu queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNombreProducto orders the results by the nombre_producto field.
func ByNombreProducto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNombreProducto, opts...).ToFunc()
}

// ByCategoriaMenu orders the results by the categoria_menu field.
func ByCategoriaMenu(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoriaMenu, opts...).ToFunc()
}

// ByPrecioVenta orders the results by the precio_venta field.
func ByPrecioVenta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrecioVenta, opts...).ToFunc()
}

// ByRecetasCount orders the results by recetas count.
func ByRecetasCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecetasStep(), opts...)
	}
}

// ByRecetas orders the results by recetas terms.
func ByRecetas(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecetasStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDetallesPedidoCount orders the results by detalles_pedido count.
func ByDetallesPedidoCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDetallesPedidoStep(), opts...)
	}
}

// ByDetallesPedido orders the results by detalles_pedido terms.
func ByDetallesPedido(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDetallesPedidoStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRecetasStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecetasInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecetasTable, RecetasColumn),
	)
}
func newDetallesPedidoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DetallesPedidoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DetallesPedidoTable, DetallesPedidoColumn),
	)
}
