// Code generated by ent, DO NOT EDIT.

package productosmenu

import (
	"boloneria-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLTE(FieldID, id))
}

// NombreProducto applies equality check predicate on the "nombre_producto" field. It's identical to NombreProductoEQ.
func NombreProducto(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldNombreProducto, v))
}

// CategoriaMenu applies equality check predicate on the "categoria_menu" field. It's identical to CategoriaMenuEQ.
func CategoriaMenu(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldCategoriaMenu, v))
}

// PrecioVenta applies equality check predicate on the "precio_venta" field. It's identical to PrecioVentaEQ.
func PrecioVenta(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldPrecioVenta, v))
}

// NombreProductoEQ applies the EQ predicate on the "nombre_producto" field.
func NombreProductoEQ(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldNombreProducto, v))
}

// NombreProductoNEQ applies the NEQ predicate on the "nombre_producto" field.
func NombreProductoNEQ(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNEQ(FieldNombreProducto, v))
}

// NombreProductoIn applies the In predicate on the "nombre_producto" field.
func NombreProductoIn(vs ...string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldIn(FieldNombreProducto, vs...))
}

// NombreProductoNotIn applies the NotIn predicate on the "nombre_producto" field.
func NombreProductoNotIn(vs ...string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNotIn(FieldNombreProducto, vs...))
}

// NombreProductoGT applies the GT predicate on the "nombre_producto" field.
func NombreProductoGT(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGT(FieldNombreProducto, v))
}

// NombreProductoGTE applies the GTE predicate on the "nombre_producto" field.
func NombreProductoGTE(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGTE(FieldNombreProducto, v))
}

// NombreProductoLT applies the LT predicate on the "nombre_producto" field.
func NombreProductoLT(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLT(FieldNombreProducto, v))
}

// NombreProductoLTE applies the LTE predicate on the "nombre_producto" field.
func NombreProductoLTE(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLTE(FieldNombreProducto, v))
}

// NombreProductoContains applies the Contains predicate on the "nombre_producto" field.
func NombreProductoContains(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldContains(FieldNombreProducto, v))
}

// NombreProductoHasPrefix applies the HasPrefix predicate on the "nombre_producto" field.
func NombreProductoHasPrefix(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldHasPrefix(FieldNombreProducto, v))
}

// NombreProductoHasSuffix applies the HasSuffix predicate on the "nombre_producto" field.
func NombreProductoHasSuffix(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldHasSuffix(FieldNombreProducto, v))
}

// NombreProductoEqualFold applies the EqualFold predicate on the "nombre_producto" field.
func NombreProductoEqualFold(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEqualFold(FieldNombreProducto, v))
}

// NombreProductoContainsFold applies the ContainsFold predicate on the "nombre_producto" field.
func NombreProductoContainsFold(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldContainsFold(FieldNombreProducto, v))
}

// CategoriaMenuEQ applies the EQ predicate on the "categoria_menu" field.
func CategoriaMenuEQ(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldCategoriaMenu, v))
}

// CategoriaMenuNEQ applies the NEQ predicate on the "categoria_menu" field.
func CategoriaMenuNEQ(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNEQ(FieldCategoriaMenu, v))
}

// CategoriaMenuIn applies the In predicate on the "categoria_menu" field.
func CategoriaMenuIn(vs ...string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldIn(FieldCategoriaMenu, vs...))
}

// CategoriaMenuNotIn applies the NotIn predicate on the "categoria_menu" field.
func CategoriaMenuNotIn(vs ...string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNotIn(FieldCategoriaMenu, vs...))
}

// CategoriaMenuGT applies the GT predicate on the "categoria_menu" field.
func CategoriaMenuGT(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGT(FieldCategoriaMenu, v))
}

// CategoriaMenuGTE applies the GTE predicate on the "categoria_menu" field.
func CategoriaMenuGTE(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGTE(FieldCategoriaMenu, v))
}

// CategoriaMenuLT applies the LT predicate on the "categoria_menu" field.
func CategoriaMenuLT(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLT(FieldCategoriaMenu, v))
}

// CategoriaMenuLTE applies the LTE predicate on the "categoria_menu" field.
func CategoriaMenuLTE(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLTE(FieldCategoriaMenu, v))
}

// CategoriaMenuContains applies the Contains predicate on the "categoria_menu" field.
func CategoriaMenuContains(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldContains(FieldCategoriaMenu, v))
}

// CategoriaMenuHasPrefix applies the HasPrefix predicate on the "categoria_menu" field.
func CategoriaMenuHasPrefix(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldHasPrefix(FieldCategoriaMenu, v))
}

// CategoriaMenuHasSuffix applies the HasSuffix predicate on the "categoria_menu" field.
func CategoriaMenuHasSuffix(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldHasSuffix(FieldCategoriaMenu, v))
}

// CategoriaMenuEqualFold applies the EqualFold predicate on the "categoria_menu" field.
func CategoriaMenuEqualFold(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEqualFold(FieldCategoriaMenu, v))
}

// CategoriaMenuContainsFold applies the ContainsFold predicate on the "categoria_menu" field.
func CategoriaMenuContainsFold(v string) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldContainsFold(FieldCategoriaMenu, v))
}

// PrecioVentaEQ applies the EQ predicate on the "precio_venta" field.
func PrecioVentaEQ(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldEQ(FieldPrecioVenta, v))
}

// PrecioVentaNEQ applies the NEQ predicate on the "precio_venta" field.
func PrecioVentaNEQ(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNEQ(FieldPrecioVenta, v))
}

// PrecioVentaIn applies the In predicate on the "precio_venta" field.
func PrecioVentaIn(vs ...float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldIn(FieldPrecioVenta, vs...))
}

// PrecioVentaNotIn applies the NotIn predicate on the "precio_venta" field.
func PrecioVentaNotIn(vs ...float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldNotIn(FieldPrecioVenta, vs...))
}

// PrecioVentaGT applies the GT predicate on the "precio_venta" field.
func PrecioVentaGT(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGT(FieldPrecioVenta, v))
}

// PrecioVentaGTE applies the GTE predicate on the "precio_venta" field.
func PrecioVentaGTE(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldGTE(FieldPrecioVenta, v))
}

// PrecioVentaLT applies the LT predicate on the "precio_venta" field.
func PrecioVentaLT(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLT(FieldPrecioVenta, v))
}

// PrecioVentaLTE applies the LTE predicate on the "precio_venta" field.
func PrecioVentaLTE(v float64) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.FieldLTE(FieldPrecioVenta, v))
}

// HasRecetas applies the HasEdge predicate on the "recetas" edge.
func HasRecetas() predicate.ProductosMenu {
	return predicate.ProductosMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RecetasTable, RecetasColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecetasWith applies the HasEdge predicate on the "recetas" edge with a given conditions (other predicates).
func HasRecetasWith(preds ...predicate.Recetas) predicate.ProductosMenu {
	return predicate.ProductosMenu(func(s *sql.Selector) {
		step := newRecetasStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDetallesPedido applies the HasEdge predicate on the "detalles_pedido" edge.
func HasDetallesPedido() predicate.ProductosMenu {
	return predicate.ProductosMenu(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DetallesPedidoTable, DetallesPedidoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDetallesPedidoWith applies the HasEdge predicate on the "detalles_pedido" edge with a given conditions (other predicates).
func HasDetallesPedidoWith(preds ...predicate.DetallesPedido) predicate.ProductosMenu {
	return predicate.ProductosMenu(func(s *sql.Selector) {
		step := newDetallesPedidoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductosMenu) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductosMenu) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductosMenu) predicate.ProductosMenu {
	return predicate.ProductosMenu(sql.NotPredicates(p))
}
