// Code generated by ent, DO NOT EDIT.

package recetas

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recetas type in the database.
	Label = "recetas"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCantidadNecesaria holds the string denoting the cantidad_necesaria field in the database.
	FieldCantidadNecesaria = "cantidad_necesaria"
	// EdgeProducto holds the string denoting the producto edge name in mutations.
	EdgeProducto = "producto"
	// EdgeMateriaPrima holds the string denoting the materia_prima edge name in mutations.
	EdgeMateriaPrima = "materia_prima"
	// Table holds the table name of the recetas in the database.
	Table = "recetas"
	// ProductoTable is the table that holds the producto relation/edge.
	ProductoTable = "recetas"
	// ProductoInverseTable is the table name for the ProductosMenu entity.
	// It exists in this package in order to avoid circular dependency with the "productosmenu" package.
	ProductoInverseTable = "productos_menu"
	// ProductoColumn is the table column denoting the producto relation/edge.
	ProductoColumn = "productos_menu_recetas"
	// MateriaPrimaTable is the table that holds the materia_prima relation/edge.
	MateriaPrimaTable = "recetas"
	// MateriaPrimaInverseTable is the table name for the MateriaPrima entity.
	// It exists in this package in order to avoid circular dependency with the "materiaprima" package.
	MateriaPrimaInverseTable = "materia_prima"
	// MateriaPrimaColumn is the table column denoting the materia_prima relation/edge.
	MateriaPrimaColumn = "materia_prima_recetas"
)

// Columns holds all SQL columns for recetas fields.
var Columns = []string{
	FieldID,
	FieldCantidadNecesaria,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "recetas"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"materia_prima_recetas",
	"productos_menu_recetas",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Recetas queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCantidadNecesaria orders the results by the cantidad_necesaria field.
func ByCantidadNecesaria(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCantidadNecesaria, opts...).ToFunc()
}

// ByProductoField orders the results by producto field.
func ByProductoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductoStep(), sql.OrderByField(field, opts...))
	}
}

// ByMateriaPrimaField orders the results by materia_prima field.
func ByMateriaPrimaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMateriaPrimaStep(), sql.OrderByField(field, opts...))
	}
}
func newProductoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductoTable, ProductoColumn),
	)
}
func newMateriaPrimaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MateriaPrimaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MateriaPrimaTable, MateriaPrimaColumn),
	)
}
