// Code generated by ent, DO NOT EDIT.

package recetas

import (
	"boloneria-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Recetas {
	return predicate.Recetas(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Recetas {
	return predicate.Recetas(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Recetas {
	return predicate.Recetas(sql.FieldLTE(FieldID, id))
}

// CantidadNecesaria applies equality check predicate on the "cantidad_necesaria" field. It's identical to CantidadNecesariaEQ.
func CantidadNecesaria(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldEQ(FieldCantidadNecesaria, v))
}

// CantidadNecesariaEQ applies the EQ predicate on the "cantidad_necesaria" field.
func CantidadNecesariaEQ(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldEQ(FieldCantidadNecesaria, v))
}

// CantidadNecesariaNEQ applies the NEQ predicate on the "cantidad_necesaria" field.
func CantidadNecesariaNEQ(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldNEQ(FieldCantidadNecesaria, v))
}

// CantidadNecesariaIn applies the In predicate on the "cantidad_necesaria" field.
func CantidadNecesariaIn(vs ...float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldIn(FieldCantidadNecesaria, vs...))
}

// CantidadNecesariaNotIn applies the NotIn predicate on the "cantidad_necesaria" field.
func CantidadNecesariaNotIn(vs ...float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldNotIn(FieldCantidadNecesaria, vs...))
}

// CantidadNecesariaGT applies the GT predicate on the "cantidad_necesaria" field.
func CantidadNecesariaGT(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldGT(FieldCantidadNecesaria, v))
}

// CantidadNecesariaGTE applies the GTE predicate on the "cantidad_necesaria" field.
func CantidadNecesariaGTE(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldGTE(FieldCantidadNecesaria, v))
}

// CantidadNecesariaLT applies the LT predicate on the "cantidad_necesaria" field.
func CantidadNecesariaLT(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldLT(FieldCantidadNecesaria, v))
}

// CantidadNecesariaLTE applies the LTE predicate on the "cantidad_necesaria" field.
func CantidadNecesariaLTE(v float64) predicate.Recetas {
	return predicate.Recetas(sql.FieldLTE(FieldCantidadNecesaria, v))
}

// HasProducto applies the HasEdge predicate on the "producto" edge.
func HasProducto() predicate.Recetas {
	return predicate.Recetas(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductoTable, ProductoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductoWith applies the HasEdge predicate on the "producto" edge with a given conditions (other predicates).
func HasProductoWith(preds ...predicate.ProductosMenu) predicate.Recetas {
	return predicate.Recetas(func(s *sql.Selector) {
		step := newProductoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMateriaPrima applies the HasEdge predicate on the "materia_prima" edge.
func HasMateriaPrima() predicate.Recetas {
	return predicate.Recetas(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MateriaPrimaTable, MateriaPrimaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMateriaPrimaWith applies the HasEdge predicate on the "materia_prima" edge with a given conditions (other predicates).
func HasMateriaPrimaWith(preds ...predicate.MateriaPrima) predicate.Recetas {
	return predicate.Recetas(func(s *sql.Selector) {
		step := newMateriaPrimaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Recetas) predicate.Recetas {
	return predicate.Recetas(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Recetas) predicate.Recetas {
	return predicate.Recetas(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Recetas) predicate.Recetas {
	return predicate.Recetas(sql.NotPredicates(p))
}
