// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientesUpdate is the builder for updating Clientes entities.
type ClientesUpdate struct {
	config
	hooks    []Hook
	mutation *ClientesMutation
}

// Where appends a list predicates to the ClientesUpdate builder.
func (_u *ClientesUpdate) Where(ps ...predicate.Clientes) *ClientesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNombreCompleto sets the "nombre_completo" field.
func (_u *ClientesUpdate) SetNombreCompleto(v string) *ClientesUpdate {
	_u.mutation.SetNombreCompleto(v)
	return _u
}

// SetNillableNombreCompleto sets the "nombre_completo" field if the given value is not nil.
func (_u *ClientesUpdate) SetNillableNombreCompleto(v *string) *ClientesUpdate {
	if v != nil {
		_u.SetNombreCompleto(*v)
	}
	return _u
}

// SetTelefono sets the "telefono" field.
func (_u *ClientesUpdate) SetTelefono(v string) *ClientesUpdate {
	_u.mutation.SetTelefono(v)
	return _u
}

// SetNillableTelefono sets the "telefono" field if the given value is not nil.
func (_u *ClientesUpdate) SetNillableTelefono(v *string) *ClientesUpdate {
	if v != nil {
		_u.SetTelefono(*v)
	}
	return _u
}

// ClearTelefono clears the value of the "telefono" field.
func (_u *ClientesUpdate) ClearTelefono() *ClientesUpdate {
	_u.mutation.ClearTelefono()
	return _u
}

// SetEmail sets the "email" field.
func (_u *ClientesUpdate) SetEmail(v string) *ClientesUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ClientesUpdate) SetNillableEmail(v *string) *ClientesUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *ClientesUpdate) ClearEmail() *ClientesUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetDireccion sets the "direccion" field.
func (_u *ClientesUpdate) SetDireccion(v string) *ClientesUpdate {
	_u.mutation.SetDireccion(v)
	return _u
}

// SetNillableDireccion sets the "direccion" field if the given value is not nil.
func (_u *ClientesUpdate) SetNillableDireccion(v *string) *ClientesUpdate {
	if v != nil {
		_u.SetDireccion(*v)
	}
	return _u
}

// ClearDireccion clears the value of the "direccion" field.
func (_u *ClientesUpdate) ClearDireccion() *ClientesUpdate {
	_u.mutation.ClearDireccion()
	return _u
}

// AddPedidoIDs adds the "pedidos" edge to the Pedidos entity by IDs.
func (_u *ClientesUpdate) AddPedidoIDs(ids ...int) *ClientesUpdate {
	_u.mutation.AddPedidoIDs(ids...)
	return _u
}

// AddPedidos adds the "pedidos" edges to the Pedidos entity.
func (_u *ClientesUpdate) AddPedidos(v ...*Pedidos) *ClientesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPedidoIDs(ids...)
}

// Mutation returns the ClientesMutation object of the builder.
func (_u *ClientesUpdate) Mutation() *ClientesMutation {
	return _u.mutation
}

// ClearPedidos clears all "pedidos" edges to the Pedidos entity.
func (_u *ClientesUpdate) ClearPedidos() *ClientesUpdate {
	_u.mutation.ClearPedidos()
	return _u
}

// RemovePedidoIDs removes the "pedidos" edge to Pedidos entities by IDs.
func (_u *ClientesUpdate) RemovePedidoIDs(ids ...int) *ClientesUpdate {
	_u.mutation.RemovePedidoIDs(ids...)
	return _u
}

// RemovePedidos removes "pedidos" edges to Pedidos entities.
func (_u *ClientesUpdate) RemovePedidos(v ...*Pedidos) *ClientesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePedidoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientesUpdate) check() error {
	if v, ok := _u.mutation.NombreCompleto(); ok {
		if err := clientes.NombreCompletoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_completo", err: fmt.Errorf(`ent: validator failed for field "Clientes.nombre_completo": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientes.Table, clientes.Columns, sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreCompleto(); ok {
		_spec.SetField(clientes.FieldNombreCompleto, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefono(); ok {
		_spec.SetField(clientes.FieldTelefono, field.TypeString, value)
	}
	if _u.mutation.TelefonoCleared() {
		_spec.ClearField(clientes.FieldTelefono, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(clientes.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(clientes.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Direccion(); ok {
		_spec.SetField(clientes.FieldDireccion, field.TypeString, value)
	}
	if _u.mutation.DireccionCleared() {
		_spec.ClearField(clientes.FieldDireccion, field.TypeString)
	}
	if _u.mutation.PedidosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPedidosIDs(); len(nodes) > 0 && !_u.mutation.PedidosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PedidosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientesUpdateOne is the builder for updating a single Clientes entity.
type ClientesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientesMutation
}

// SetNombreCompleto sets the "nombre_completo" field.
func (_u *ClientesUpdateOne) SetNombreCompleto(v string) *ClientesUpdateOne {
	_u.mutation.SetNombreCompleto(v)
	return _u
}

// SetNillableNombreCompleto sets the "nombre_completo" field if the given value is not nil.
func (_u *ClientesUpdateOne) SetNillableNombreCompleto(v *string) *ClientesUpdateOne {
	if v != nil {
		_u.SetNombreCompleto(*v)
	}
	return _u
}

// SetTelefono sets the "telefono" field.
func (_u *ClientesUpdateOne) SetTelefono(v string) *ClientesUpdateOne {
	_u.mutation.SetTelefono(v)
	return _u
}

// SetNillableTelefono sets the "telefono" field if the given value is not nil.
func (_u *ClientesUpdateOne) SetNillableTelefono(v *string) *ClientesUpdateOne {
	if v != nil {
		_u.SetTelefono(*v)
	}
	return _u
}

// ClearTelefono clears the value of the "telefono" field.
func (_u *ClientesUpdateOne) ClearTelefono() *ClientesUpdateOne {
	_u.mutation.ClearTelefono()
	return _u
}

// SetEmail sets the "email" field.
func (_u *ClientesUpdateOne) SetEmail(v string) *ClientesUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *ClientesUpdateOne) SetNillableEmail(v *string) *ClientesUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *ClientesUpdateOne) ClearEmail() *ClientesUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetDireccion sets the "direccion" field.
func (_u *ClientesUpdateOne) SetDireccion(v string) *ClientesUpdateOne {
	_u.mutation.SetDireccion(v)
	return _u
}

// SetNillableDireccion sets the "direccion" field if the given value is not nil.
func (_u *ClientesUpdateOne) SetNillableDireccion(v *string) *ClientesUpdateOne {
	if v != nil {
		_u.SetDireccion(*v)
	}
	return _u
}

// ClearDireccion clears the value of the "direccion" field.
func (_u *ClientesUpdateOne) ClearDireccion() *ClientesUpdateOne {
	_u.mutation.ClearDireccion()
	return _u
}

// AddPedidoIDs adds the "pedidos" edge to the Pedidos entity by IDs.
func (_u *ClientesUpdateOne) AddPedidoIDs(ids ...int) *ClientesUpdateOne {
	_u.mutation.AddPedidoIDs(ids...)
	return _u
}

// AddPedidos adds the "pedidos" edges to the Pedidos entity.
func (_u *ClientesUpdateOne) AddPedidos(v ...*Pedidos) *ClientesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPedidoIDs(ids...)
}

// Mutation returns the ClientesMutation object of the builder.
func (_u *ClientesUpdateOne) Mutation() *ClientesMutation {
	return _u.mutation
}

// ClearPedidos clears all "pedidos" edges to the Pedidos entity.
func (_u *ClientesUpdateOne) ClearPedidos() *ClientesUpdateOne {
	_u.mutation.ClearPedidos()
	return _u
}

// RemovePedidoIDs removes the "pedidos" edge to Pedidos entities by IDs.
func (_u *ClientesUpdateOne) RemovePedidoIDs(ids ...int) *ClientesUpdateOne {
	_u.mutation.RemovePedidoIDs(ids...)
	return _u
}

// RemovePedidos removes "pedidos" edges to Pedidos entities.
func (_u *ClientesUpdateOne) RemovePedidos(v ...*Pedidos) *ClientesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePedidoIDs(ids...)
}

// Where appends a list predicates to the ClientesUpdate builder.
func (_u *ClientesUpdateOne) Where(ps ...predicate.Clientes) *ClientesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientesUpdateOne) Select(field string, fields ...string) *ClientesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Clientes entity.
func (_u *ClientesUpdateOne) Save(ctx context.Context) (*Clientes, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientesUpdateOne) SaveX(ctx context.Context) *Clientes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientesUpdateOne) check() error {
	if v, ok := _u.mutation.NombreCompleto(); ok {
		if err := clientes.NombreCompletoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_completo", err: fmt.Errorf(`ent: validator failed for field "Clientes.nombre_completo": %w`, err)}
		}
	}
	return nil
}

func (_u *ClientesUpdateOne) sqlSave(ctx context.Context) (_node *Clientes, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientes.Table, clientes.Columns, sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Clientes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientes.FieldID)
		for _, f := range fields {
			if !clientes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreCompleto(); ok {
		_spec.SetField(clientes.FieldNombreCompleto, field.TypeString, value)
	}
	if value, ok := _u.mutation.Telefono(); ok {
		_spec.SetField(clientes.FieldTelefono, field.TypeString, value)
	}
	if _u.mutation.TelefonoCleared() {
		_spec.ClearField(clientes.FieldTelefono, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(clientes.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(clientes.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Direccion(); ok {
		_spec.SetField(clientes.FieldDireccion, field.TypeString, value)
	}
	if _u.mutation.DireccionCleared() {
		_spec.ClearField(clientes.FieldDireccion, field.TypeString)
	}
	if _u.mutation.PedidosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPedidosIDs(); len(nodes) > 0 && !_u.mutation.PedidosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PedidosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Clientes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
