// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/pedidos"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientesCreate is the builder for creating a Clientes entity.
type ClientesCreate struct {
	config
	mutation *ClientesMutation
	hooks    []Hook
}

// SetNombreCompleto sets the "nombre_completo" field.
func (_c *ClientesCreate) SetNombreCompleto(v string) *ClientesCreate {
	_c.mutation.SetNombreCompleto(v)
	return _c
}

// SetTelefono sets the "telefono" field.
func (_c *ClientesCreate) SetTelefono(v string) *ClientesCreate {
	_c.mutation.SetTelefono(v)
	return _c
}

// SetNillableTelefono sets the "telefono" field if the given value is not nil.
func (_c *ClientesCreate) SetNillableTelefono(v *string) *ClientesCreate {
	if v != nil {
		_c.SetTelefono(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *ClientesCreate) SetEmail(v string) *ClientesCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *ClientesCreate) SetNillableEmail(v *string) *ClientesCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetDireccion sets the "direccion" field.
func (_c *ClientesCreate) SetDireccion(v string) *ClientesCreate {
	_c.mutation.SetDireccion(v)
	return _c
}

// SetNillableDireccion sets the "direccion" field if the given value is not nil.
func (_c *ClientesCreate) SetNillableDireccion(v *string) *ClientesCreate {
	if v != nil {
		_c.SetDireccion(*v)
	}
	return _c
}

// AddPedidoIDs adds the "pedidos" edge to the Pedidos entity by IDs.
func (_c *ClientesCreate) AddPedidoIDs(ids ...int) *ClientesCreate {
	_c.mutation.AddPedidoIDs(ids...)
	return _c
}

// AddPedidos adds the "pedidos" edges to the Pedidos entity.
func (_c *ClientesCreate) AddPedidos(v ...*Pedidos) *ClientesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPedidoIDs(ids...)
}

// Mutation returns the ClientesMutation object of the builder.
func (_c *ClientesCreate) Mutation() *ClientesMutation {
	return _c.mutation
}

// Save creates the Clientes in the database.
func (_c *ClientesCreate) Save(ctx context.Context) (*Clientes, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientesCreate) SaveX(ctx context.Context) *Clientes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientesCreate) check() error {
	if _, ok := _c.mutation.NombreCompleto(); !ok {
		return &ValidationError{Name: "nombre_completo", err: errors.New(`ent: missing required field "Clientes.nombre_completo"`)}
	}
	if v, ok := _c.mutation.NombreCompleto(); ok {
		if err := clientes.NombreCompletoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_completo", err: fmt.Errorf(`ent: validator failed for field "Clientes.nombre_completo": %w`, err)}
		}
	}
	return nil
}

func (_c *ClientesCreate) sqlSave(ctx context.Context) (*Clientes, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientesCreate) createSpec() (*Clientes, *sqlgraph.CreateSpec) {
	var (
		_node = &Clientes{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientes.Table, sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NombreCompleto(); ok {
		_spec.SetField(clientes.FieldNombreCompleto, field.TypeString, value)
		_node.NombreCompleto = value
	}
	if value, ok := _c.mutation.Telefono(); ok {
		_spec.SetField(clientes.FieldTelefono, field.TypeString, value)
		_node.Telefono = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(clientes.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.Direccion(); ok {
		_spec.SetField(clientes.FieldDireccion, field.TypeString, value)
		_node.Direccion = &value
	}
	if nodes := _c.mutation.PedidosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientes.PedidosTable,
			Columns: []string{clientes.PedidosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientesCreateBulk is the builder for creating many Clientes entities in bulk.
type ClientesCreateBulk struct {
	config
	err      error
	builders []*ClientesCreate
}

// Save creates the Clientes entities in the database.
func (_c *ClientesCreateBulk) Save(ctx context.Context) ([]*Clientes, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Clientes, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientesCreateBulk) SaveX(ctx context.Context) []*Clientes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
