// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"boloneria-app/ent/migrate"

	"boloneria-app/ent/clientes"
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/recetas"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Clientes is the client for interacting with the Clientes builders.
	Clientes *ClientesClient
	// DetallesPedido is the client for interacting with the DetallesPedido builders.
	DetallesPedido *DetallesPedidoClient
	// MateriaPrima is the client for interacting with the MateriaPrima builders.
	MateriaPrima *MateriaPrimaClient
	// Pedidos is the client for interacting with the Pedidos builders.
	Pedidos *PedidosClient
	// ProductosMenu is the client for interacting with the ProductosMenu builders.
	ProductosMenu *ProductosMenuClient
	// Recetas is the client for interacting with the Recetas builders.
	Recetas *RecetasClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Clientes = NewClientesClient(c.config)
	c.DetallesPedido = NewDetallesPedidoClient(c.config)
	c.MateriaPrima = NewMateriaPrimaClient(c.config)
	c.Pedidos = NewPedidosClient(c.config)
	c.ProductosMenu = NewProductosMenuClient(c.config)
	c.Recetas = NewRecetasClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Clientes:       NewClientesClient(cfg),
		DetallesPedido: NewDetallesPedidoClient(cfg),
		MateriaPrima:   NewMateriaPrimaClient(cfg),
		Pedidos:        NewPedidosClient(cfg),
		ProductosMenu:  NewProductosMenuClient(cfg),
		Recetas:        NewRecetasClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Clientes:       NewClientesClient(cfg),
		DetallesPedido: NewDetallesPedidoClient(cfg),
		MateriaPrima:   NewMateriaPrimaClient(cfg),
		Pedidos:        NewPedidosClient(cfg),
		ProductosMenu:  NewProductosMenuClient(cfg),
		Recetas:        NewRecetasClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Clientes.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Clientes, c.DetallesPedido, c.MateriaPrima, c.Pedidos, c.ProductosMenu,
		c.Recetas,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Clientes, c.DetallesPedido, c.MateriaPrima, c.Pedidos, c.ProductosMenu,
		c.Recetas,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ClientesMutation:
		return c.Clientes.mutate(ctx, m)
	case *DetallesPedidoMutation:
		return c.DetallesPedido.mutate(ctx, m)
	case *MateriaPrimaMutation:
		return c.MateriaPrima.mutate(ctx, m)
	case *PedidosMutation:
		return c.Pedidos.mutate(ctx, m)
	case *ProductosMenuMutation:
		return c.ProductosMenu.mutate(ctx, m)
	case *RecetasMutation:
		return c.Recetas.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ClientesClient is a client for the Clientes schema.
type ClientesClient struct {
	config
}

// NewClientesClient returns a client for the Clientes from the given config.
func NewClientesClient(c config) *ClientesClient {
	return &ClientesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `clientes.Hooks(f(g(h())))`.
func (c *ClientesClient) Use(hooks ...Hook) {
	c.hooks.Clientes = append(c.hooks.Clientes, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `clientes.Intercept(f(g(h())))`.
func (c *ClientesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Clientes = append(c.inters.Clientes, interceptors...)
}

// Create returns a builder for creating a Clientes entity.
func (c *ClientesClient) Create() *ClientesCreate {
	mutation := newClientesMutation(c.config, OpCreate)
	return &ClientesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Clientes entities.
func (c *ClientesClient) CreateBulk(builders ...*ClientesCreate) *ClientesCreateBulk {
	return &ClientesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ClientesClient) MapCreateBulk(slice any, setFunc func(*ClientesCreate, int)) *ClientesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ClientesCreateBulk{err: fmt.Errorf("calling to ClientesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ClientesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ClientesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Clientes.
func (c *ClientesClient) Update() *ClientesUpdate {
	mutation := newClientesMutation(c.config, OpUpdate)
	return &ClientesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClientesClient) UpdateOne(_m *Clientes) *ClientesUpdateOne {
	mutation := newClientesMutation(c.config, OpUpdateOne, withClientes(_m))
	return &ClientesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClientesClient) UpdateOneID(id int) *ClientesUpdateOne {
	mutation := newClientesMutation(c.config, OpUpdateOne, withClientesID(id))
	return &ClientesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Clientes.
func (c *ClientesClient) Delete() *ClientesDelete {
	mutation := newClientesMutation(c.config, OpDelete)
	return &ClientesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClientesClient) DeleteOne(_m *Clientes) *ClientesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClientesClient) DeleteOneID(id int) *ClientesDeleteOne {
	builder := c.Delete().Where(clientes.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClientesDeleteOne{builder}
}

// Query returns a query builder for Clientes.
func (c *ClientesClient) Query() *ClientesQuery {
	return &ClientesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClientes},
		inters: c.Interceptors(),
	}
}

// Get returns a Clientes entity by its id.
func (c *ClientesClient) Get(ctx context.Context, id int) (*Clientes, error) {
	return c.Query().Where(clientes.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClientesClient) GetX(ctx context.Context, id int) *Clientes {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPedidos queries the pedidos edge of a Clientes.
func (c *ClientesClient) QueryPedidos(_m *Clientes) *PedidosQuery {
	query := (&PedidosClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(clientes.Table, clientes.FieldID, id),
			sqlgraph.To(pedidos.Table, pedidos.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clientes.PedidosTable, clientes.PedidosColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClientesClient) Hooks() []Hook {
	return c.hooks.Clientes
}

// Interceptors returns the client interceptors.
func (c *ClientesClient) Interceptors() []Interceptor {
	return c.inters.Clientes
}

func (c *ClientesClient) mutate(ctx context.Context, m *ClientesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClientesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClientesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClientesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClientesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Clientes mutation op: %q", m.Op())
	}
}

// DetallesPedidoClient is a client for the DetallesPedido schema.
type DetallesPedidoClient struct {
	config
}

// NewDetallesPedidoClient returns a client for the DetallesPedido from the given config.
func NewDetallesPedidoClient(c config) *DetallesPedidoClient {
	return &DetallesPedidoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `detallespedido.Hooks(f(g(h())))`.
func (c *DetallesPedidoClient) Use(hooks ...Hook) {
	c.hooks.DetallesPedido = append(c.hooks.DetallesPedido, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `detallespedido.Intercept(f(g(h())))`.
func (c *DetallesPedidoClient) Intercept(interceptors ...Interceptor) {
	c.inters.DetallesPedido = append(c.inters.DetallesPedido, interceptors...)
}

// Create returns a builder for creating a DetallesPedido entity.
func (c *DetallesPedidoClient) Create() *DetallesPedidoCreate {
	mutation := newDetallesPedidoMutation(c.config, OpCreate)
	return &DetallesPedidoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DetallesPedido entities.
func (c *DetallesPedidoClient) CreateBulk(builders ...*DetallesPedidoCreate) *DetallesPedidoCreateBulk {
	return &DetallesPedidoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DetallesPedidoClient) MapCreateBulk(slice any, setFunc func(*DetallesPedidoCreate, int)) *DetallesPedidoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DetallesPedidoCreateBulk{err: fmt.Errorf("calling to DetallesPedidoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DetallesPedidoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DetallesPedidoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DetallesPedido.
func (c *DetallesPedidoClient) Update() *DetallesPedidoUpdate {
	mutation := newDetallesPedidoMutation(c.config, OpUpdate)
	return &DetallesPedidoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DetallesPedidoClient) UpdateOne(_m *DetallesPedido) *DetallesPedidoUpdateOne {
	mutation := newDetallesPedidoMutation(c.config, OpUpdateOne, withDetallesPedido(_m))
	return &DetallesPedidoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DetallesPedidoClient) UpdateOneID(id int) *DetallesPedidoUpdateOne {
	mutation := newDetallesPedidoMutation(c.config, OpUpdateOne, withDetallesPedidoID(id))
	return &DetallesPedidoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DetallesPedido.
func (c *DetallesPedidoClient) Delete() *DetallesPedidoDelete {
	mutation := newDetallesPedidoMutation(c.config, OpDelete)
	return &DetallesPedidoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DetallesPedidoClient) DeleteOne(_m *DetallesPedido) *DetallesPedidoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DetallesPedidoClient) DeleteOneID(id int) *DetallesPedidoDeleteOne {
	builder := c.Delete().Where(detallespedido.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DetallesPedidoDeleteOne{builder}
}

// Query returns a query builder for DetallesPedido.
func (c *DetallesPedidoClient) Query() *DetallesPedidoQuery {
	return &DetallesPedidoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDetallesPedido},
		inters: c.Interceptors(),
	}
}

// Get returns a DetallesPedido entity by its id.
func (c *DetallesPedidoClient) Get(ctx context.Context, id int) (*DetallesPedido, error) {
	return c.Query().Where(detallespedido.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DetallesPedidoClient) GetX(ctx context.Context, id int) *DetallesPedido {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPedido queries the pedido edge of a DetallesPedido.
func (c *DetallesPedidoClient) QueryPedido(_m *DetallesPedido) *PedidosQuery {
	query := (&PedidosClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(detallespedido.Table, detallespedido.FieldID, id),
			sqlgraph.To(pedidos.Table, pedidos.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, detallespedido.PedidoTable, detallespedido.PedidoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProducto queries the producto edge of a DetallesPedido.
func (c *DetallesPedidoClient) QueryProducto(_m *DetallesPedido) *ProductosMenuQuery {
	query := (&ProductosMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(detallespedido.Table, detallespedido.FieldID, id),
			sqlgraph.To(productosmenu.Table, productosmenu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, detallespedido.ProductoTable, detallespedido.ProductoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DetallesPedidoClient) Hooks() []Hook {
	return c.hooks.DetallesPedido
}

// Interceptors returns the client interceptors.
func (c *DetallesPedidoClient) Interceptors() []Interceptor {
	return c.inters.DetallesPedido
}

func (c *DetallesPedidoClient) mutate(ctx context.Context, m *DetallesPedidoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DetallesPedidoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DetallesPedidoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DetallesPedidoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DetallesPedidoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DetallesPedido mutation op: %q", m.Op())
	}
}

// MateriaPrimaClient is a client for the MateriaPrima schema.
type MateriaPrimaClient struct {
	config
}

// NewMateriaPrimaClient returns a client for the MateriaPrima from the given config.
func NewMateriaPrimaClient(c config) *MateriaPrimaClient {
	return &MateriaPrimaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `materiaprima.Hooks(f(g(h())))`.
func (c *MateriaPrimaClient) Use(hooks ...Hook) {
	c.hooks.MateriaPrima = append(c.hooks.MateriaPrima, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `materiaprima.Intercept(f(g(h())))`.
func (c *MateriaPrimaClient) Intercept(interceptors ...Interceptor) {
	c.inters.MateriaPrima = append(c.inters.MateriaPrima, interceptors...)
}

// Create returns a builder for creating a MateriaPrima entity.
func (c *MateriaPrimaClient) Create() *MateriaPrimaCreate {
	mutation := newMateriaPrimaMutation(c.config, OpCreate)
	return &MateriaPrimaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MateriaPrima entities.
func (c *MateriaPrimaClient) CreateBulk(builders ...*MateriaPrimaCreate) *MateriaPrimaCreateBulk {
	return &MateriaPrimaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MateriaPrimaClient) MapCreateBulk(slice any, setFunc func(*MateriaPrimaCreate, int)) *MateriaPrimaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MateriaPrimaCreateBulk{err: fmt.Errorf("calling to MateriaPrimaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MateriaPrimaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MateriaPrimaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MateriaPrima.
func (c *MateriaPrimaClient) Update() *MateriaPrimaUpdate {
	mutation := newMateriaPrimaMutation(c.config, OpUpdate)
	return &MateriaPrimaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MateriaPrimaClient) UpdateOne(_m *MateriaPrima) *MateriaPrimaUpdateOne {
	mutation := newMateriaPrimaMutation(c.config, OpUpdateOne, withMateriaPrima(_m))
	return &MateriaPrimaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MateriaPrimaClient) UpdateOneID(id int) *MateriaPrimaUpdateOne {
	mutation := newMateriaPrimaMutation(c.config, OpUpdateOne, withMateriaPrimaID(id))
	return &MateriaPrimaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MateriaPrima.
func (c *MateriaPrimaClient) Delete() *MateriaPrimaDelete {
	mutation := newMateriaPrimaMutation(c.config, OpDelete)
	return &MateriaPrimaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MateriaPrimaClient) DeleteOne(_m *MateriaPrima) *MateriaPrimaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MateriaPrimaClient) DeleteOneID(id int) *MateriaPrimaDeleteOne {
	builder := c.Delete().Where(materiaprima.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MateriaPrimaDeleteOne{builder}
}

// Query returns a query builder for MateriaPrima.
func (c *MateriaPrimaClient) Query() *MateriaPrimaQuery {
	return &MateriaPrimaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMateriaPrima},
		inters: c.Interceptors(),
	}
}

// Get returns a MateriaPrima entity by its id.
func (c *MateriaPrimaClient) Get(ctx context.Context, id int) (*MateriaPrima, error) {
	return c.Query().Where(materiaprima.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MateriaPrimaClient) GetX(ctx context.Context, id int) *MateriaPrima {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecetas queries the recetas edge of a MateriaPrima.
func (c *MateriaPrimaClient) QueryRecetas(_m *MateriaPrima) *RecetasQuery {
	query := (&RecetasClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(materiaprima.Table, materiaprima.FieldID, id),
			sqlgraph.To(recetas.Table, recetas.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, materiaprima.RecetasTable, materiaprima.RecetasColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MateriaPrimaClient) Hooks() []Hook {
	return c.hooks.MateriaPrima
}

// Interceptors returns the client interceptors.
func (c *MateriaPrimaClient) Interceptors() []Interceptor {
	return c.inters.MateriaPrima
}

func (c *MateriaPrimaClient) mutate(ctx context.Context, m *MateriaPrimaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MateriaPrimaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MateriaPrimaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MateriaPrimaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MateriaPrimaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MateriaPrima mutation op: %q", m.Op())
	}
}

// PedidosClient is a client for the Pedidos schema.
type PedidosClient struct {
	config
}

// NewPedidosClient returns a client for the Pedidos from the given config.
func NewPedidosClient(c config) *PedidosClient {
	return &PedidosClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pedidos.Hooks(f(g(h())))`.
func (c *PedidosClient) Use(hooks ...Hook) {
	c.hooks.Pedidos = append(c.hooks.Pedidos, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pedidos.Intercept(f(g(h())))`.
func (c *PedidosClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pedidos = append(c.inters.Pedidos, interceptors...)
}

// Create returns a builder for creating a Pedidos entity.
func (c *PedidosClient) Create() *PedidosCreate {
	mutation := newPedidosMutation(c.config, OpCreate)
	return &PedidosCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pedidos entities.
func (c *PedidosClient) CreateBulk(builders ...*PedidosCreate) *PedidosCreateBulk {
	return &PedidosCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PedidosClient) MapCreateBulk(slice any, setFunc func(*PedidosCreate, int)) *PedidosCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PedidosCreateBulk{err: fmt.Errorf("calling to PedidosClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PedidosCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PedidosCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pedidos.
func (c *PedidosClient) Update() *PedidosUpdate {
	mutation := newPedidosMutation(c.config, OpUpdate)
	return &PedidosUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PedidosClient) UpdateOne(_m *Pedidos) *PedidosUpdateOne {
	mutation := newPedidosMutation(c.config, OpUpdateOne, withPedidos(_m))
	return &PedidosUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PedidosClient) UpdateOneID(id int) *PedidosUpdateOne {
	mutation := newPedidosMutation(c.config, OpUpdateOne, withPedidosID(id))
	return &PedidosUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pedidos.
func (c *PedidosClient) Delete() *PedidosDelete {
	mutation := newPedidosMutation(c.config, OpDelete)
	return &PedidosDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PedidosClient) DeleteOne(_m *Pedidos) *PedidosDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PedidosClient) DeleteOneID(id int) *PedidosDeleteOne {
	builder := c.Delete().Where(pedidos.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PedidosDeleteOne{builder}
}

// Query returns a query builder for Pedidos.
func (c *PedidosClient) Query() *PedidosQuery {
	return &PedidosQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePedidos},
		inters: c.Interceptors(),
	}
}

// Get returns a Pedidos entity by its id.
func (c *PedidosClient) Get(ctx context.Context, id int) (*Pedidos, error) {
	return c.Query().Where(pedidos.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PedidosClient) GetX(ctx context.Context, id int) *Pedidos {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCliente queries the cliente edge of a Pedidos.
func (c *PedidosClient) QueryCliente(_m *Pedidos) *ClientesQuery {
	query := (&ClientesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pedidos.Table, pedidos.FieldID, id),
			sqlgraph.To(clientes.Table, clientes.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pedidos.ClienteTable, pedidos.ClienteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDetalles queries the detalles edge of a Pedidos.
func (c *PedidosClient) QueryDetalles(_m *Pedidos) *DetallesPedidoQuery {
	query := (&DetallesPedidoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(pedidos.Table, pedidos.FieldID, id),
			sqlgraph.To(detallespedido.Table, detallespedido.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pedidos.DetallesTable, pedidos.DetallesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PedidosClient) Hooks() []Hook {
	return c.hooks.Pedidos
}

// Interceptors returns the client interceptors.
func (c *PedidosClient) Interceptors() []Interceptor {
	return c.inters.Pedidos
}

func (c *PedidosClient) mutate(ctx context.Context, m *PedidosMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PedidosCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PedidosUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PedidosUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PedidosDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pedidos mutation op: %q", m.Op())
	}
}

// ProductosMenuClient is a client for the ProductosMenu schema.
type ProductosMenuClient struct {
	config
}

// NewProductosMenuClient returns a client for the ProductosMenu from the given config.
func NewProductosMenuClient(c config) *ProductosMenuClient {
	return &ProductosMenuClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `productosmenu.Hooks(f(g(h())))`.
func (c *ProductosMenuClient) Use(hooks ...Hook) {
	c.hooks.ProductosMenu = append(c.hooks.ProductosMenu, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `productosmenu.Intercept(f(g(h())))`.
func (c *ProductosMenuClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProductosMenu = append(c.inters.ProductosMenu, interceptors...)
}

// Create returns a builder for creating a ProductosMenu entity.
func (c *ProductosMenuClient) Create() *ProductosMenuCreate {
	mutation := newProductosMenuMutation(c.config, OpCreate)
	return &ProductosMenuCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProductosMenu entities.
func (c *ProductosMenuClient) CreateBulk(builders ...*ProductosMenuCreate) *ProductosMenuCreateBulk {
	return &ProductosMenuCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProductosMenuClient) MapCreateBulk(slice any, setFunc func(*ProductosMenuCreate, int)) *ProductosMenuCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProductosMenuCreateBulk{err: fmt.Errorf("calling to ProductosMenuClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProductosMenuCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProductosMenuCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProductosMenu.
func (c *ProductosMenuClient) Update() *ProductosMenuUpdate {
	mutation := newProductosMenuMutation(c.config, OpUpdate)
	return &ProductosMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProductosMenuClient) UpdateOne(_m *ProductosMenu) *ProductosMenuUpdateOne {
	mutation := newProductosMenuMutation(c.config, OpUpdateOne, withProductosMenu(_m))
	return &ProductosMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProductosMenuClient) UpdateOneID(id int) *ProductosMenuUpdateOne {
	mutation := newProductosMenuMutation(c.config, OpUpdateOne, withProductosMenuID(id))
	return &ProductosMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProductosMenu.
func (c *ProductosMenuClient) Delete() *ProductosMenuDelete {
	mutation := newProductosMenuMutation(c.config, OpDelete)
	return &ProductosMenuDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProductosMenuClient) DeleteOne(_m *ProductosMenu) *ProductosMenuDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProductosMenuClient) DeleteOneID(id int) *ProductosMenuDeleteOne {
	builder := c.Delete().Where(productosmenu.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProductosMenuDeleteOne{builder}
}

// Query returns a query builder for ProductosMenu.
func (c *ProductosMenuClient) Query() *ProductosMenuQuery {
	return &ProductosMenuQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProductosMenu},
		inters: c.Interceptors(),
	}
}

// Get returns a ProductosMenu entity by its id.
func (c *ProductosMenuClient) Get(ctx context.Context, id int) (*ProductosMenu, error) {
	return c.Query().Where(productosmenu.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProductosMenuClient) GetX(ctx context.Context, id int) *ProductosMenu {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRecetas queries the recetas edge of a ProductosMenu.
func (c *ProductosMenuClient) QueryRecetas(_m *ProductosMenu) *RecetasQuery {
	query := (&RecetasClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(productosmenu.Table, productosmenu.FieldID, id),
			sqlgraph.To(recetas.Table, recetas.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productosmenu.RecetasTable, productosmenu.RecetasColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDetallesPedido queries the detalles_pedido edge of a ProductosMenu.
func (c *ProductosMenuClient) QueryDetallesPedido(_m *ProductosMenu) *DetallesPedidoQuery {
	query := (&DetallesPedidoClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(productosmenu.Table, productosmenu.FieldID, id),
			sqlgraph.To(detallespedido.Table, detallespedido.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productosmenu.DetallesPedidoTable, productosmenu.DetallesPedidoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProductosMenuClient) Hooks() []Hook {
	return c.hooks.ProductosMenu
}

// Interceptors returns the client interceptors.
func (c *ProductosMenuClient) Interceptors() []Interceptor {
	return c.inters.ProductosMenu
}

func (c *ProductosMenuClient) mutate(ctx context.Context, m *ProductosMenuMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProductosMenuCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProductosMenuUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProductosMenuUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProductosMenuDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProductosMenu mutation op: %q", m.Op())
	}
}

// RecetasClient is a client for the Recetas schema.
type RecetasClient struct {
	config
}

// NewRecetasClient returns a client for the Recetas from the given config.
func NewRecetasClient(c config) *RecetasClient {
	return &RecetasClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `recetas.Hooks(f(g(h())))`.
func (c *RecetasClient) Use(hooks ...Hook) {
	c.hooks.Recetas = append(c.hooks.Recetas, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `recetas.Intercept(f(g(h())))`.
func (c *RecetasClient) Intercept(interceptors ...Interceptor) {
	c.inters.Recetas = append(c.inters.Recetas, interceptors...)
}

// Create returns a builder for creating a Recetas entity.
func (c *RecetasClient) Create() *RecetasCreate {
	mutation := newRecetasMutation(c.config, OpCreate)
	return &RecetasCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Recetas entities.
func (c *RecetasClient) CreateBulk(builders ...*RecetasCreate) *RecetasCreateBulk {
	return &RecetasCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RecetasClient) MapCreateBulk(slice any, setFunc func(*RecetasCreate, int)) *RecetasCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RecetasCreateBulk{err: fmt.Errorf("calling to RecetasClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RecetasCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RecetasCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Recetas.
func (c *RecetasClient) Update() *RecetasUpdate {
	mutation := newRecetasMutation(c.config, OpUpdate)
	return &RecetasUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecetasClient) UpdateOne(_m *Recetas) *RecetasUpdateOne {
	mutation := newRecetasMutation(c.config, OpUpdateOne, withRecetas(_m))
	return &RecetasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecetasClient) UpdateOneID(id int) *RecetasUpdateOne {
	mutation := newRecetasMutation(c.config, OpUpdateOne, withRecetasID(id))
	return &RecetasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Recetas.
func (c *RecetasClient) Delete() *RecetasDelete {
	mutation := newRecetasMutation(c.config, OpDelete)
	return &RecetasDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RecetasClient) DeleteOne(_m *Recetas) *RecetasDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RecetasClient) DeleteOneID(id int) *RecetasDeleteOne {
	builder := c.Delete().Where(recetas.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecetasDeleteOne{builder}
}

// Query returns a query builder for Recetas.
func (c *RecetasClient) Query() *RecetasQuery {
	return &RecetasQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRecetas},
		inters: c.Interceptors(),
	}
}

// Get returns a Recetas entity by its id.
func (c *RecetasClient) Get(ctx context.Context, id int) (*Recetas, error) {
	return c.Query().Where(recetas.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecetasClient) GetX(ctx context.Context, id int) *Recetas {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProducto queries the producto edge of a Recetas.
func (c *RecetasClient) QueryProducto(_m *Recetas) *ProductosMenuQuery {
	query := (&ProductosMenuClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recetas.Table, recetas.FieldID, id),
			sqlgraph.To(productosmenu.Table, productosmenu.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recetas.ProductoTable, recetas.ProductoColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMateriaPrima queries the materia_prima edge of a Recetas.
func (c *RecetasClient) QueryMateriaPrima(_m *Recetas) *MateriaPrimaQuery {
	query := (&MateriaPrimaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(recetas.Table, recetas.FieldID, id),
			sqlgraph.To(materiaprima.Table, materiaprima.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recetas.MateriaPrimaTable, recetas.MateriaPrimaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecetasClient) Hooks() []Hook {
	return c.hooks.Recetas
}

// Interceptors returns the client interceptors.
func (c *RecetasClient) Interceptors() []Interceptor {
	return c.inters.Recetas
}

func (c *RecetasClient) mutate(ctx context.Context, m *RecetasMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RecetasCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RecetasUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RecetasUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RecetasDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Recetas mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Clientes, DetallesPedido, MateriaPrima, Pedidos, ProductosMenu,
		Recetas []ent.Hook
	}
	inters struct {
		Clientes, DetallesPedido, MateriaPrima, Pedidos, ProductosMenu,
		Recetas []ent.Interceptor
	}
)
