// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Clientes is the model entity for the Clientes schema.
type Clientes struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NombreCompleto holds the value of the "nombre_completo" field.
	NombreCompleto string `json:"nombre_completo,omitempty"`
	// Telefono holds the value of the "telefono" field.
	Telefono *string `json:"telefono,omitempty"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// Direccion holds the value of the "direccion" field.
	Direccion *string `json:"direccion,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClientesQuery when eager-loading is set.
	Edges        ClientesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClientesEdges holds the relations/edges for other nodes in the graph.
type ClientesEdges struct {
	// Pedidos holds the value of the pedidos edge.
	Pedidos []*Pedidos `json:"pedidos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PedidosOrErr returns the Pedidos value or an error if the edge
// was not loaded in eager-loading.
func (e ClientesEdges) PedidosOrErr() ([]*Pedidos, error) {
	if e.loadedTypes[0] {
		return e.Pedidos, nil
	}
	return nil, &NotLoadedError{edge: "pedidos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Clientes) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientes.FieldID:
			values[i] = new(sql.NullInt64)
		case clientes.FieldNombreCompleto, clientes.FieldTelefono, clientes.FieldEmail, clientes.FieldDireccion:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Clientes fields.
func (_m *Clientes) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientes.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case clientes.FieldNombreCompleto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nombre_completo", values[i])
			} else if value.Valid {
				_m.NombreCompleto = value.String
			}
		case clientes.FieldTelefono:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field telefono", values[i])
			} else if value.Valid {
				_m.Telefono = new(string)
				*_m.Telefono = value.String
			}
		case clientes.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case clientes.FieldDireccion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direccion", values[i])
			} else if value.Valid {
				_m.Direccion = new(string)
				*_m.Direccion = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Clientes.
// This includes values selected through modifiers, order, etc.
func (_m *Clientes) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPedidos queries the "pedidos" edge of the Clientes entity.
func (_m *Clientes) QueryPedidos() *PedidosQuery {
	return NewClientesClient(_m.config).QueryPedidos(_m)
}

// Update returns a builder for updating this Clientes.
// Note that you need to call Clientes.Unwrap() before calling this method if this Clientes
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Clientes) Update() *ClientesUpdateOne {
	return NewClientesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Clientes entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Clientes) Unwrap() *Clientes {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Clientes is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Clientes) String() string {
	var builder strings.Builder
	builder.WriteString("Clientes(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("nombre_completo=")
	builder.WriteString(_m.NombreCompleto)
	builder.WriteString(", ")
	if v := _m.Telefono; v != nil {
		builder.WriteString("telefono=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Direccion; v != nil {
		builder.WriteString("direccion=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ClientesSlice is a parsable slice of Clientes.
type ClientesSlice []*Clientes
