// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/productosmenu"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DetallesPedidoCreate is the builder for creating a DetallesPedido entity.
type DetallesPedidoCreate struct {
	config
	mutation *DetallesPedidoMutation
	hooks    []Hook
}

// SetPedidoID sets the "pedido_id" field.
func (_c *DetallesPedidoCreate) SetPedidoID(v int) *DetallesPedidoCreate {
	_c.mutation.SetPedidoID(v)
	return _c
}

// SetProductoID sets the "producto_id" field.
func (_c *DetallesPedidoCreate) SetProductoID(v int) *DetallesPedidoCreate {
	_c.mutation.SetProductoID(v)
	return _c
}

// SetCantidad sets the "cantidad" field.
func (_c *DetallesPedidoCreate) SetCantidad(v int) *DetallesPedidoCreate {
	_c.mutation.SetCantidad(v)
	return _c
}

// SetPrecioUnitario sets the "precio_unitario" field.
func (_c *DetallesPedidoCreate) SetPrecioUnitario(v float64) *DetallesPedidoCreate {
	_c.mutation.SetPrecioUnitario(v)
	return _c
}

// SetSubtotal sets the "subtotal" field.
func (_c *DetallesPedidoCreate) SetSubtotal(v float64) *DetallesPedidoCreate {
	_c.mutation.SetSubtotal(v)
	return _c
}

// SetPedido sets the "pedido" edge to the Pedidos entity.
func (_c *DetallesPedidoCreate) SetPedido(v *Pedidos) *DetallesPedidoCreate {
	return _c.SetPedidoID(v.ID)
}

// SetProducto sets the "producto" edge to the ProductosMenu entity.
func (_c *DetallesPedidoCreate) SetProducto(v *ProductosMenu) *DetallesPedidoCreate {
	return _c.SetProductoID(v.ID)
}

// Mutation returns the DetallesPedidoMutation object of the builder.
func (_c *DetallesPedidoCreate) Mutation() *DetallesPedidoMutation {
	return _c.mutation
}

// Save creates the DetallesPedido in the database.
func (_c *DetallesPedidoCreate) Save(ctx context.Context) (*DetallesPedido, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DetallesPedidoCreate) SaveX(ctx context.Context) *DetallesPedido {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DetallesPedidoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DetallesPedidoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DetallesPedidoCreate) check() error {
	if _, ok := _c.mutation.PedidoID(); !ok {
		return &ValidationError{Name: "pedido_id", err: errors.New(`ent: missing required field "DetallesPedido.pedido_id"`)}
	}
	if _, ok := _c.mutation.ProductoID(); !ok {
		return &ValidationError{Name: "producto_id", err: errors.New(`ent: missing required field "DetallesPedido.producto_id"`)}
	}
	if _, ok := _c.mutation.Cantidad(); !ok {
		return &ValidationError{Name: "cantidad", err: errors.New(`ent: missing required field "DetallesPedido.cantidad"`)}
	}
	if _, ok := _c.mutation.PrecioUnitario(); !ok {
		return &ValidationError{Name: "precio_unitario", err: errors.New(`ent: missing required field "DetallesPedido.precio_unitario"`)}
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		return &ValidationError{Name: "subtotal", err: errors.New(`ent: missing required field "DetallesPedido.subtotal"`)}
	}
	if len(_c.mutation.PedidoIDs()) == 0 {
		return &ValidationError{Name: "pedido", err: errors.New(`ent: missing required edge "DetallesPedido.pedido"`)}
	}
	if len(_c.mutation.ProductoIDs()) == 0 {
		return &ValidationError{Name: "producto", err: errors.New(`ent: missing required edge "DetallesPedido.producto"`)}
	}
	return nil
}

func (_c *DetallesPedidoCreate) sqlSave(ctx context.Context) (*DetallesPedido, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DetallesPedidoCreate) createSpec() (*DetallesPedido, *sqlgraph.CreateSpec) {
	var (
		_node = &DetallesPedido{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(detallespedido.Table, sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Cantidad(); ok {
		_spec.SetField(detallespedido.FieldCantidad, field.TypeInt, value)
		_node.Cantidad = value
	}
	if value, ok := _c.mutation.PrecioUnitario(); ok {
		_spec.SetField(detallespedido.FieldPrecioUnitario, field.TypeFloat64, value)
		_node.PrecioUnitario = value
	}
	if value, ok := _c.mutation.Subtotal(); ok {
		_spec.SetField(detallespedido.FieldSubtotal, field.TypeFloat64, value)
		_node.Subtotal = value
	}
	if nodes := _c.mutation.PedidoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.PedidoTable,
			Columns: []string{detallespedido.PedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PedidoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.ProductoTable,
			Columns: []string{detallespedido.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DetallesPedidoCreateBulk is the builder for creating many DetallesPedido entities in bulk.
type DetallesPedidoCreateBulk struct {
	config
	err      error
	builders []*DetallesPedidoCreate
}

// Save creates the DetallesPedido entities in the database.
func (_c *DetallesPedidoCreateBulk) Save(ctx context.Context) ([]*DetallesPedido, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DetallesPedido, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DetallesPedidoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DetallesPedidoCreateBulk) SaveX(ctx context.Context) []*DetallesPedido {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DetallesPedidoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DetallesPedidoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
