// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/productosmenu"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DetallesPedido is the model entity for the DetallesPedido schema.
type DetallesPedido struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PedidoID holds the value of the "pedido_id" field.
	PedidoID int `json:"pedido_id,omitempty"`
	// ProductoID holds the value of the "producto_id" field.
	ProductoID int `json:"producto_id,omitempty"`
	// Cantidad holds the value of the "cantidad" field.
	Cantidad int `json:"cantidad,omitempty"`
	// PrecioUnitario holds the value of the "precio_unitario" field.
	PrecioUnitario float64 `json:"precio_unitario,omitempty"`
	// Subtotal holds the value of the "subtotal" field.
	Subtotal float64 `json:"subtotal,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DetallesPedidoQuery when eager-loading is set.
	Edges        DetallesPedidoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DetallesPedidoEdges holds the relations/edges for other nodes in the graph.
type DetallesPedidoEdges struct {
	// Pedido holds the value of the pedido edge.
	Pedido *Pedidos `json:"pedido,omitempty"`
	// Producto holds the value of the producto edge.
	Producto *ProductosMenu `json:"producto,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PedidoOrErr returns the Pedido value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DetallesPedidoEdges) PedidoOrErr() (*Pedidos, error) {
	if e.Pedido != nil {
		return e.Pedido, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: pedidos.Label}
	}
	return nil, &NotLoadedError{edge: "pedido"}
}

// ProductoOrErr returns the Producto value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DetallesPedidoEdges) ProductoOrErr() (*ProductosMenu, error) {
	if e.Producto != nil {
		return e.Producto, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: productosmenu.Label}
	}
	return nil, &NotLoadedError{edge: "producto"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DetallesPedido) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case detallespedido.FieldPrecioUnitario, detallespedido.FieldSubtotal:
			values[i] = new(sql.NullFloat64)
		case detallespedido.FieldID, detallespedido.FieldPedidoID, detallespedido.FieldProductoID, detallespedido.FieldCantidad:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DetallesPedido fields.
func (_m *DetallesPedido) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case detallespedido.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case detallespedido.FieldPedidoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pedido_id", values[i])
			} else if value.Valid {
				_m.PedidoID = int(value.Int64)
			}
		case detallespedido.FieldProductoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field producto_id", values[i])
			} else if value.Valid {
				_m.ProductoID = int(value.Int64)
			}
		case detallespedido.FieldCantidad:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cantidad", values[i])
			} else if value.Valid {
				_m.Cantidad = int(value.Int64)
			}
		case detallespedido.FieldPrecioUnitario:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field precio_unitario", values[i])
			} else if value.Valid {
				_m.PrecioUnitario = value.Float64
			}
		case detallespedido.FieldSubtotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field subtotal", values[i])
			} else if value.Valid {
				_m.Subtotal = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DetallesPedido.
// This includes values selected through modifiers, order, etc.
func (_m *DetallesPedido) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPedido queries the "pedido" edge of the DetallesPedido entity.
func (_m *DetallesPedido) QueryPedido() *PedidosQuery {
	return NewDetallesPedidoClient(_m.config).QueryPedido(_m)
}

// QueryProducto queries the "producto" edge of the DetallesPedido entity.
func (_m *DetallesPedido) QueryProducto() *ProductosMenuQuery {
	return NewDetallesPedidoClient(_m.config).QueryProducto(_m)
}

// Update returns a builder for updating this DetallesPedido.
// Note that you need to call DetallesPedido.Unwrap() before calling this method if this DetallesPedido
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DetallesPedido) Update() *DetallesPedidoUpdateOne {
	return NewDetallesPedidoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DetallesPedido entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DetallesPedido) Unwrap() *DetallesPedido {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DetallesPedido is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DetallesPedido) String() string {
	var builder strings.Builder
	builder.WriteString("DetallesPedido(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pedido_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PedidoID))
	builder.WriteString(", ")
	builder.WriteString("producto_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductoID))
	builder.WriteString(", ")
	builder.WriteString("cantidad=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cantidad))
	builder.WriteString(", ")
	builder.WriteString("precio_unitario=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrecioUnitario))
	builder.WriteString(", ")
	builder.WriteString("subtotal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Subtotal))
	builder.WriteByte(')')
	return builder.String()
}

// DetallesPedidos is a parsable slice of DetallesPedido.
type DetallesPedidos []*DetallesPedido
