// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/productosmenu"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DetallesPedidoUpdate is the builder for updating DetallesPedido entities.
type DetallesPedidoUpdate struct {
	config
	hooks    []Hook
	mutation *DetallesPedidoMutation
}

// Where appends a list predicates to the DetallesPedidoUpdate builder.
func (_u *DetallesPedidoUpdate) Where(ps ...predicate.DetallesPedido) *DetallesPedidoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPedidoID sets the "pedido_id" field.
func (_u *DetallesPedidoUpdate) SetPedidoID(v int) *DetallesPedidoUpdate {
	_u.mutation.SetPedidoID(v)
	return _u
}

// SetNillablePedidoID sets the "pedido_id" field if the given value is not nil.
func (_u *DetallesPedidoUpdate) SetNillablePedidoID(v *int) *DetallesPedidoUpdate {
	if v != nil {
		_u.SetPedidoID(*v)
	}
	return _u
}

// SetProductoID sets the "producto_id" field.
func (_u *DetallesPedidoUpdate) SetProductoID(v int) *DetallesPedidoUpdate {
	_u.mutation.SetProductoID(v)
	return _u
}

// SetNillableProductoID sets the "producto_id" field if the given value is not nil.
func (_u *DetallesPedidoUpdate) SetNillableProductoID(v *int) *DetallesPedidoUpdate {
	if v != nil {
		_u.SetProductoID(*v)
	}
	return _u
}

// SetCantidad sets the "cantidad" field.
func (_u *DetallesPedidoUpdate) SetCantidad(v int) *DetallesPedidoUpdate {
	_u.mutation.ResetCantidad()
	_u.mutation.SetCantidad(v)
	return _u
}

// SetNillableCantidad sets the "cantidad" field if the given value is not nil.
func (_u *DetallesPedidoUpdate) SetNillableCantidad(v *int) *DetallesPedidoUpdate {
	if v != nil {
		_u.SetCantidad(*v)
	}
	return _u
}

// AddCantidad adds value to the "cantidad" field.
func (_u *DetallesPedidoUpdate) AddCantidad(v int) *DetallesPedidoUpdate {
	_u.mutation.AddCantidad(v)
	return _u
}

// SetPrecioUnitario sets the "precio_unitario" field.
func (_u *DetallesPedidoUpdate) SetPrecioUnitario(v float64) *DetallesPedidoUpdate {
	_u.mutation.ResetPrecioUnitario()
	_u.mutation.SetPrecioUnitario(v)
	return _u
}

// SetNillablePrecioUnitario sets the "precio_unitario" field if the given value is not nil.
func (_u *DetallesPedidoUpdate) SetNillablePrecioUnitario(v *float64) *DetallesPedidoUpdate {
	if v != nil {
		_u.SetPrecioUnitario(*v)
	}
	return _u
}

// AddPrecioUnitario adds value to the "precio_unitario" field.
func (_u *DetallesPedidoUpdate) AddPrecioUnitario(v float64) *DetallesPedidoUpdate {
	_u.mutation.AddPrecioUnitario(v)
	return _u
}

// SetSubtotal sets the "subtotal" field.
func (_u *DetallesPedidoUpdate) SetSubtotal(v float64) *DetallesPedidoUpdate {
	_u.mutation.ResetSubtotal()
	_u.mutation.SetSubtotal(v)
	return _u
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_u *DetallesPedidoUpdate) SetNillableSubtotal(v *float64) *DetallesPedidoUpdate {
	if v != nil {
		_u.SetSubtotal(*v)
	}
	return _u
}

// AddSubtotal adds value to the "subtotal" field.
func (_u *DetallesPedidoUpdate) AddSubtotal(v float64) *DetallesPedidoUpdate {
	_u.mutation.AddSubtotal(v)
	return _u
}

// SetPedido sets the "pedido" edge to the Pedidos entity.
func (_u *DetallesPedidoUpdate) SetPedido(v *Pedidos) *DetallesPedidoUpdate {
	return _u.SetPedidoID(v.ID)
}

// SetProducto sets the "producto" edge to the ProductosMenu entity.
func (_u *DetallesPedidoUpdate) SetProducto(v *ProductosMenu) *DetallesPedidoUpdate {
	return _u.SetProductoID(v.ID)
}

// Mutation returns the DetallesPedidoMutation object of the builder.
func (_u *DetallesPedidoUpdate) Mutation() *DetallesPedidoMutation {
	return _u.mutation
}

// ClearPedido clears the "pedido" edge to the Pedidos entity.
func (_u *DetallesPedidoUpdate) ClearPedido() *DetallesPedidoUpdate {
	_u.mutation.ClearPedido()
	return _u
}

// ClearProducto clears the "producto" edge to the ProductosMenu entity.
func (_u *DetallesPedidoUpdate) ClearProducto() *DetallesPedidoUpdate {
	_u.mutation.ClearProducto()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DetallesPedidoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DetallesPedidoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DetallesPedidoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DetallesPedidoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DetallesPedidoUpdate) check() error {
	if _u.mutation.PedidoCleared() && len(_u.mutation.PedidoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DetallesPedido.pedido"`)
	}
	if _u.mutation.ProductoCleared() && len(_u.mutation.ProductoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DetallesPedido.producto"`)
	}
	return nil
}

func (_u *DetallesPedidoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(detallespedido.Table, detallespedido.Columns, sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cantidad(); ok {
		_spec.SetField(detallespedido.FieldCantidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCantidad(); ok {
		_spec.AddField(detallespedido.FieldCantidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrecioUnitario(); ok {
		_spec.SetField(detallespedido.FieldPrecioUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrecioUnitario(); ok {
		_spec.AddField(detallespedido.FieldPrecioUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Subtotal(); ok {
		_spec.SetField(detallespedido.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubtotal(); ok {
		_spec.AddField(detallespedido.FieldSubtotal, field.TypeFloat64, value)
	}
	if _u.mutation.PedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.PedidoTable,
			Columns: []string{detallespedido.PedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PedidoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.PedidoTable,
			Columns: []string{detallespedido.PedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.ProductoTable,
			Columns: []string{detallespedido.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.ProductoTable,
			Columns: []string{detallespedido.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{detallespedido.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DetallesPedidoUpdateOne is the builder for updating a single DetallesPedido entity.
type DetallesPedidoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DetallesPedidoMutation
}

// SetPedidoID sets the "pedido_id" field.
func (_u *DetallesPedidoUpdateOne) SetPedidoID(v int) *DetallesPedidoUpdateOne {
	_u.mutation.SetPedidoID(v)
	return _u
}

// SetNillablePedidoID sets the "pedido_id" field if the given value is not nil.
func (_u *DetallesPedidoUpdateOne) SetNillablePedidoID(v *int) *DetallesPedidoUpdateOne {
	if v != nil {
		_u.SetPedidoID(*v)
	}
	return _u
}

// SetProductoID sets the "producto_id" field.
func (_u *DetallesPedidoUpdateOne) SetProductoID(v int) *DetallesPedidoUpdateOne {
	_u.mutation.SetProductoID(v)
	return _u
}

// SetNillableProductoID sets the "producto_id" field if the given value is not nil.
func (_u *DetallesPedidoUpdateOne) SetNillableProductoID(v *int) *DetallesPedidoUpdateOne {
	if v != nil {
		_u.SetProductoID(*v)
	}
	return _u
}

// SetCantidad sets the "cantidad" field.
func (_u *DetallesPedidoUpdateOne) SetCantidad(v int) *DetallesPedidoUpdateOne {
	_u.mutation.ResetCantidad()
	_u.mutation.SetCantidad(v)
	return _u
}

// SetNillableCantidad sets the "cantidad" field if the given value is not nil.
func (_u *DetallesPedidoUpdateOne) SetNillableCantidad(v *int) *DetallesPedidoUpdateOne {
	if v != nil {
		_u.SetCantidad(*v)
	}
	return _u
}

// AddCantidad adds value to the "cantidad" field.
func (_u *DetallesPedidoUpdateOne) AddCantidad(v int) *DetallesPedidoUpdateOne {
	_u.mutation.AddCantidad(v)
	return _u
}

// SetPrecioUnitario sets the "precio_unitario" field.
func (_u *DetallesPedidoUpdateOne) SetPrecioUnitario(v float64) *DetallesPedidoUpdateOne {
	_u.mutation.ResetPrecioUnitario()
	_u.mutation.SetPrecioUnitario(v)
	return _u
}

// SetNillablePrecioUnitario sets the "precio_unitario" field if the given value is not nil.
func (_u *DetallesPedidoUpdateOne) SetNillablePrecioUnitario(v *float64) *DetallesPedidoUpdateOne {
	if v != nil {
		_u.SetPrecioUnitario(*v)
	}
	return _u
}

// AddPrecioUnitario adds value to the "precio_unitario" field.
func (_u *DetallesPedidoUpdateOne) AddPrecioUnitario(v float64) *DetallesPedidoUpdateOne {
	_u.mutation.AddPrecioUnitario(v)
	return _u
}

// SetSubtotal sets the "subtotal" field.
func (_u *DetallesPedidoUpdateOne) SetSubtotal(v float64) *DetallesPedidoUpdateOne {
	_u.mutation.ResetSubtotal()
	_u.mutation.SetSubtotal(v)
	return _u
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_u *DetallesPedidoUpdateOne) SetNillableSubtotal(v *float64) *DetallesPedidoUpdateOne {
	if v != nil {
		_u.SetSubtotal(*v)
	}
	return _u
}

// AddSubtotal adds value to the "subtotal" field.
func (_u *DetallesPedidoUpdateOne) AddSubtotal(v float64) *DetallesPedidoUpdateOne {
	_u.mutation.AddSubtotal(v)
	return _u
}

// SetPedido sets the "pedido" edge to the Pedidos entity.
func (_u *DetallesPedidoUpdateOne) SetPedido(v *Pedidos) *DetallesPedidoUpdateOne {
	return _u.SetPedidoID(v.ID)
}

// SetProducto sets the "producto" edge to the ProductosMenu entity.
func (_u *DetallesPedidoUpdateOne) SetProducto(v *ProductosMenu) *DetallesPedidoUpdateOne {
	return _u.SetProductoID(v.ID)
}

// Mutation returns the DetallesPedidoMutation object of the builder.
func (_u *DetallesPedidoUpdateOne) Mutation() *DetallesPedidoMutation {
	return _u.mutation
}

// ClearPedido clears the "pedido" edge to the Pedidos entity.
func (_u *DetallesPedidoUpdateOne) ClearPedido() *DetallesPedidoUpdateOne {
	_u.mutation.ClearPedido()
	return _u
}

// ClearProducto clears the "producto" edge to the ProductosMenu entity.
func (_u *DetallesPedidoUpdateOne) ClearProducto() *DetallesPedidoUpdateOne {
	_u.mutation.ClearProducto()
	return _u
}

// Where appends a list predicates to the DetallesPedidoUpdate builder.
func (_u *DetallesPedidoUpdateOne) Where(ps ...predicate.DetallesPedido) *DetallesPedidoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DetallesPedidoUpdateOne) Select(field string, fields ...string) *DetallesPedidoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DetallesPedido entity.
func (_u *DetallesPedidoUpdateOne) Save(ctx context.Context) (*DetallesPedido, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DetallesPedidoUpdateOne) SaveX(ctx context.Context) *DetallesPedido {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DetallesPedidoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DetallesPedidoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DetallesPedidoUpdateOne) check() error {
	if _u.mutation.PedidoCleared() && len(_u.mutation.PedidoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DetallesPedido.pedido"`)
	}
	if _u.mutation.ProductoCleared() && len(_u.mutation.ProductoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DetallesPedido.producto"`)
	}
	return nil
}

func (_u *DetallesPedidoUpdateOne) sqlSave(ctx context.Context) (_node *DetallesPedido, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(detallespedido.Table, detallespedido.Columns, sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DetallesPedido.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, detallespedido.FieldID)
		for _, f := range fields {
			if !detallespedido.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != detallespedido.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cantidad(); ok {
		_spec.SetField(detallespedido.FieldCantidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCantidad(); ok {
		_spec.AddField(detallespedido.FieldCantidad, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrecioUnitario(); ok {
		_spec.SetField(detallespedido.FieldPrecioUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrecioUnitario(); ok {
		_spec.AddField(detallespedido.FieldPrecioUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Subtotal(); ok {
		_spec.SetField(detallespedido.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubtotal(); ok {
		_spec.AddField(detallespedido.FieldSubtotal, field.TypeFloat64, value)
	}
	if _u.mutation.PedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.PedidoTable,
			Columns: []string{detallespedido.PedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PedidoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.PedidoTable,
			Columns: []string{detallespedido.PedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.ProductoTable,
			Columns: []string{detallespedido.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   detallespedido.ProductoTable,
			Columns: []string{detallespedido.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DetallesPedido{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{detallespedido.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
