// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DetallesPedidoDelete is the builder for deleting a DetallesPedido entity.
type DetallesPedidoDelete struct {
	config
	hooks    []Hook
	mutation *DetallesPedidoMutation
}

// Where appends a list predicates to the DetallesPedidoDelete builder.
func (_d *DetallesPedidoDelete) Where(ps ...predicate.DetallesPedido) *DetallesPedidoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DetallesPedidoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DetallesPedidoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DetallesPedidoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(detallespedido.Table, sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DetallesPedidoDeleteOne is the builder for deleting a single DetallesPedido entity.
type DetallesPedidoDeleteOne struct {
	_d *DetallesPedidoDelete
}

// Where appends a list predicates to the DetallesPedidoDelete builder.
func (_d *DetallesPedidoDeleteOne) Where(ps ...predicate.DetallesPedido) *DetallesPedidoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DetallesPedidoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{detallespedido.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DetallesPedidoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
