// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/recetas"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MateriaPrimaCreate is the builder for creating a MateriaPrima entity.
type MateriaPrimaCreate struct {
	config
	mutation *MateriaPrimaMutation
	hooks    []Hook
}

// SetNombreInsumo sets the "nombre_insumo" field.
func (_c *MateriaPrimaCreate) SetNombreInsumo(v string) *MateriaPrimaCreate {
	_c.mutation.SetNombreInsumo(v)
	return _c
}

// SetCategoria sets the "categoria" field.
func (_c *MateriaPrimaCreate) SetCategoria(v string) *MateriaPrimaCreate {
	_c.mutation.SetCategoria(v)
	return _c
}

// SetProveedor sets the "proveedor" field.
func (_c *MateriaPrimaCreate) SetProveedor(v string) *MateriaPrimaCreate {
	_c.mutation.SetProveedor(v)
	return _c
}

// SetUnidadMedida sets the "unidad_medida" field.
func (_c *MateriaPrimaCreate) SetUnidadMedida(v string) *MateriaPrimaCreate {
	_c.mutation.SetUnidadMedida(v)
	return _c
}

// SetCostoUnitario sets the "costo_unitario" field.
func (_c *MateriaPrimaCreate) SetCostoUnitario(v float64) *MateriaPrimaCreate {
	_c.mutation.SetCostoUnitario(v)
	return _c
}

// SetStockActual sets the "stock_actual" field.
func (_c *MateriaPrimaCreate) SetStockActual(v float64) *MateriaPrimaCreate {
	_c.mutation.SetStockActual(v)
	return _c
}

// SetPuntoReorden sets the "punto_reorden" field.
func (_c *MateriaPrimaCreate) SetPuntoReorden(v float64) *MateriaPrimaCreate {
	_c.mutation.SetPuntoReorden(v)
	return _c
}

// AddRecetaIDs adds the "recetas" edge to the Recetas entity by IDs.
func (_c *MateriaPrimaCreate) AddRecetaIDs(ids ...int) *MateriaPrimaCreate {
	_c.mutation.AddRecetaIDs(ids...)
	return _c
}

// AddRecetas adds the "recetas" edges to the Recetas entity.
func (_c *MateriaPrimaCreate) AddRecetas(v ...*Recetas) *MateriaPrimaCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecetaIDs(ids...)
}

// Mutation returns the MateriaPrimaMutation object of the builder.
func (_c *MateriaPrimaCreate) Mutation() *MateriaPrimaMutation {
	return _c.mutation
}

// Save creates the MateriaPrima in the database.
func (_c *MateriaPrimaCreate) Save(ctx context.Context) (*MateriaPrima, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MateriaPrimaCreate) SaveX(ctx context.Context) *MateriaPrima {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MateriaPrimaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MateriaPrimaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MateriaPrimaCreate) check() error {
	if _, ok := _c.mutation.NombreInsumo(); !ok {
		return &ValidationError{Name: "nombre_insumo", err: errors.New(`ent: missing required field "MateriaPrima.nombre_insumo"`)}
	}
	if v, ok := _c.mutation.NombreInsumo(); ok {
		if err := materiaprima.NombreInsumoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_insumo", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.nombre_insumo": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Categoria(); !ok {
		return &ValidationError{Name: "categoria", err: errors.New(`ent: missing required field "MateriaPrima.categoria"`)}
	}
	if v, ok := _c.mutation.Categoria(); ok {
		if err := materiaprima.CategoriaValidator(v); err != nil {
			return &ValidationError{Name: "categoria", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.categoria": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Proveedor(); !ok {
		return &ValidationError{Name: "proveedor", err: errors.New(`ent: missing required field "MateriaPrima.proveedor"`)}
	}
	if v, ok := _c.mutation.Proveedor(); ok {
		if err := materiaprima.ProveedorValidator(v); err != nil {
			return &ValidationError{Name: "proveedor", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.proveedor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UnidadMedida(); !ok {
		return &ValidationError{Name: "unidad_medida", err: errors.New(`ent: missing required field "MateriaPrima.unidad_medida"`)}
	}
	if v, ok := _c.mutation.UnidadMedida(); ok {
		if err := materiaprima.UnidadMedidaValidator(v); err != nil {
			return &ValidationError{Name: "unidad_medida", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.unidad_medida": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CostoUnitario(); !ok {
		return &ValidationError{Name: "costo_unitario", err: errors.New(`ent: missing required field "MateriaPrima.costo_unitario"`)}
	}
	if _, ok := _c.mutation.StockActual(); !ok {
		return &ValidationError{Name: "stock_actual", err: errors.New(`ent: missing required field "MateriaPrima.stock_actual"`)}
	}
	if _, ok := _c.mutation.PuntoReorden(); !ok {
		return &ValidationError{Name: "punto_reorden", err: errors.New(`ent: missing required field "MateriaPrima.punto_reorden"`)}
	}
	return nil
}

func (_c *MateriaPrimaCreate) sqlSave(ctx context.Context) (*MateriaPrima, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MateriaPrimaCreate) createSpec() (*MateriaPrima, *sqlgraph.CreateSpec) {
	var (
		_node = &MateriaPrima{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(materiaprima.Table, sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NombreInsumo(); ok {
		_spec.SetField(materiaprima.FieldNombreInsumo, field.TypeString, value)
		_node.NombreInsumo = value
	}
	if value, ok := _c.mutation.Categoria(); ok {
		_spec.SetField(materiaprima.FieldCategoria, field.TypeString, value)
		_node.Categoria = value
	}
	if value, ok := _c.mutation.Proveedor(); ok {
		_spec.SetField(materiaprima.FieldProveedor, field.TypeString, value)
		_node.Proveedor = value
	}
	if value, ok := _c.mutation.UnidadMedida(); ok {
		_spec.SetField(materiaprima.FieldUnidadMedida, field.TypeString, value)
		_node.UnidadMedida = value
	}
	if value, ok := _c.mutation.CostoUnitario(); ok {
		_spec.SetField(materiaprima.FieldCostoUnitario, field.TypeFloat64, value)
		_node.CostoUnitario = value
	}
	if value, ok := _c.mutation.StockActual(); ok {
		_spec.SetField(materiaprima.FieldStockActual, field.TypeFloat64, value)
		_node.StockActual = value
	}
	if value, ok := _c.mutation.PuntoReorden(); ok {
		_spec.SetField(materiaprima.FieldPuntoReorden, field.TypeFloat64, value)
		_node.PuntoReorden = value
	}
	if nodes := _c.mutation.RecetasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MateriaPrimaCreateBulk is the builder for creating many MateriaPrima entities in bulk.
type MateriaPrimaCreateBulk struct {
	config
	err      error
	builders []*MateriaPrimaCreate
}

// Save creates the MateriaPrima entities in the database.
func (_c *MateriaPrimaCreateBulk) Save(ctx context.Context) ([]*MateriaPrima, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MateriaPrima, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MateriaPrimaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MateriaPrimaCreateBulk) SaveX(ctx context.Context) []*MateriaPrima {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MateriaPrimaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MateriaPrimaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
