// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MateriaPrimaDelete is the builder for deleting a MateriaPrima entity.
type MateriaPrimaDelete struct {
	config
	hooks    []Hook
	mutation *MateriaPrimaMutation
}

// Where appends a list predicates to the MateriaPrimaDelete builder.
func (_d *MateriaPrimaDelete) Where(ps ...predicate.MateriaPrima) *MateriaPrimaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MateriaPrimaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MateriaPrimaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MateriaPrimaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(materiaprima.Table, sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MateriaPrimaDeleteOne is the builder for deleting a single MateriaPrima entity.
type MateriaPrimaDeleteOne struct {
	_d *MateriaPrimaDelete
}

// Where appends a list predicates to the MateriaPrimaDelete builder.
func (_d *MateriaPrimaDeleteOne) Where(ps ...predicate.MateriaPrima) *MateriaPrimaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MateriaPrimaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{materiaprima.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MateriaPrimaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
