// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/recetas"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MateriaPrimaUpdate is the builder for updating MateriaPrima entities.
type MateriaPrimaUpdate struct {
	config
	hooks    []Hook
	mutation *MateriaPrimaMutation
}

// Where appends a list predicates to the MateriaPrimaUpdate builder.
func (_u *MateriaPrimaUpdate) Where(ps ...predicate.MateriaPrima) *MateriaPrimaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNombreInsumo sets the "nombre_insumo" field.
func (_u *MateriaPrimaUpdate) SetNombreInsumo(v string) *MateriaPrimaUpdate {
	_u.mutation.SetNombreInsumo(v)
	return _u
}

// SetNillableNombreInsumo sets the "nombre_insumo" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableNombreInsumo(v *string) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetNombreInsumo(*v)
	}
	return _u
}

// SetCategoria sets the "categoria" field.
func (_u *MateriaPrimaUpdate) SetCategoria(v string) *MateriaPrimaUpdate {
	_u.mutation.SetCategoria(v)
	return _u
}

// SetNillableCategoria sets the "categoria" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableCategoria(v *string) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetCategoria(*v)
	}
	return _u
}

// SetProveedor sets the "proveedor" field.
func (_u *MateriaPrimaUpdate) SetProveedor(v string) *MateriaPrimaUpdate {
	_u.mutation.SetProveedor(v)
	return _u
}

// SetNillableProveedor sets the "proveedor" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableProveedor(v *string) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetProveedor(*v)
	}
	return _u
}

// SetUnidadMedida sets the "unidad_medida" field.
func (_u *MateriaPrimaUpdate) SetUnidadMedida(v string) *MateriaPrimaUpdate {
	_u.mutation.SetUnidadMedida(v)
	return _u
}

// SetNillableUnidadMedida sets the "unidad_medida" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableUnidadMedida(v *string) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetUnidadMedida(*v)
	}
	return _u
}

// SetCostoUnitario sets the "costo_unitario" field.
func (_u *MateriaPrimaUpdate) SetCostoUnitario(v float64) *MateriaPrimaUpdate {
	_u.mutation.ResetCostoUnitario()
	_u.mutation.SetCostoUnitario(v)
	return _u
}

// SetNillableCostoUnitario sets the "costo_unitario" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableCostoUnitario(v *float64) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetCostoUnitario(*v)
	}
	return _u
}

// AddCostoUnitario adds value to the "costo_unitario" field.
func (_u *MateriaPrimaUpdate) AddCostoUnitario(v float64) *MateriaPrimaUpdate {
	_u.mutation.AddCostoUnitario(v)
	return _u
}

// SetStockActual sets the "stock_actual" field.
func (_u *MateriaPrimaUpdate) SetStockActual(v float64) *MateriaPrimaUpdate {
	_u.mutation.ResetStockActual()
	_u.mutation.SetStockActual(v)
	return _u
}

// SetNillableStockActual sets the "stock_actual" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillableStockActual(v *float64) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetStockActual(*v)
	}
	return _u
}

// AddStockActual adds value to the "stock_actual" field.
func (_u *MateriaPrimaUpdate) AddStockActual(v float64) *MateriaPrimaUpdate {
	_u.mutation.AddStockActual(v)
	return _u
}

// SetPuntoReorden sets the "punto_reorden" field.
func (_u *MateriaPrimaUpdate) SetPuntoReorden(v float64) *MateriaPrimaUpdate {
	_u.mutation.ResetPuntoReorden()
	_u.mutation.SetPuntoReorden(v)
	return _u
}

// SetNillablePuntoReorden sets the "punto_reorden" field if the given value is not nil.
func (_u *MateriaPrimaUpdate) SetNillablePuntoReorden(v *float64) *MateriaPrimaUpdate {
	if v != nil {
		_u.SetPuntoReorden(*v)
	}
	return _u
}

// AddPuntoReorden adds value to the "punto_reorden" field.
func (_u *MateriaPrimaUpdate) AddPuntoReorden(v float64) *MateriaPrimaUpdate {
	_u.mutation.AddPuntoReorden(v)
	return _u
}

// AddRecetaIDs adds the "recetas" edge to the Recetas entity by IDs.
func (_u *MateriaPrimaUpdate) AddRecetaIDs(ids ...int) *MateriaPrimaUpdate {
	_u.mutation.AddRecetaIDs(ids...)
	return _u
}

// AddRecetas adds the "recetas" edges to the Recetas entity.
func (_u *MateriaPrimaUpdate) AddRecetas(v ...*Recetas) *MateriaPrimaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecetaIDs(ids...)
}

// Mutation returns the MateriaPrimaMutation object of the builder.
func (_u *MateriaPrimaUpdate) Mutation() *MateriaPrimaMutation {
	return _u.mutation
}

// ClearRecetas clears all "recetas" edges to the Recetas entity.
func (_u *MateriaPrimaUpdate) ClearRecetas() *MateriaPrimaUpdate {
	_u.mutation.ClearRecetas()
	return _u
}

// RemoveRecetaIDs removes the "recetas" edge to Recetas entities by IDs.
func (_u *MateriaPrimaUpdate) RemoveRecetaIDs(ids ...int) *MateriaPrimaUpdate {
	_u.mutation.RemoveRecetaIDs(ids...)
	return _u
}

// RemoveRecetas removes "recetas" edges to Recetas entities.
func (_u *MateriaPrimaUpdate) RemoveRecetas(v ...*Recetas) *MateriaPrimaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecetaIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MateriaPrimaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MateriaPrimaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MateriaPrimaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MateriaPrimaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MateriaPrimaUpdate) check() error {
	if v, ok := _u.mutation.NombreInsumo(); ok {
		if err := materiaprima.NombreInsumoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_insumo", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.nombre_insumo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Categoria(); ok {
		if err := materiaprima.CategoriaValidator(v); err != nil {
			return &ValidationError{Name: "categoria", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.categoria": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Proveedor(); ok {
		if err := materiaprima.ProveedorValidator(v); err != nil {
			return &ValidationError{Name: "proveedor", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.proveedor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnidadMedida(); ok {
		if err := materiaprima.UnidadMedidaValidator(v); err != nil {
			return &ValidationError{Name: "unidad_medida", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.unidad_medida": %w`, err)}
		}
	}
	return nil
}

func (_u *MateriaPrimaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(materiaprima.Table, materiaprima.Columns, sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreInsumo(); ok {
		_spec.SetField(materiaprima.FieldNombreInsumo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Categoria(); ok {
		_spec.SetField(materiaprima.FieldCategoria, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proveedor(); ok {
		_spec.SetField(materiaprima.FieldProveedor, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnidadMedida(); ok {
		_spec.SetField(materiaprima.FieldUnidadMedida, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostoUnitario(); ok {
		_spec.SetField(materiaprima.FieldCostoUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostoUnitario(); ok {
		_spec.AddField(materiaprima.FieldCostoUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StockActual(); ok {
		_spec.SetField(materiaprima.FieldStockActual, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStockActual(); ok {
		_spec.AddField(materiaprima.FieldStockActual, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PuntoReorden(); ok {
		_spec.SetField(materiaprima.FieldPuntoReorden, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPuntoReorden(); ok {
		_spec.AddField(materiaprima.FieldPuntoReorden, field.TypeFloat64, value)
	}
	if _u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecetasIDs(); len(nodes) > 0 && !_u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecetasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{materiaprima.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MateriaPrimaUpdateOne is the builder for updating a single MateriaPrima entity.
type MateriaPrimaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MateriaPrimaMutation
}

// SetNombreInsumo sets the "nombre_insumo" field.
func (_u *MateriaPrimaUpdateOne) SetNombreInsumo(v string) *MateriaPrimaUpdateOne {
	_u.mutation.SetNombreInsumo(v)
	return _u
}

// SetNillableNombreInsumo sets the "nombre_insumo" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableNombreInsumo(v *string) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetNombreInsumo(*v)
	}
	return _u
}

// SetCategoria sets the "categoria" field.
func (_u *MateriaPrimaUpdateOne) SetCategoria(v string) *MateriaPrimaUpdateOne {
	_u.mutation.SetCategoria(v)
	return _u
}

// SetNillableCategoria sets the "categoria" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableCategoria(v *string) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetCategoria(*v)
	}
	return _u
}

// SetProveedor sets the "proveedor" field.
func (_u *MateriaPrimaUpdateOne) SetProveedor(v string) *MateriaPrimaUpdateOne {
	_u.mutation.SetProveedor(v)
	return _u
}

// SetNillableProveedor sets the "proveedor" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableProveedor(v *string) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetProveedor(*v)
	}
	return _u
}

// SetUnidadMedida sets the "unidad_medida" field.
func (_u *MateriaPrimaUpdateOne) SetUnidadMedida(v string) *MateriaPrimaUpdateOne {
	_u.mutation.SetUnidadMedida(v)
	return _u
}

// SetNillableUnidadMedida sets the "unidad_medida" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableUnidadMedida(v *string) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetUnidadMedida(*v)
	}
	return _u
}

// SetCostoUnitario sets the "costo_unitario" field.
func (_u *MateriaPrimaUpdateOne) SetCostoUnitario(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.ResetCostoUnitario()
	_u.mutation.SetCostoUnitario(v)
	return _u
}

// SetNillableCostoUnitario sets the "costo_unitario" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableCostoUnitario(v *float64) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetCostoUnitario(*v)
	}
	return _u
}

// AddCostoUnitario adds value to the "costo_unitario" field.
func (_u *MateriaPrimaUpdateOne) AddCostoUnitario(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.AddCostoUnitario(v)
	return _u
}

// SetStockActual sets the "stock_actual" field.
func (_u *MateriaPrimaUpdateOne) SetStockActual(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.ResetStockActual()
	_u.mutation.SetStockActual(v)
	return _u
}

// SetNillableStockActual sets the "stock_actual" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillableStockActual(v *float64) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetStockActual(*v)
	}
	return _u
}

// AddStockActual adds value to the "stock_actual" field.
func (_u *MateriaPrimaUpdateOne) AddStockActual(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.AddStockActual(v)
	return _u
}

// SetPuntoReorden sets the "punto_reorden" field.
func (_u *MateriaPrimaUpdateOne) SetPuntoReorden(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.ResetPuntoReorden()
	_u.mutation.SetPuntoReorden(v)
	return _u
}

// SetNillablePuntoReorden sets the "punto_reorden" field if the given value is not nil.
func (_u *MateriaPrimaUpdateOne) SetNillablePuntoReorden(v *float64) *MateriaPrimaUpdateOne {
	if v != nil {
		_u.SetPuntoReorden(*v)
	}
	return _u
}

// AddPuntoReorden adds value to the "punto_reorden" field.
func (_u *MateriaPrimaUpdateOne) AddPuntoReorden(v float64) *MateriaPrimaUpdateOne {
	_u.mutation.AddPuntoReorden(v)
	return _u
}

// AddRecetaIDs adds the "recetas" edge to the Recetas entity by IDs.
func (_u *MateriaPrimaUpdateOne) AddRecetaIDs(ids ...int) *MateriaPrimaUpdateOne {
	_u.mutation.AddRecetaIDs(ids...)
	return _u
}

// AddRecetas adds the "recetas" edges to the Recetas entity.
func (_u *MateriaPrimaUpdateOne) AddRecetas(v ...*Recetas) *MateriaPrimaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecetaIDs(ids...)
}

// Mutation returns the MateriaPrimaMutation object of the builder.
func (_u *MateriaPrimaUpdateOne) Mutation() *MateriaPrimaMutation {
	return _u.mutation
}

// ClearRecetas clears all "recetas" edges to the Recetas entity.
func (_u *MateriaPrimaUpdateOne) ClearRecetas() *MateriaPrimaUpdateOne {
	_u.mutation.ClearRecetas()
	return _u
}

// RemoveRecetaIDs removes the "recetas" edge to Recetas entities by IDs.
func (_u *MateriaPrimaUpdateOne) RemoveRecetaIDs(ids ...int) *MateriaPrimaUpdateOne {
	_u.mutation.RemoveRecetaIDs(ids...)
	return _u
}

// RemoveRecetas removes "recetas" edges to Recetas entities.
func (_u *MateriaPrimaUpdateOne) RemoveRecetas(v ...*Recetas) *MateriaPrimaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecetaIDs(ids...)
}

// Where appends a list predicates to the MateriaPrimaUpdate builder.
func (_u *MateriaPrimaUpdateOne) Where(ps ...predicate.MateriaPrima) *MateriaPrimaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MateriaPrimaUpdateOne) Select(field string, fields ...string) *MateriaPrimaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MateriaPrima entity.
func (_u *MateriaPrimaUpdateOne) Save(ctx context.Context) (*MateriaPrima, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MateriaPrimaUpdateOne) SaveX(ctx context.Context) *MateriaPrima {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MateriaPrimaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MateriaPrimaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MateriaPrimaUpdateOne) check() error {
	if v, ok := _u.mutation.NombreInsumo(); ok {
		if err := materiaprima.NombreInsumoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_insumo", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.nombre_insumo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Categoria(); ok {
		if err := materiaprima.CategoriaValidator(v); err != nil {
			return &ValidationError{Name: "categoria", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.categoria": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Proveedor(); ok {
		if err := materiaprima.ProveedorValidator(v); err != nil {
			return &ValidationError{Name: "proveedor", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.proveedor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnidadMedida(); ok {
		if err := materiaprima.UnidadMedidaValidator(v); err != nil {
			return &ValidationError{Name: "unidad_medida", err: fmt.Errorf(`ent: validator failed for field "MateriaPrima.unidad_medida": %w`, err)}
		}
	}
	return nil
}

func (_u *MateriaPrimaUpdateOne) sqlSave(ctx context.Context) (_node *MateriaPrima, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(materiaprima.Table, materiaprima.Columns, sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MateriaPrima.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, materiaprima.FieldID)
		for _, f := range fields {
			if !materiaprima.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != materiaprima.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreInsumo(); ok {
		_spec.SetField(materiaprima.FieldNombreInsumo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Categoria(); ok {
		_spec.SetField(materiaprima.FieldCategoria, field.TypeString, value)
	}
	if value, ok := _u.mutation.Proveedor(); ok {
		_spec.SetField(materiaprima.FieldProveedor, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnidadMedida(); ok {
		_spec.SetField(materiaprima.FieldUnidadMedida, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostoUnitario(); ok {
		_spec.SetField(materiaprima.FieldCostoUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostoUnitario(); ok {
		_spec.AddField(materiaprima.FieldCostoUnitario, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.StockActual(); ok {
		_spec.SetField(materiaprima.FieldStockActual, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStockActual(); ok {
		_spec.AddField(materiaprima.FieldStockActual, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PuntoReorden(); ok {
		_spec.SetField(materiaprima.FieldPuntoReorden, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPuntoReorden(); ok {
		_spec.AddField(materiaprima.FieldPuntoReorden, field.TypeFloat64, value)
	}
	if _u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecetasIDs(); len(nodes) > 0 && !_u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecetasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   materiaprima.RecetasTable,
			Columns: []string{materiaprima.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MateriaPrima{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{materiaprima.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
