// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MateriaPrima is the model entity for the MateriaPrima schema.
type MateriaPrima struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NombreInsumo holds the value of the "nombre_insumo" field.
	NombreInsumo string `json:"nombre_insumo,omitempty"`
	// Categoria holds the value of the "categoria" field.
	Categoria string `json:"categoria,omitempty"`
	// Proveedor holds the value of the "proveedor" field.
	Proveedor string `json:"proveedor,omitempty"`
	// UnidadMedida holds the value of the "unidad_medida" field.
	UnidadMedida string `json:"unidad_medida,omitempty"`
	// CostoUnitario holds the value of the "costo_unitario" field.
	CostoUnitario float64 `json:"costo_unitario,omitempty"`
	// StockActual holds the value of the "stock_actual" field.
	StockActual float64 `json:"stock_actual,omitempty"`
	// PuntoReorden holds the value of the "punto_reorden" field.
	PuntoReorden float64 `json:"punto_reorden,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MateriaPrimaQuery when eager-loading is set.
	Edges        MateriaPrimaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MateriaPrimaEdges holds the relations/edges for other nodes in the graph.
type MateriaPrimaEdges struct {
	// Recetas holds the value of the recetas edge.
	Recetas []*Recetas `json:"recetas,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecetasOrErr returns the Recetas value or an error if the edge
// was not loaded in eager-loading.
func (e MateriaPrimaEdges) RecetasOrErr() ([]*Recetas, error) {
	if e.loadedTypes[0] {
		return e.Recetas, nil
	}
	return nil, &NotLoadedError{edge: "recetas"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MateriaPrima) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case materiaprima.FieldCostoUnitario, materiaprima.FieldStockActual, materiaprima.FieldPuntoReorden:
			values[i] = new(sql.NullFloat64)
		case materiaprima.FieldID:
			values[i] = new(sql.NullInt64)
		case materiaprima.FieldNombreInsumo, materiaprima.FieldCategoria, materiaprima.FieldProveedor, materiaprima.FieldUnidadMedida:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MateriaPrima fields.
func (_m *MateriaPrima) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case materiaprima.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case materiaprima.FieldNombreInsumo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nombre_insumo", values[i])
			} else if value.Valid {
				_m.NombreInsumo = value.String
			}
		case materiaprima.FieldCategoria:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field categoria", values[i])
			} else if value.Valid {
				_m.Categoria = value.String
			}
		case materiaprima.FieldProveedor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proveedor", values[i])
			} else if value.Valid {
				_m.Proveedor = value.String
			}
		case materiaprima.FieldUnidadMedida:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unidad_medida", values[i])
			} else if value.Valid {
				_m.UnidadMedida = value.String
			}
		case materiaprima.FieldCostoUnitario:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field costo_unitario", values[i])
			} else if value.Valid {
				_m.CostoUnitario = value.Float64
			}
		case materiaprima.FieldStockActual:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field stock_actual", values[i])
			} else if value.Valid {
				_m.StockActual = value.Float64
			}
		case materiaprima.FieldPuntoReorden:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field punto_reorden", values[i])
			} else if value.Valid {
				_m.PuntoReorden = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MateriaPrima.
// This includes values selected through modifiers, order, etc.
func (_m *MateriaPrima) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRecetas queries the "recetas" edge of the MateriaPrima entity.
func (_m *MateriaPrima) QueryRecetas() *RecetasQuery {
	return NewMateriaPrimaClient(_m.config).QueryRecetas(_m)
}

// Update returns a builder for updating this MateriaPrima.
// Note that you need to call MateriaPrima.Unwrap() before calling this method if this MateriaPrima
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MateriaPrima) Update() *MateriaPrimaUpdateOne {
	return NewMateriaPrimaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MateriaPrima entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MateriaPrima) Unwrap() *MateriaPrima {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MateriaPrima is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MateriaPrima) String() string {
	var builder strings.Builder
	builder.WriteString("MateriaPrima(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("nombre_insumo=")
	builder.WriteString(_m.NombreInsumo)
	builder.WriteString(", ")
	builder.WriteString("categoria=")
	builder.WriteString(_m.Categoria)
	builder.WriteString(", ")
	builder.WriteString("proveedor=")
	builder.WriteString(_m.Proveedor)
	builder.WriteString(", ")
	builder.WriteString("unidad_medida=")
	builder.WriteString(_m.UnidadMedida)
	builder.WriteString(", ")
	builder.WriteString("costo_unitario=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostoUnitario))
	builder.WriteString(", ")
	builder.WriteString("stock_actual=")
	builder.WriteString(fmt.Sprintf("%v", _m.StockActual))
	builder.WriteString(", ")
	builder.WriteString("punto_reorden=")
	builder.WriteString(fmt.Sprintf("%v", _m.PuntoReorden))
	builder.WriteByte(')')
	return builder.String()
}

// MateriaPrimas is a parsable slice of MateriaPrima.
type MateriaPrimas []*MateriaPrima
