// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PedidosDelete is the builder for deleting a Pedidos entity.
type PedidosDelete struct {
	config
	hooks    []Hook
	mutation *PedidosMutation
}

// Where appends a list predicates to the PedidosDelete builder.
func (_d *PedidosDelete) Where(ps ...predicate.Pedidos) *PedidosDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PedidosDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PedidosDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PedidosDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pedidos.Table, sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PedidosDeleteOne is the builder for deleting a single Pedidos entity.
type PedidosDeleteOne struct {
	_d *PedidosDelete
}

// Where appends a list predicates to the PedidosDelete builder.
func (_d *PedidosDeleteOne) Where(ps ...predicate.Pedidos) *PedidosDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PedidosDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pedidos.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PedidosDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
