// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PedidosUpdate is the builder for updating Pedidos entities.
type PedidosUpdate struct {
	config
	hooks    []Hook
	mutation *PedidosMutation
}

// Where appends a list predicates to the PedidosUpdate builder.
func (_u *PedidosUpdate) Where(ps ...predicate.Pedidos) *PedidosUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFechaPedido sets the "fecha_pedido" field.
func (_u *PedidosUpdate) SetFechaPedido(v time.Time) *PedidosUpdate {
	_u.mutation.SetFechaPedido(v)
	return _u
}

// SetNillableFechaPedido sets the "fecha_pedido" field if the given value is not nil.
func (_u *PedidosUpdate) SetNillableFechaPedido(v *time.Time) *PedidosUpdate {
	if v != nil {
		_u.SetFechaPedido(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PedidosUpdate) SetEstado(v string) *PedidosUpdate {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PedidosUpdate) SetNillableEstado(v *string) *PedidosUpdate {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetTotalPedido sets the "total_pedido" field.
func (_u *PedidosUpdate) SetTotalPedido(v float64) *PedidosUpdate {
	_u.mutation.ResetTotalPedido()
	_u.mutation.SetTotalPedido(v)
	return _u
}

// SetNillableTotalPedido sets the "total_pedido" field if the given value is not nil.
func (_u *PedidosUpdate) SetNillableTotalPedido(v *float64) *PedidosUpdate {
	if v != nil {
		_u.SetTotalPedido(*v)
	}
	return _u
}

// AddTotalPedido adds value to the "total_pedido" field.
func (_u *PedidosUpdate) AddTotalPedido(v float64) *PedidosUpdate {
	_u.mutation.AddTotalPedido(v)
	return _u
}

// SetClienteID sets the "cliente_id" field.
func (_u *PedidosUpdate) SetClienteID(v int) *PedidosUpdate {
	_u.mutation.SetClienteID(v)
	return _u
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_u *PedidosUpdate) SetNillableClienteID(v *int) *PedidosUpdate {
	if v != nil {
		_u.SetClienteID(*v)
	}
	return _u
}

// ClearClienteID clears the value of the "cliente_id" field.
func (_u *PedidosUpdate) ClearClienteID() *PedidosUpdate {
	_u.mutation.ClearClienteID()
	return _u
}

// SetCliente sets the "cliente" edge to the Clientes entity.
func (_u *PedidosUpdate) SetCliente(v *Clientes) *PedidosUpdate {
	return _u.SetClienteID(v.ID)
}

// AddDetalleIDs adds the "detalles" edge to the DetallesPedido entity by IDs.
func (_u *PedidosUpdate) AddDetalleIDs(ids ...int) *PedidosUpdate {
	_u.mutation.AddDetalleIDs(ids...)
	return _u
}

// AddDetalles adds the "detalles" edges to the DetallesPedido entity.
func (_u *PedidosUpdate) AddDetalles(v ...*DetallesPedido) *PedidosUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDetalleIDs(ids...)
}

// Mutation returns the PedidosMutation object of the builder.
func (_u *PedidosUpdate) Mutation() *PedidosMutation {
	return _u.mutation
}

// ClearCliente clears the "cliente" edge to the Clientes entity.
func (_u *PedidosUpdate) ClearCliente() *PedidosUpdate {
	_u.mutation.ClearCliente()
	return _u
}

// ClearDetalles clears all "detalles" edges to the DetallesPedido entity.
func (_u *PedidosUpdate) ClearDetalles() *PedidosUpdate {
	_u.mutation.ClearDetalles()
	return _u
}

// RemoveDetalleIDs removes the "detalles" edge to DetallesPedido entities by IDs.
func (_u *PedidosUpdate) RemoveDetalleIDs(ids ...int) *PedidosUpdate {
	_u.mutation.RemoveDetalleIDs(ids...)
	return _u
}

// RemoveDetalles removes "detalles" edges to DetallesPedido entities.
func (_u *PedidosUpdate) RemoveDetalles(v ...*DetallesPedido) *PedidosUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDetalleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PedidosUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PedidosUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PedidosUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PedidosUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PedidosUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pedidos.Table, pedidos.Columns, sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FechaPedido(); ok {
		_spec.SetField(pedidos.FieldFechaPedido, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(pedidos.FieldEstado, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPedido(); ok {
		_spec.SetField(pedidos.FieldTotalPedido, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPedido(); ok {
		_spec.AddField(pedidos.FieldTotalPedido, field.TypeFloat64, value)
	}
	if _u.mutation.ClienteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pedidos.ClienteTable,
			Columns: []string{pedidos.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pedidos.ClienteTable,
			Columns: []string{pedidos.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DetallesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDetallesIDs(); len(nodes) > 0 && !_u.mutation.DetallesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DetallesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pedidos.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PedidosUpdateOne is the builder for updating a single Pedidos entity.
type PedidosUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PedidosMutation
}

// SetFechaPedido sets the "fecha_pedido" field.
func (_u *PedidosUpdateOne) SetFechaPedido(v time.Time) *PedidosUpdateOne {
	_u.mutation.SetFechaPedido(v)
	return _u
}

// SetNillableFechaPedido sets the "fecha_pedido" field if the given value is not nil.
func (_u *PedidosUpdateOne) SetNillableFechaPedido(v *time.Time) *PedidosUpdateOne {
	if v != nil {
		_u.SetFechaPedido(*v)
	}
	return _u
}

// SetEstado sets the "estado" field.
func (_u *PedidosUpdateOne) SetEstado(v string) *PedidosUpdateOne {
	_u.mutation.SetEstado(v)
	return _u
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_u *PedidosUpdateOne) SetNillableEstado(v *string) *PedidosUpdateOne {
	if v != nil {
		_u.SetEstado(*v)
	}
	return _u
}

// SetTotalPedido sets the "total_pedido" field.
func (_u *PedidosUpdateOne) SetTotalPedido(v float64) *PedidosUpdateOne {
	_u.mutation.ResetTotalPedido()
	_u.mutation.SetTotalPedido(v)
	return _u
}

// SetNillableTotalPedido sets the "total_pedido" field if the given value is not nil.
func (_u *PedidosUpdateOne) SetNillableTotalPedido(v *float64) *PedidosUpdateOne {
	if v != nil {
		_u.SetTotalPedido(*v)
	}
	return _u
}

// AddTotalPedido adds value to the "total_pedido" field.
func (_u *PedidosUpdateOne) AddTotalPedido(v float64) *PedidosUpdateOne {
	_u.mutation.AddTotalPedido(v)
	return _u
}

// SetClienteID sets the "cliente_id" field.
func (_u *PedidosUpdateOne) SetClienteID(v int) *PedidosUpdateOne {
	_u.mutation.SetClienteID(v)
	return _u
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_u *PedidosUpdateOne) SetNillableClienteID(v *int) *PedidosUpdateOne {
	if v != nil {
		_u.SetClienteID(*v)
	}
	return _u
}

// ClearClienteID clears the value of the "cliente_id" field.
func (_u *PedidosUpdateOne) ClearClienteID() *PedidosUpdateOne {
	_u.mutation.ClearClienteID()
	return _u
}

// SetCliente sets the "cliente" edge to the Clientes entity.
func (_u *PedidosUpdateOne) SetCliente(v *Clientes) *PedidosUpdateOne {
	return _u.SetClienteID(v.ID)
}

// AddDetalleIDs adds the "detalles" edge to the DetallesPedido entity by IDs.
func (_u *PedidosUpdateOne) AddDetalleIDs(ids ...int) *PedidosUpdateOne {
	_u.mutation.AddDetalleIDs(ids...)
	return _u
}

// AddDetalles adds the "detalles" edges to the DetallesPedido entity.
func (_u *PedidosUpdateOne) AddDetalles(v ...*DetallesPedido) *PedidosUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDetalleIDs(ids...)
}

// Mutation returns the PedidosMutation object of the builder.
func (_u *PedidosUpdateOne) Mutation() *PedidosMutation {
	return _u.mutation
}

// ClearCliente clears the "cliente" edge to the Clientes entity.
func (_u *PedidosUpdateOne) ClearCliente() *PedidosUpdateOne {
	_u.mutation.ClearCliente()
	return _u
}

// ClearDetalles clears all "detalles" edges to the DetallesPedido entity.
func (_u *PedidosUpdateOne) ClearDetalles() *PedidosUpdateOne {
	_u.mutation.ClearDetalles()
	return _u
}

// RemoveDetalleIDs removes the "detalles" edge to DetallesPedido entities by IDs.
func (_u *PedidosUpdateOne) RemoveDetalleIDs(ids ...int) *PedidosUpdateOne {
	_u.mutation.RemoveDetalleIDs(ids...)
	return _u
}

// RemoveDetalles removes "detalles" edges to DetallesPedido entities.
func (_u *PedidosUpdateOne) RemoveDetalles(v ...*DetallesPedido) *PedidosUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDetalleIDs(ids...)
}

// Where appends a list predicates to the PedidosUpdate builder.
func (_u *PedidosUpdateOne) Where(ps ...predicate.Pedidos) *PedidosUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PedidosUpdateOne) Select(field string, fields ...string) *PedidosUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pedidos entity.
func (_u *PedidosUpdateOne) Save(ctx context.Context) (*Pedidos, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PedidosUpdateOne) SaveX(ctx context.Context) *Pedidos {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PedidosUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PedidosUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PedidosUpdateOne) sqlSave(ctx context.Context) (_node *Pedidos, err error) {
	_spec := sqlgraph.NewUpdateSpec(pedidos.Table, pedidos.Columns, sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pedidos.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pedidos.FieldID)
		for _, f := range fields {
			if !pedidos.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pedidos.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FechaPedido(); ok {
		_spec.SetField(pedidos.FieldFechaPedido, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Estado(); ok {
		_spec.SetField(pedidos.FieldEstado, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPedido(); ok {
		_spec.SetField(pedidos.FieldTotalPedido, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPedido(); ok {
		_spec.AddField(pedidos.FieldTotalPedido, field.TypeFloat64, value)
	}
	if _u.mutation.ClienteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pedidos.ClienteTable,
			Columns: []string{pedidos.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pedidos.ClienteTable,
			Columns: []string{pedidos.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DetallesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDetallesIDs(); len(nodes) > 0 && !_u.mutation.DetallesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DetallesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pedidos{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pedidos.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
