// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PedidosQuery is the builder for querying Pedidos entities.
type PedidosQuery struct {
	config
	ctx          *QueryContext
	order        []pedidos.OrderOption
	inters       []Interceptor
	predicates   []predicate.Pedidos
	withCliente  *ClientesQuery
	withDetalles *DetallesPedidoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PedidosQuery builder.
func (_q *PedidosQuery) Where(ps ...predicate.Pedidos) *PedidosQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PedidosQuery) Limit(limit int) *PedidosQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PedidosQuery) Offset(offset int) *PedidosQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PedidosQuery) Unique(unique bool) *PedidosQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PedidosQuery) Order(o ...pedidos.OrderOption) *PedidosQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCliente chains the current query on the "cliente" edge.
func (_q *PedidosQuery) QueryCliente() *ClientesQuery {
	query := (&ClientesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pedidos.Table, pedidos.FieldID, selector),
			sqlgraph.To(clientes.Table, clientes.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pedidos.ClienteTable, pedidos.ClienteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDetalles chains the current query on the "detalles" edge.
func (_q *PedidosQuery) QueryDetalles() *DetallesPedidoQuery {
	query := (&DetallesPedidoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pedidos.Table, pedidos.FieldID, selector),
			sqlgraph.To(detallespedido.Table, detallespedido.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pedidos.DetallesTable, pedidos.DetallesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Pedidos entity from the query.
// Returns a *NotFoundError when no Pedidos was found.
func (_q *PedidosQuery) First(ctx context.Context) (*Pedidos, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pedidos.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PedidosQuery) FirstX(ctx context.Context) *Pedidos {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Pedidos ID from the query.
// Returns a *NotFoundError when no Pedidos ID was found.
func (_q *PedidosQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pedidos.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PedidosQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Pedidos entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Pedidos entity is found.
// Returns a *NotFoundError when no Pedidos entities are found.
func (_q *PedidosQuery) Only(ctx context.Context) (*Pedidos, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pedidos.Label}
	default:
		return nil, &NotSingularError{pedidos.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PedidosQuery) OnlyX(ctx context.Context) *Pedidos {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Pedidos ID in the query.
// Returns a *NotSingularError when more than one Pedidos ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PedidosQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pedidos.Label}
	default:
		err = &NotSingularError{pedidos.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PedidosQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PedidosSlice.
func (_q *PedidosQuery) All(ctx context.Context) ([]*Pedidos, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Pedidos, *PedidosQuery]()
	return withInterceptors[[]*Pedidos](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PedidosQuery) AllX(ctx context.Context) []*Pedidos {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Pedidos IDs.
func (_q *PedidosQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pedidos.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PedidosQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PedidosQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PedidosQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PedidosQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PedidosQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PedidosQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PedidosQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PedidosQuery) Clone() *PedidosQuery {
	if _q == nil {
		return nil
	}
	return &PedidosQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]pedidos.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Pedidos{}, _q.predicates...),
		withCliente:  _q.withCliente.Clone(),
		withDetalles: _q.withDetalles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCliente tells the query-builder to eager-load the nodes that are connected to
// the "cliente" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PedidosQuery) WithCliente(opts ...func(*ClientesQuery)) *PedidosQuery {
	query := (&ClientesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCliente = query
	return _q
}

// WithDetalles tells the query-builder to eager-load the nodes that are connected to
// the "detalles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PedidosQuery) WithDetalles(opts ...func(*DetallesPedidoQuery)) *PedidosQuery {
	query := (&DetallesPedidoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDetalles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FechaPedido time.Time `json:"fecha_pedido,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Pedidos.Query().
//		GroupBy(pedidos.FieldFechaPedido).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PedidosQuery) GroupBy(field string, fields ...string) *PedidosGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PedidosGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pedidos.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FechaPedido time.Time `json:"fecha_pedido,omitempty"`
//	}
//
//	client.Pedidos.Query().
//		Select(pedidos.FieldFechaPedido).
//		Scan(ctx, &v)
func (_q *PedidosQuery) Select(fields ...string) *PedidosSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PedidosSelect{PedidosQuery: _q}
	sbuild.label = pedidos.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PedidosSelect configured with the given aggregations.
func (_q *PedidosQuery) Aggregate(fns ...AggregateFunc) *PedidosSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PedidosQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pedidos.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PedidosQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Pedidos, error) {
	var (
		nodes       = []*Pedidos{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCliente != nil,
			_q.withDetalles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Pedidos).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Pedidos{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCliente; query != nil {
		if err := _q.loadCliente(ctx, query, nodes, nil,
			func(n *Pedidos, e *Clientes) { n.Edges.Cliente = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDetalles; query != nil {
		if err := _q.loadDetalles(ctx, query, nodes,
			func(n *Pedidos) { n.Edges.Detalles = []*DetallesPedido{} },
			func(n *Pedidos, e *DetallesPedido) { n.Edges.Detalles = append(n.Edges.Detalles, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PedidosQuery) loadCliente(ctx context.Context, query *ClientesQuery, nodes []*Pedidos, init func(*Pedidos), assign func(*Pedidos, *Clientes)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Pedidos)
	for i := range nodes {
		if nodes[i].ClienteID == nil {
			continue
		}
		fk := *nodes[i].ClienteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(clientes.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cliente_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PedidosQuery) loadDetalles(ctx context.Context, query *DetallesPedidoQuery, nodes []*Pedidos, init func(*Pedidos), assign func(*Pedidos, *DetallesPedido)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Pedidos)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(detallespedido.FieldPedidoID)
	}
	query.Where(predicate.DetallesPedido(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pedidos.DetallesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PedidoID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pedido_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PedidosQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PedidosQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pedidos.Table, pedidos.Columns, sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pedidos.FieldID)
		for i := range fields {
			if fields[i] != pedidos.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCliente != nil {
			_spec.Node.AddColumnOnce(pedidos.FieldClienteID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PedidosQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pedidos.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pedidos.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PedidosGroupBy is the group-by builder for Pedidos entities.
type PedidosGroupBy struct {
	selector
	build *PedidosQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PedidosGroupBy) Aggregate(fns ...AggregateFunc) *PedidosGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PedidosGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PedidosQuery, *PedidosGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PedidosGroupBy) sqlScan(ctx context.Context, root *PedidosQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PedidosSelect is the builder for selecting fields of Pedidos entities.
type PedidosSelect struct {
	*PedidosQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PedidosSelect) Aggregate(fns ...AggregateFunc) *PedidosSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PedidosSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PedidosQuery, *PedidosSelect](ctx, _s.PedidosQuery, _s, _s.inters, v)
}

func (_s *PedidosSelect) sqlScan(ctx context.Context, root *PedidosQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
