// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/pedidos"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PedidosCreate is the builder for creating a Pedidos entity.
type PedidosCreate struct {
	config
	mutation *PedidosMutation
	hooks    []Hook
}

// SetFechaPedido sets the "fecha_pedido" field.
func (_c *PedidosCreate) SetFechaPedido(v time.Time) *PedidosCreate {
	_c.mutation.SetFechaPedido(v)
	return _c
}

// SetNillableFechaPedido sets the "fecha_pedido" field if the given value is not nil.
func (_c *PedidosCreate) SetNillableFechaPedido(v *time.Time) *PedidosCreate {
	if v != nil {
		_c.SetFechaPedido(*v)
	}
	return _c
}

// SetEstado sets the "estado" field.
func (_c *PedidosCreate) SetEstado(v string) *PedidosCreate {
	_c.mutation.SetEstado(v)
	return _c
}

// SetNillableEstado sets the "estado" field if the given value is not nil.
func (_c *PedidosCreate) SetNillableEstado(v *string) *PedidosCreate {
	if v != nil {
		_c.SetEstado(*v)
	}
	return _c
}

// SetTotalPedido sets the "total_pedido" field.
func (_c *PedidosCreate) SetTotalPedido(v float64) *PedidosCreate {
	_c.mutation.SetTotalPedido(v)
	return _c
}

// SetClienteID sets the "cliente_id" field.
func (_c *PedidosCreate) SetClienteID(v int) *PedidosCreate {
	_c.mutation.SetClienteID(v)
	return _c
}

// SetNillableClienteID sets the "cliente_id" field if the given value is not nil.
func (_c *PedidosCreate) SetNillableClienteID(v *int) *PedidosCreate {
	if v != nil {
		_c.SetClienteID(*v)
	}
	return _c
}

// SetCliente sets the "cliente" edge to the Clientes entity.
func (_c *PedidosCreate) SetCliente(v *Clientes) *PedidosCreate {
	return _c.SetClienteID(v.ID)
}

// AddDetalleIDs adds the "detalles" edge to the DetallesPedido entity by IDs.
func (_c *PedidosCreate) AddDetalleIDs(ids ...int) *PedidosCreate {
	_c.mutation.AddDetalleIDs(ids...)
	return _c
}

// AddDetalles adds the "detalles" edges to the DetallesPedido entity.
func (_c *PedidosCreate) AddDetalles(v ...*DetallesPedido) *PedidosCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDetalleIDs(ids...)
}

// Mutation returns the PedidosMutation object of the builder.
func (_c *PedidosCreate) Mutation() *PedidosMutation {
	return _c.mutation
}

// Save creates the Pedidos in the database.
func (_c *PedidosCreate) Save(ctx context.Context) (*Pedidos, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PedidosCreate) SaveX(ctx context.Context) *Pedidos {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PedidosCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PedidosCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PedidosCreate) defaults() {
	if _, ok := _c.mutation.FechaPedido(); !ok {
		v := pedidos.DefaultFechaPedido()
		_c.mutation.SetFechaPedido(v)
	}
	if _, ok := _c.mutation.Estado(); !ok {
		v := pedidos.DefaultEstado
		_c.mutation.SetEstado(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PedidosCreate) check() error {
	if _, ok := _c.mutation.FechaPedido(); !ok {
		return &ValidationError{Name: "fecha_pedido", err: errors.New(`ent: missing required field "Pedidos.fecha_pedido"`)}
	}
	if _, ok := _c.mutation.Estado(); !ok {
		return &ValidationError{Name: "estado", err: errors.New(`ent: missing required field "Pedidos.estado"`)}
	}
	if _, ok := _c.mutation.TotalPedido(); !ok {
		return &ValidationError{Name: "total_pedido", err: errors.New(`ent: missing required field "Pedidos.total_pedido"`)}
	}
	return nil
}

func (_c *PedidosCreate) sqlSave(ctx context.Context) (*Pedidos, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PedidosCreate) createSpec() (*Pedidos, *sqlgraph.CreateSpec) {
	var (
		_node = &Pedidos{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pedidos.Table, sqlgraph.NewFieldSpec(pedidos.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FechaPedido(); ok {
		_spec.SetField(pedidos.FieldFechaPedido, field.TypeTime, value)
		_node.FechaPedido = value
	}
	if value, ok := _c.mutation.Estado(); ok {
		_spec.SetField(pedidos.FieldEstado, field.TypeString, value)
		_node.Estado = value
	}
	if value, ok := _c.mutation.TotalPedido(); ok {
		_spec.SetField(pedidos.FieldTotalPedido, field.TypeFloat64, value)
		_node.TotalPedido = value
	}
	if nodes := _c.mutation.ClienteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pedidos.ClienteTable,
			Columns: []string{pedidos.ClienteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClienteID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DetallesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pedidos.DetallesTable,
			Columns: []string{pedidos.DetallesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PedidosCreateBulk is the builder for creating many Pedidos entities in bulk.
type PedidosCreateBulk struct {
	config
	err      error
	builders []*PedidosCreate
}

// Save creates the Pedidos entities in the database.
func (_c *PedidosCreateBulk) Save(ctx context.Context) ([]*Pedidos, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Pedidos, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PedidosMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PedidosCreateBulk) SaveX(ctx context.Context) []*Pedidos {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PedidosCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PedidosCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
