// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/pedidos"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Pedidos is the model entity for the Pedidos schema.
type Pedidos struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FechaPedido holds the value of the "fecha_pedido" field.
	FechaPedido time.Time `json:"fecha_pedido,omitempty"`
	// Estado holds the value of the "estado" field.
	Estado string `json:"estado,omitempty"`
	// TotalPedido holds the value of the "total_pedido" field.
	TotalPedido float64 `json:"total_pedido,omitempty"`
	// ClienteID holds the value of the "cliente_id" field.
	ClienteID *int `json:"cliente_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PedidosQuery when eager-loading is set.
	Edges        PedidosEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PedidosEdges holds the relations/edges for other nodes in the graph.
type PedidosEdges struct {
	// Cliente holds the value of the cliente edge.
	Cliente *Clientes `json:"cliente,omitempty"`
	// Detalles holds the value of the detalles edge.
	Detalles []*DetallesPedido `json:"detalles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ClienteOrErr returns the Cliente value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PedidosEdges) ClienteOrErr() (*Clientes, error) {
	if e.Cliente != nil {
		return e.Cliente, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: clientes.Label}
	}
	return nil, &NotLoadedError{edge: "cliente"}
}

// DetallesOrErr returns the Detalles value or an error if the edge
// was not loaded in eager-loading.
func (e PedidosEdges) DetallesOrErr() ([]*DetallesPedido, error) {
	if e.loadedTypes[1] {
		return e.Detalles, nil
	}
	return nil, &NotLoadedError{edge: "detalles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pedidos) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pedidos.FieldTotalPedido:
			values[i] = new(sql.NullFloat64)
		case pedidos.FieldID, pedidos.FieldClienteID:
			values[i] = new(sql.NullInt64)
		case pedidos.FieldEstado:
			values[i] = new(sql.NullString)
		case pedidos.FieldFechaPedido:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pedidos fields.
func (_m *Pedidos) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pedidos.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pedidos.FieldFechaPedido:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fecha_pedido", values[i])
			} else if value.Valid {
				_m.FechaPedido = value.Time
			}
		case pedidos.FieldEstado:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field estado", values[i])
			} else if value.Valid {
				_m.Estado = value.String
			}
		case pedidos.FieldTotalPedido:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_pedido", values[i])
			} else if value.Valid {
				_m.TotalPedido = value.Float64
			}
		case pedidos.FieldClienteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cliente_id", values[i])
			} else if value.Valid {
				_m.ClienteID = new(int)
				*_m.ClienteID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pedidos.
// This includes values selected through modifiers, order, etc.
func (_m *Pedidos) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCliente queries the "cliente" edge of the Pedidos entity.
func (_m *Pedidos) QueryCliente() *ClientesQuery {
	return NewPedidosClient(_m.config).QueryCliente(_m)
}

// QueryDetalles queries the "detalles" edge of the Pedidos entity.
func (_m *Pedidos) QueryDetalles() *DetallesPedidoQuery {
	return NewPedidosClient(_m.config).QueryDetalles(_m)
}

// Update returns a builder for updating this Pedidos.
// Note that you need to call Pedidos.Unwrap() before calling this method if this Pedidos
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Pedidos) Update() *PedidosUpdateOne {
	return NewPedidosClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Pedidos entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Pedidos) Unwrap() *Pedidos {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pedidos is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Pedidos) String() string {
	var builder strings.Builder
	builder.WriteString("Pedidos(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("fecha_pedido=")
	builder.WriteString(_m.FechaPedido.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("estado=")
	builder.WriteString(_m.Estado)
	builder.WriteString(", ")
	builder.WriteString("total_pedido=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPedido))
	builder.WriteString(", ")
	if v := _m.ClienteID; v != nil {
		builder.WriteString("cliente_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PedidosSlice is a parsable slice of Pedidos.
type PedidosSlice []*Pedidos
