// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/recetas"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductosMenuUpdate is the builder for updating ProductosMenu entities.
type ProductosMenuUpdate struct {
	config
	hooks    []Hook
	mutation *ProductosMenuMutation
}

// Where appends a list predicates to the ProductosMenuUpdate builder.
func (_u *ProductosMenuUpdate) Where(ps ...predicate.ProductosMenu) *ProductosMenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNombreProducto sets the "nombre_producto" field.
func (_u *ProductosMenuUpdate) SetNombreProducto(v string) *ProductosMenuUpdate {
	_u.mutation.SetNombreProducto(v)
	return _u
}

// SetNillableNombreProducto sets the "nombre_producto" field if the given value is not nil.
func (_u *ProductosMenuUpdate) SetNillableNombreProducto(v *string) *ProductosMenuUpdate {
	if v != nil {
		_u.SetNombreProducto(*v)
	}
	return _u
}

// SetCategoriaMenu sets the "categoria_menu" field.
func (_u *ProductosMenuUpdate) SetCategoriaMenu(v string) *ProductosMenuUpdate {
	_u.mutation.SetCategoriaMenu(v)
	return _u
}

// SetNillableCategoriaMenu sets the "categoria_menu" field if the given value is not nil.
func (_u *ProductosMenuUpdate) SetNillableCategoriaMenu(v *string) *ProductosMenuUpdate {
	if v != nil {
		_u.SetCategoriaMenu(*v)
	}
	return _u
}

// SetPrecioVenta sets the "precio_venta" field.
func (_u *ProductosMenuUpdate) SetPrecioVenta(v float64) *ProductosMenuUpdate {
	_u.mutation.ResetPrecioVenta()
	_u.mutation.SetPrecioVenta(v)
	return _u
}

// SetNillablePrecioVenta sets the "precio_venta" field if the given value is not nil.
func (_u *ProductosMenuUpdate) SetNillablePrecioVenta(v *float64) *ProductosMenuUpdate {
	if v != nil {
		_u.SetPrecioVenta(*v)
	}
	return _u
}

// AddPrecioVenta adds value to the "precio_venta" field.
func (_u *ProductosMenuUpdate) AddPrecioVenta(v float64) *ProductosMenuUpdate {
	_u.mutation.AddPrecioVenta(v)
	return _u
}

// AddRecetaIDs adds the "recetas" edge to the Recetas entity by IDs.
func (_u *ProductosMenuUpdate) AddRecetaIDs(ids ...int) *ProductosMenuUpdate {
	_u.mutation.AddRecetaIDs(ids...)
	return _u
}

// AddRecetas adds the "recetas" edges to the Recetas entity.
func (_u *ProductosMenuUpdate) AddRecetas(v ...*Recetas) *ProductosMenuUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecetaIDs(ids...)
}

// AddDetallesPedidoIDs adds the "detalles_pedido" edge to the DetallesPedido entity by IDs.
func (_u *ProductosMenuUpdate) AddDetallesPedidoIDs(ids ...int) *ProductosMenuUpdate {
	_u.mutation.AddDetallesPedidoIDs(ids...)
	return _u
}

// AddDetallesPedido adds the "detalles_pedido" edges to the DetallesPedido entity.
func (_u *ProductosMenuUpdate) AddDetallesPedido(v ...*DetallesPedido) *ProductosMenuUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDetallesPedidoIDs(ids...)
}

// Mutation returns the ProductosMenuMutation object of the builder.
func (_u *ProductosMenuUpdate) Mutation() *ProductosMenuMutation {
	return _u.mutation
}

// ClearRecetas clears all "recetas" edges to the Recetas entity.
func (_u *ProductosMenuUpdate) ClearRecetas() *ProductosMenuUpdate {
	_u.mutation.ClearRecetas()
	return _u
}

// RemoveRecetaIDs removes the "recetas" edge to Recetas entities by IDs.
func (_u *ProductosMenuUpdate) RemoveRecetaIDs(ids ...int) *ProductosMenuUpdate {
	_u.mutation.RemoveRecetaIDs(ids...)
	return _u
}

// RemoveRecetas removes "recetas" edges to Recetas entities.
func (_u *ProductosMenuUpdate) RemoveRecetas(v ...*Recetas) *ProductosMenuUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecetaIDs(ids...)
}

// ClearDetallesPedido clears all "detalles_pedido" edges to the DetallesPedido entity.
func (_u *ProductosMenuUpdate) ClearDetallesPedido() *ProductosMenuUpdate {
	_u.mutation.ClearDetallesPedido()
	return _u
}

// RemoveDetallesPedidoIDs removes the "detalles_pedido" edge to DetallesPedido entities by IDs.
func (_u *ProductosMenuUpdate) RemoveDetallesPedidoIDs(ids ...int) *ProductosMenuUpdate {
	_u.mutation.RemoveDetallesPedidoIDs(ids...)
	return _u
}

// RemoveDetallesPedido removes "detalles_pedido" edges to DetallesPedido entities.
func (_u *ProductosMenuUpdate) RemoveDetallesPedido(v ...*DetallesPedido) *ProductosMenuUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDetallesPedidoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductosMenuUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductosMenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductosMenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductosMenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductosMenuUpdate) check() error {
	if v, ok := _u.mutation.NombreProducto(); ok {
		if err := productosmenu.NombreProductoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_producto", err: fmt.Errorf(`ent: validator failed for field "ProductosMenu.nombre_producto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoriaMenu(); ok {
		if err := productosmenu.CategoriaMenuValidator(v); err != nil {
			return &ValidationError{Name: "categoria_menu", err: fmt.Errorf(`ent: validator failed for field "ProductosMenu.categoria_menu": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductosMenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productosmenu.Table, productosmenu.Columns, sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreProducto(); ok {
		_spec.SetField(productosmenu.FieldNombreProducto, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoriaMenu(); ok {
		_spec.SetField(productosmenu.FieldCategoriaMenu, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrecioVenta(); ok {
		_spec.SetField(productosmenu.FieldPrecioVenta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrecioVenta(); ok {
		_spec.AddField(productosmenu.FieldPrecioVenta, field.TypeFloat64, value)
	}
	if _u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecetasIDs(); len(nodes) > 0 && !_u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecetasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DetallesPedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDetallesPedidoIDs(); len(nodes) > 0 && !_u.mutation.DetallesPedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DetallesPedidoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productosmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductosMenuUpdateOne is the builder for updating a single ProductosMenu entity.
type ProductosMenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductosMenuMutation
}

// SetNombreProducto sets the "nombre_producto" field.
func (_u *ProductosMenuUpdateOne) SetNombreProducto(v string) *ProductosMenuUpdateOne {
	_u.mutation.SetNombreProducto(v)
	return _u
}

// SetNillableNombreProducto sets the "nombre_producto" field if the given value is not nil.
func (_u *ProductosMenuUpdateOne) SetNillableNombreProducto(v *string) *ProductosMenuUpdateOne {
	if v != nil {
		_u.SetNombreProducto(*v)
	}
	return _u
}

// SetCategoriaMenu sets the "categoria_menu" field.
func (_u *ProductosMenuUpdateOne) SetCategoriaMenu(v string) *ProductosMenuUpdateOne {
	_u.mutation.SetCategoriaMenu(v)
	return _u
}

// SetNillableCategoriaMenu sets the "categoria_menu" field if the given value is not nil.
func (_u *ProductosMenuUpdateOne) SetNillableCategoriaMenu(v *string) *ProductosMenuUpdateOne {
	if v != nil {
		_u.SetCategoriaMenu(*v)
	}
	return _u
}

// SetPrecioVenta sets the "precio_venta" field.
func (_u *ProductosMenuUpdateOne) SetPrecioVenta(v float64) *ProductosMenuUpdateOne {
	_u.mutation.ResetPrecioVenta()
	_u.mutation.SetPrecioVenta(v)
	return _u
}

// SetNillablePrecioVenta sets the "precio_venta" field if the given value is not nil.
func (_u *ProductosMenuUpdateOne) SetNillablePrecioVenta(v *float64) *ProductosMenuUpdateOne {
	if v != nil {
		_u.SetPrecioVenta(*v)
	}
	return _u
}

// AddPrecioVenta adds value to the "precio_venta" field.
func (_u *ProductosMenuUpdateOne) AddPrecioVenta(v float64) *ProductosMenuUpdateOne {
	_u.mutation.AddPrecioVenta(v)
	return _u
}

// AddRecetaIDs adds the "recetas" edge to the Recetas entity by IDs.
func (_u *ProductosMenuUpdateOne) AddRecetaIDs(ids ...int) *ProductosMenuUpdateOne {
	_u.mutation.AddRecetaIDs(ids...)
	return _u
}

// AddRecetas adds the "recetas" edges to the Recetas entity.
func (_u *ProductosMenuUpdateOne) AddRecetas(v ...*Recetas) *ProductosMenuUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecetaIDs(ids...)
}

// AddDetallesPedidoIDs adds the "detalles_pedido" edge to the DetallesPedido entity by IDs.
func (_u *ProductosMenuUpdateOne) AddDetallesPedidoIDs(ids ...int) *ProductosMenuUpdateOne {
	_u.mutation.AddDetallesPedidoIDs(ids...)
	return _u
}

// AddDetallesPedido adds the "detalles_pedido" edges to the DetallesPedido entity.
func (_u *ProductosMenuUpdateOne) AddDetallesPedido(v ...*DetallesPedido) *ProductosMenuUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDetallesPedidoIDs(ids...)
}

// Mutation returns the ProductosMenuMutation object of the builder.
func (_u *ProductosMenuUpdateOne) Mutation() *ProductosMenuMutation {
	return _u.mutation
}

// ClearRecetas clears all "recetas" edges to the Recetas entity.
func (_u *ProductosMenuUpdateOne) ClearRecetas() *ProductosMenuUpdateOne {
	_u.mutation.ClearRecetas()
	return _u
}

// RemoveRecetaIDs removes the "recetas" edge to Recetas entities by IDs.
func (_u *ProductosMenuUpdateOne) RemoveRecetaIDs(ids ...int) *ProductosMenuUpdateOne {
	_u.mutation.RemoveRecetaIDs(ids...)
	return _u
}

// RemoveRecetas removes "recetas" edges to Recetas entities.
func (_u *ProductosMenuUpdateOne) RemoveRecetas(v ...*Recetas) *ProductosMenuUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecetaIDs(ids...)
}

// ClearDetallesPedido clears all "detalles_pedido" edges to the DetallesPedido entity.
func (_u *ProductosMenuUpdateOne) ClearDetallesPedido() *ProductosMenuUpdateOne {
	_u.mutation.ClearDetallesPedido()
	return _u
}

// RemoveDetallesPedidoIDs removes the "detalles_pedido" edge to DetallesPedido entities by IDs.
func (_u *ProductosMenuUpdateOne) RemoveDetallesPedidoIDs(ids ...int) *ProductosMenuUpdateOne {
	_u.mutation.RemoveDetallesPedidoIDs(ids...)
	return _u
}

// RemoveDetallesPedido removes "detalles_pedido" edges to DetallesPedido entities.
func (_u *ProductosMenuUpdateOne) RemoveDetallesPedido(v ...*DetallesPedido) *ProductosMenuUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDetallesPedidoIDs(ids...)
}

// Where appends a list predicates to the ProductosMenuUpdate builder.
func (_u *ProductosMenuUpdateOne) Where(ps ...predicate.ProductosMenu) *ProductosMenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductosMenuUpdateOne) Select(field string, fields ...string) *ProductosMenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductosMenu entity.
func (_u *ProductosMenuUpdateOne) Save(ctx context.Context) (*ProductosMenu, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductosMenuUpdateOne) SaveX(ctx context.Context) *ProductosMenu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductosMenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductosMenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductosMenuUpdateOne) check() error {
	if v, ok := _u.mutation.NombreProducto(); ok {
		if err := productosmenu.NombreProductoValidator(v); err != nil {
			return &ValidationError{Name: "nombre_producto", err: fmt.Errorf(`ent: validator failed for field "ProductosMenu.nombre_producto": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CategoriaMenu(); ok {
		if err := productosmenu.CategoriaMenuValidator(v); err != nil {
			return &ValidationError{Name: "categoria_menu", err: fmt.Errorf(`ent: validator failed for field "ProductosMenu.categoria_menu": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductosMenuUpdateOne) sqlSave(ctx context.Context) (_node *ProductosMenu, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productosmenu.Table, productosmenu.Columns, sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductosMenu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productosmenu.FieldID)
		for _, f := range fields {
			if !productosmenu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productosmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NombreProducto(); ok {
		_spec.SetField(productosmenu.FieldNombreProducto, field.TypeString, value)
	}
	if value, ok := _u.mutation.CategoriaMenu(); ok {
		_spec.SetField(productosmenu.FieldCategoriaMenu, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrecioVenta(); ok {
		_spec.SetField(productosmenu.FieldPrecioVenta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrecioVenta(); ok {
		_spec.AddField(productosmenu.FieldPrecioVenta, field.TypeFloat64, value)
	}
	if _u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecetasIDs(); len(nodes) > 0 && !_u.mutation.RecetasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecetasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.RecetasTable,
			Columns: []string{productosmenu.RecetasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DetallesPedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDetallesPedidoIDs(); len(nodes) > 0 && !_u.mutation.DetallesPedidoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DetallesPedidoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productosmenu.DetallesPedidoTable,
			Columns: []string{productosmenu.DetallesPedidoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(detallespedido.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductosMenu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productosmenu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
