// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/detallespedido"
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/recetas"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductosMenuQuery is the builder for querying ProductosMenu entities.
type ProductosMenuQuery struct {
	config
	ctx                *QueryContext
	order              []productosmenu.OrderOption
	inters             []Interceptor
	predicates         []predicate.ProductosMenu
	withRecetas        *RecetasQuery
	withDetallesPedido *DetallesPedidoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductosMenuQuery builder.
func (_q *ProductosMenuQuery) Where(ps ...predicate.ProductosMenu) *ProductosMenuQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProductosMenuQuery) Limit(limit int) *ProductosMenuQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProductosMenuQuery) Offset(offset int) *ProductosMenuQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProductosMenuQuery) Unique(unique bool) *ProductosMenuQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProductosMenuQuery) Order(o ...productosmenu.OrderOption) *ProductosMenuQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRecetas chains the current query on the "recetas" edge.
func (_q *ProductosMenuQuery) QueryRecetas() *RecetasQuery {
	query := (&RecetasClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productosmenu.Table, productosmenu.FieldID, selector),
			sqlgraph.To(recetas.Table, recetas.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productosmenu.RecetasTable, productosmenu.RecetasColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDetallesPedido chains the current query on the "detalles_pedido" edge.
func (_q *ProductosMenuQuery) QueryDetallesPedido() *DetallesPedidoQuery {
	query := (&DetallesPedidoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productosmenu.Table, productosmenu.FieldID, selector),
			sqlgraph.To(detallespedido.Table, detallespedido.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productosmenu.DetallesPedidoTable, productosmenu.DetallesPedidoColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductosMenu entity from the query.
// Returns a *NotFoundError when no ProductosMenu was found.
func (_q *ProductosMenuQuery) First(ctx context.Context) (*ProductosMenu, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productosmenu.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProductosMenuQuery) FirstX(ctx context.Context) *ProductosMenu {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductosMenu ID from the query.
// Returns a *NotFoundError when no ProductosMenu ID was found.
func (_q *ProductosMenuQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productosmenu.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProductosMenuQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductosMenu entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductosMenu entity is found.
// Returns a *NotFoundError when no ProductosMenu entities are found.
func (_q *ProductosMenuQuery) Only(ctx context.Context) (*ProductosMenu, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productosmenu.Label}
	default:
		return nil, &NotSingularError{productosmenu.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProductosMenuQuery) OnlyX(ctx context.Context) *ProductosMenu {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductosMenu ID in the query.
// Returns a *NotSingularError when more than one ProductosMenu ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProductosMenuQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productosmenu.Label}
	default:
		err = &NotSingularError{productosmenu.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProductosMenuQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductosMenus.
func (_q *ProductosMenuQuery) All(ctx context.Context) ([]*ProductosMenu, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductosMenu, *ProductosMenuQuery]()
	return withInterceptors[[]*ProductosMenu](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProductosMenuQuery) AllX(ctx context.Context) []*ProductosMenu {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductosMenu IDs.
func (_q *ProductosMenuQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(productosmenu.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProductosMenuQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProductosMenuQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProductosMenuQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProductosMenuQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProductosMenuQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProductosMenuQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductosMenuQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProductosMenuQuery) Clone() *ProductosMenuQuery {
	if _q == nil {
		return nil
	}
	return &ProductosMenuQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]productosmenu.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ProductosMenu{}, _q.predicates...),
		withRecetas:        _q.withRecetas.Clone(),
		withDetallesPedido: _q.withDetallesPedido.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRecetas tells the query-builder to eager-load the nodes that are connected to
// the "recetas" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductosMenuQuery) WithRecetas(opts ...func(*RecetasQuery)) *ProductosMenuQuery {
	query := (&RecetasClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecetas = query
	return _q
}

// WithDetallesPedido tells the query-builder to eager-load the nodes that are connected to
// the "detalles_pedido" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductosMenuQuery) WithDetallesPedido(opts ...func(*DetallesPedidoQuery)) *ProductosMenuQuery {
	query := (&DetallesPedidoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDetallesPedido = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NombreProducto string `json:"nombre_producto,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductosMenu.Query().
//		GroupBy(productosmenu.FieldNombreProducto).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProductosMenuQuery) GroupBy(field string, fields ...string) *ProductosMenuGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductosMenuGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = productosmenu.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NombreProducto string `json:"nombre_producto,omitempty"`
//	}
//
//	client.ProductosMenu.Query().
//		Select(productosmenu.FieldNombreProducto).
//		Scan(ctx, &v)
func (_q *ProductosMenuQuery) Select(fields ...string) *ProductosMenuSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProductosMenuSelect{ProductosMenuQuery: _q}
	sbuild.label = productosmenu.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductosMenuSelect configured with the given aggregations.
func (_q *ProductosMenuQuery) Aggregate(fns ...AggregateFunc) *ProductosMenuSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProductosMenuQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !productosmenu.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProductosMenuQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductosMenu, error) {
	var (
		nodes       = []*ProductosMenu{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRecetas != nil,
			_q.withDetallesPedido != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductosMenu).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductosMenu{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRecetas; query != nil {
		if err := _q.loadRecetas(ctx, query, nodes,
			func(n *ProductosMenu) { n.Edges.Recetas = []*Recetas{} },
			func(n *ProductosMenu, e *Recetas) { n.Edges.Recetas = append(n.Edges.Recetas, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDetallesPedido; query != nil {
		if err := _q.loadDetallesPedido(ctx, query, nodes,
			func(n *ProductosMenu) { n.Edges.DetallesPedido = []*DetallesPedido{} },
			func(n *ProductosMenu, e *DetallesPedido) { n.Edges.DetallesPedido = append(n.Edges.DetallesPedido, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProductosMenuQuery) loadRecetas(ctx context.Context, query *RecetasQuery, nodes []*ProductosMenu, init func(*ProductosMenu), assign func(*ProductosMenu, *Recetas)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProductosMenu)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Recetas(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(productosmenu.RecetasColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.productos_menu_recetas
		if fk == nil {
			return fmt.Errorf(`foreign-key "productos_menu_recetas" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "productos_menu_recetas" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ProductosMenuQuery) loadDetallesPedido(ctx context.Context, query *DetallesPedidoQuery, nodes []*ProductosMenu, init func(*ProductosMenu), assign func(*ProductosMenu, *DetallesPedido)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProductosMenu)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(detallespedido.FieldProductoID)
	}
	query.Where(predicate.DetallesPedido(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(productosmenu.DetallesPedidoColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProductoID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "producto_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ProductosMenuQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProductosMenuQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productosmenu.Table, productosmenu.Columns, sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productosmenu.FieldID)
		for i := range fields {
			if fields[i] != productosmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProductosMenuQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(productosmenu.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = productosmenu.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductosMenuGroupBy is the group-by builder for ProductosMenu entities.
type ProductosMenuGroupBy struct {
	selector
	build *ProductosMenuQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProductosMenuGroupBy) Aggregate(fns ...AggregateFunc) *ProductosMenuGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProductosMenuGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductosMenuQuery, *ProductosMenuGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProductosMenuGroupBy) sqlScan(ctx context.Context, root *ProductosMenuQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductosMenuSelect is the builder for selecting fields of ProductosMenu entities.
type ProductosMenuSelect struct {
	*ProductosMenuQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProductosMenuSelect) Aggregate(fns ...AggregateFunc) *ProductosMenuSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProductosMenuSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductosMenuQuery, *ProductosMenuSelect](ctx, _s.ProductosMenuQuery, _s, _s.inters, v)
}

func (_s *ProductosMenuSelect) sqlScan(ctx context.Context, root *ProductosMenuQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
