// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/recetas"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecetasDelete is the builder for deleting a Recetas entity.
type RecetasDelete struct {
	config
	hooks    []Hook
	mutation *RecetasMutation
}

// Where appends a list predicates to the RecetasDelete builder.
func (_d *RecetasDelete) Where(ps ...predicate.Recetas) *RecetasDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RecetasDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecetasDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RecetasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recetas.Table, sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RecetasDeleteOne is the builder for deleting a single Recetas entity.
type RecetasDeleteOne struct {
	_d *RecetasDelete
}

// Where appends a list predicates to the RecetasDelete builder.
func (_d *RecetasDeleteOne) Where(ps ...predicate.Recetas) *RecetasDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RecetasDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recetas.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RecetasDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
