// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/predicate"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/recetas"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecetasUpdate is the builder for updating Recetas entities.
type RecetasUpdate struct {
	config
	hooks    []Hook
	mutation *RecetasMutation
}

// Where appends a list predicates to the RecetasUpdate builder.
func (_u *RecetasUpdate) Where(ps ...predicate.Recetas) *RecetasUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCantidadNecesaria sets the "cantidad_necesaria" field.
func (_u *RecetasUpdate) SetCantidadNecesaria(v float64) *RecetasUpdate {
	_u.mutation.ResetCantidadNecesaria()
	_u.mutation.SetCantidadNecesaria(v)
	return _u
}

// SetNillableCantidadNecesaria sets the "cantidad_necesaria" field if the given value is not nil.
func (_u *RecetasUpdate) SetNillableCantidadNecesaria(v *float64) *RecetasUpdate {
	if v != nil {
		_u.SetCantidadNecesaria(*v)
	}
	return _u
}

// AddCantidadNecesaria adds value to the "cantidad_necesaria" field.
func (_u *RecetasUpdate) AddCantidadNecesaria(v float64) *RecetasUpdate {
	_u.mutation.AddCantidadNecesaria(v)
	return _u
}

// SetProductoID sets the "producto" edge to the ProductosMenu entity by ID.
func (_u *RecetasUpdate) SetProductoID(id int) *RecetasUpdate {
	_u.mutation.SetProductoID(id)
	return _u
}

// SetProducto sets the "producto" edge to the ProductosMenu entity.
func (_u *RecetasUpdate) SetProducto(v *ProductosMenu) *RecetasUpdate {
	return _u.SetProductoID(v.ID)
}

// SetMateriaPrimaID sets the "materia_prima" edge to the MateriaPrima entity by ID.
func (_u *RecetasUpdate) SetMateriaPrimaID(id int) *RecetasUpdate {
	_u.mutation.SetMateriaPrimaID(id)
	return _u
}

// SetMateriaPrima sets the "materia_prima" edge to the MateriaPrima entity.
func (_u *RecetasUpdate) SetMateriaPrima(v *MateriaPrima) *RecetasUpdate {
	return _u.SetMateriaPrimaID(v.ID)
}

// Mutation returns the RecetasMutation object of the builder.
func (_u *RecetasUpdate) Mutation() *RecetasMutation {
	return _u.mutation
}

// ClearProducto clears the "producto" edge to the ProductosMenu entity.
func (_u *RecetasUpdate) ClearProducto() *RecetasUpdate {
	_u.mutation.ClearProducto()
	return _u
}

// ClearMateriaPrima clears the "materia_prima" edge to the MateriaPrima entity.
func (_u *RecetasUpdate) ClearMateriaPrima() *RecetasUpdate {
	_u.mutation.ClearMateriaPrima()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecetasUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecetasUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecetasUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecetasUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecetasUpdate) check() error {
	if _u.mutation.ProductoCleared() && len(_u.mutation.ProductoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Recetas.producto"`)
	}
	if _u.mutation.MateriaPrimaCleared() && len(_u.mutation.MateriaPrimaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Recetas.materia_prima"`)
	}
	return nil
}

func (_u *RecetasUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recetas.Table, recetas.Columns, sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CantidadNecesaria(); ok {
		_spec.SetField(recetas.FieldCantidadNecesaria, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCantidadNecesaria(); ok {
		_spec.AddField(recetas.FieldCantidadNecesaria, field.TypeFloat64, value)
	}
	if _u.mutation.ProductoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.ProductoTable,
			Columns: []string{recetas.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.ProductoTable,
			Columns: []string{recetas.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MateriaPrimaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.MateriaPrimaTable,
			Columns: []string{recetas.MateriaPrimaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MateriaPrimaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.MateriaPrimaTable,
			Columns: []string{recetas.MateriaPrimaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recetas.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecetasUpdateOne is the builder for updating a single Recetas entity.
type RecetasUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecetasMutation
}

// SetCantidadNecesaria sets the "cantidad_necesaria" field.
func (_u *RecetasUpdateOne) SetCantidadNecesaria(v float64) *RecetasUpdateOne {
	_u.mutation.ResetCantidadNecesaria()
	_u.mutation.SetCantidadNecesaria(v)
	return _u
}

// SetNillableCantidadNecesaria sets the "cantidad_necesaria" field if the given value is not nil.
func (_u *RecetasUpdateOne) SetNillableCantidadNecesaria(v *float64) *RecetasUpdateOne {
	if v != nil {
		_u.SetCantidadNecesaria(*v)
	}
	return _u
}

// AddCantidadNecesaria adds value to the "cantidad_necesaria" field.
func (_u *RecetasUpdateOne) AddCantidadNecesaria(v float64) *RecetasUpdateOne {
	_u.mutation.AddCantidadNecesaria(v)
	return _u
}

// SetProductoID sets the "producto" edge to the ProductosMenu entity by ID.
func (_u *RecetasUpdateOne) SetProductoID(id int) *RecetasUpdateOne {
	_u.mutation.SetProductoID(id)
	return _u
}

// SetProducto sets the "producto" edge to the ProductosMenu entity.
func (_u *RecetasUpdateOne) SetProducto(v *ProductosMenu) *RecetasUpdateOne {
	return _u.SetProductoID(v.ID)
}

// SetMateriaPrimaID sets the "materia_prima" edge to the MateriaPrima entity by ID.
func (_u *RecetasUpdateOne) SetMateriaPrimaID(id int) *RecetasUpdateOne {
	_u.mutation.SetMateriaPrimaID(id)
	return _u
}

// SetMateriaPrima sets the "materia_prima" edge to the MateriaPrima entity.
func (_u *RecetasUpdateOne) SetMateriaPrima(v *MateriaPrima) *RecetasUpdateOne {
	return _u.SetMateriaPrimaID(v.ID)
}

// Mutation returns the RecetasMutation object of the builder.
func (_u *RecetasUpdateOne) Mutation() *RecetasMutation {
	return _u.mutation
}

// ClearProducto clears the "producto" edge to the ProductosMenu entity.
func (_u *RecetasUpdateOne) ClearProducto() *RecetasUpdateOne {
	_u.mutation.ClearProducto()
	return _u
}

// ClearMateriaPrima clears the "materia_prima" edge to the MateriaPrima entity.
func (_u *RecetasUpdateOne) ClearMateriaPrima() *RecetasUpdateOne {
	_u.mutation.ClearMateriaPrima()
	return _u
}

// Where appends a list predicates to the RecetasUpdate builder.
func (_u *RecetasUpdateOne) Where(ps ...predicate.Recetas) *RecetasUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecetasUpdateOne) Select(field string, fields ...string) *RecetasUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Recetas entity.
func (_u *RecetasUpdateOne) Save(ctx context.Context) (*Recetas, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecetasUpdateOne) SaveX(ctx context.Context) *Recetas {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecetasUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecetasUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecetasUpdateOne) check() error {
	if _u.mutation.ProductoCleared() && len(_u.mutation.ProductoIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Recetas.producto"`)
	}
	if _u.mutation.MateriaPrimaCleared() && len(_u.mutation.MateriaPrimaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Recetas.materia_prima"`)
	}
	return nil
}

func (_u *RecetasUpdateOne) sqlSave(ctx context.Context) (_node *Recetas, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recetas.Table, recetas.Columns, sqlgraph.NewFieldSpec(recetas.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Recetas.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recetas.FieldID)
		for _, f := range fields {
			if !recetas.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recetas.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CantidadNecesaria(); ok {
		_spec.SetField(recetas.FieldCantidadNecesaria, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCantidadNecesaria(); ok {
		_spec.AddField(recetas.FieldCantidadNecesaria, field.TypeFloat64, value)
	}
	if _u.mutation.ProductoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.ProductoTable,
			Columns: []string{recetas.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.ProductoTable,
			Columns: []string{recetas.ProductoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productosmenu.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MateriaPrimaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.MateriaPrimaTable,
			Columns: []string{recetas.MateriaPrimaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MateriaPrimaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recetas.MateriaPrimaTable,
			Columns: []string{recetas.MateriaPrimaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(materiaprima.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Recetas{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recetas.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
