// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/recetas"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Recetas is the model entity for the Recetas schema.
type Recetas struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CantidadNecesaria holds the value of the "cantidad_necesaria" field.
	CantidadNecesaria float64 `json:"cantidad_necesaria,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecetasQuery when eager-loading is set.
	Edges                  RecetasEdges `json:"edges"`
	materia_prima_recetas  *int
	productos_menu_recetas *int
	selectValues           sql.SelectValues
}

// RecetasEdges holds the relations/edges for other nodes in the graph.
type RecetasEdges struct {
	// Producto holds the value of the producto edge.
	Producto *ProductosMenu `json:"producto,omitempty"`
	// MateriaPrima holds the value of the materia_prima edge.
	MateriaPrima *MateriaPrima `json:"materia_prima,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductoOrErr returns the Producto value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecetasEdges) ProductoOrErr() (*ProductosMenu, error) {
	if e.Producto != nil {
		return e.Producto, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: productosmenu.Label}
	}
	return nil, &NotLoadedError{edge: "producto"}
}

// MateriaPrimaOrErr returns the MateriaPrima value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecetasEdges) MateriaPrimaOrErr() (*MateriaPrima, error) {
	if e.MateriaPrima != nil {
		return e.MateriaPrima, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: materiaprima.Label}
	}
	return nil, &NotLoadedError{edge: "materia_prima"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Recetas) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recetas.FieldCantidadNecesaria:
			values[i] = new(sql.NullFloat64)
		case recetas.FieldID:
			values[i] = new(sql.NullInt64)
		case recetas.ForeignKeys[0]: // materia_prima_recetas
			values[i] = new(sql.NullInt64)
		case recetas.ForeignKeys[1]: // productos_menu_recetas
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Recetas fields.
func (_m *Recetas) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recetas.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case recetas.FieldCantidadNecesaria:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cantidad_necesaria", values[i])
			} else if value.Valid {
				_m.CantidadNecesaria = value.Float64
			}
		case recetas.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field materia_prima_recetas", value)
			} else if value.Valid {
				_m.materia_prima_recetas = new(int)
				*_m.materia_prima_recetas = int(value.Int64)
			}
		case recetas.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field productos_menu_recetas", value)
			} else if value.Valid {
				_m.productos_menu_recetas = new(int)
				*_m.productos_menu_recetas = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Recetas.
// This includes values selected through modifiers, order, etc.
func (_m *Recetas) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProducto queries the "producto" edge of the Recetas entity.
func (_m *Recetas) QueryProducto() *ProductosMenuQuery {
	return NewRecetasClient(_m.config).QueryProducto(_m)
}

// QueryMateriaPrima queries the "materia_prima" edge of the Recetas entity.
func (_m *Recetas) QueryMateriaPrima() *MateriaPrimaQuery {
	return NewRecetasClient(_m.config).QueryMateriaPrima(_m)
}

// Update returns a builder for updating this Recetas.
// Note that you need to call Recetas.Unwrap() before calling this method if this Recetas
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Recetas) Update() *RecetasUpdateOne {
	return NewRecetasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Recetas entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Recetas) Unwrap() *Recetas {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Recetas is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Recetas) String() string {
	var builder strings.Builder
	builder.WriteString("Recetas(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cantidad_necesaria=")
	builder.WriteString(fmt.Sprintf("%v", _m.CantidadNecesaria))
	builder.WriteByte(')')
	return builder.String()
}

// RecetasSlice is a parsable slice of Recetas.
type RecetasSlice []*Recetas
