// Code generated by ent, DO NOT EDIT.

package ent

import (
	"boloneria-app/ent/clientes"
	"boloneria-app/ent/materiaprima"
	"boloneria-app/ent/pedidos"
	"boloneria-app/ent/productosmenu"
	"boloneria-app/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clientesFields := schema.Clientes{}.Fields()
	_ = clientesFields
	// clientesDescNombreCompleto is the schema descriptor for nombre_completo field.
	clientesDescNombreCompleto := clientesFields[0].Descriptor()
	// clientes.NombreCompletoValidator is a validator for the "nombre_completo" field. It is called by the builders before save.
	clientes.NombreCompletoValidator = clientesDescNombreCompleto.Validators[0].(func(string) error)
	materiaprimaFields := schema.MateriaPrima{}.Fields()
	_ = materiaprimaFields
	// materiaprimaDescNombreInsumo is the schema descriptor for nombre_insumo field.
	materiaprimaDescNombreInsumo := materiaprimaFields[0].Descriptor()
	// materiaprima.NombreInsumoValidator is a validator for the "nombre_insumo" field. It is called by the builders before save.
	materiaprima.NombreInsumoValidator = materiaprimaDescNombreInsumo.Validators[0].(func(string) error)
	// materiaprimaDescCategoria is the schema descriptor for categoria field.
	materiaprimaDescCategoria := materiaprimaFields[1].Descriptor()
	// materiaprima.CategoriaValidator is a validator for the "categoria" field. It is called by the builders before save.
	materiaprima.CategoriaValidator = materiaprimaDescCategoria.Validators[0].(func(string) error)
	// materiaprimaDescProveedor is the schema descriptor for proveedor field.
	materiaprimaDescProveedor := materiaprimaFields[2].Descriptor()
	// materiaprima.ProveedorValidator is a validator for the "proveedor" field. It is called by the builders before save.
	materiaprima.ProveedorValidator = materiaprimaDescProveedor.Validators[0].(func(string) error)
	// materiaprimaDescUnidadMedida is the schema descriptor for unidad_medida field.
	materiaprimaDescUnidadMedida := materiaprimaFields[3].Descriptor()
	// materiaprima.UnidadMedidaValidator is a validator for the "unidad_medida" field. It is called by the builders before save.
	materiaprima.UnidadMedidaValidator = materiaprimaDescUnidadMedida.Validators[0].(func(string) error)
	pedidosFields := schema.Pedidos{}.Fields()
	_ = pedidosFields
	// pedidosDescFechaPedido is the schema descriptor for fecha_pedido field.
	pedidosDescFechaPedido := pedidosFields[0].Descriptor()
	// pedidos.DefaultFechaPedido holds the default value on creation for the fecha_pedido field.
	pedidos.DefaultFechaPedido = pedidosDescFechaPedido.Default.(func() time.Time)
	// pedidosDescEstado is the schema descriptor for estado field.
	pedidosDescEstado := pedidosFields[1].Descriptor()
	// pedidos.DefaultEstado holds the default value on creation for the estado field.
	pedidos.DefaultEstado = pedidosDescEstado.Default.(string)
	productosmenuFields := schema.ProductosMenu{}.Fields()
	_ = productosmenuFields
	// productosmenuDescNombreProducto is the schema descriptor for nombre_producto field.
	productosmenuDescNombreProducto := productosmenuFields[0].Descriptor()
	// productosmenu.NombreProductoValidator is a validator for the "nombre_producto" field. It is called by the builders before save.
	productosmenu.NombreProductoValidator = productosmenuDescNombreProducto.Validators[0].(func(string) error)
	// productosmenuDescCategoriaMenu is the schema descriptor for categoria_menu field.
	productosmenuDescCategoriaMenu := productosmenuFields[1].Descriptor()
	// productosmenu.CategoriaMenuValidator is a validator for the "categoria_menu" field. It is called by the builders before save.
	productosmenu.CategoriaMenuValidator = productosmenuDescCategoriaMenu.Validators[0].(func(string) error)
}
