// Code generated by ent, DO NOT EDIT.

package clientes

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the clientes type in the database.
	Label = "clientes"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNombreCompleto holds the string denoting the nombre_completo field in the database.
	FieldNombreCompleto = "nombre_completo"
	// FieldTelefono holds the string denoting the telefono field in the database.
	FieldTelefono = "telefono"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDireccion holds the string denoting the direccion field in the database.
	FieldDireccion = "direccion"
	// EdgePedidos holds the string denoting the pedidos edge name in mutations.
	EdgePedidos = "pedidos"
	// Table holds the table name of the clientes in the database.
	Table = "clientes"
	// PedidosTable is the table that holds the pedidos relation/edge.
	PedidosTable = "pedidos"
	// PedidosInverseTable is the table name for the Pedidos entity.
	// It exists in this package in order to avoid circular dependency with the "pedidos" package.
	PedidosInverseTable = "pedidos"
	// PedidosColumn is the table column denoting the pedidos relation/edge.
	PedidosColumn = "cliente_id"
)

// Columns holds all SQL columns for clientes fields.
var Columns = []string{
	FieldID,
	FieldNombreCompleto,
	FieldTelefono,
	FieldEmail,
	FieldDireccion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NombreCompletoValidator is a validator for the "nombre_completo" field. It is called by the builders before save.
	NombreCompletoValidator func(string) error
)

// OrderOption defines the ordering options for the Clientes queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNombreCompleto orders the results by the nombre_completo field.
func ByNombreCompleto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNombreCompleto, opts...).ToFunc()
}

// ByTelefono orders the results by the telefono field.
func ByTelefono(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelefono, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDireccion orders the results by the direccion field.
func ByDireccion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDireccion, opts...).ToFunc()
}

// ByPedidosCount orders the results by pedidos count.
func ByPedidosCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPedidosStep(), opts...)
	}
}

// ByPedidos orders the results by pedidos terms.
func ByPedidos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPedidosStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPedidosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PedidosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PedidosTable, PedidosColumn),
	)
}
