// Code generated by ent, DO NOT EDIT.

package clientes

import (
	"boloneria-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Clientes {
	return predicate.Clientes(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Clientes {
	return predicate.Clientes(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Clientes {
	return predicate.Clientes(sql.FieldLTE(FieldID, id))
}

// NombreCompleto applies equality check predicate on the "nombre_completo" field. It's identical to NombreCompletoEQ.
func NombreCompleto(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldNombreCompleto, v))
}

// Telefono applies equality check predicate on the "telefono" field. It's identical to TelefonoEQ.
func Telefono(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldTelefono, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldEmail, v))
}

// Direccion applies equality check predicate on the "direccion" field. It's identical to DireccionEQ.
func Direccion(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldDireccion, v))
}

// NombreCompletoEQ applies the EQ predicate on the "nombre_completo" field.
func NombreCompletoEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldNombreCompleto, v))
}

// NombreCompletoNEQ applies the NEQ predicate on the "nombre_completo" field.
func NombreCompletoNEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNEQ(FieldNombreCompleto, v))
}

// NombreCompletoIn applies the In predicate on the "nombre_completo" field.
func NombreCompletoIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldIn(FieldNombreCompleto, vs...))
}

// NombreCompletoNotIn applies the NotIn predicate on the "nombre_completo" field.
func NombreCompletoNotIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNotIn(FieldNombreCompleto, vs...))
}

// NombreCompletoGT applies the GT predicate on the "nombre_completo" field.
func NombreCompletoGT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGT(FieldNombreCompleto, v))
}

// NombreCompletoGTE applies the GTE predicate on the "nombre_completo" field.
func NombreCompletoGTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGTE(FieldNombreCompleto, v))
}

// NombreCompletoLT applies the LT predicate on the "nombre_completo" field.
func NombreCompletoLT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLT(FieldNombreCompleto, v))
}

// NombreCompletoLTE applies the LTE predicate on the "nombre_completo" field.
func NombreCompletoLTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLTE(FieldNombreCompleto, v))
}

// NombreCompletoContains applies the Contains predicate on the "nombre_completo" field.
func NombreCompletoContains(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContains(FieldNombreCompleto, v))
}

// NombreCompletoHasPrefix applies the HasPrefix predicate on the "nombre_completo" field.
func NombreCompletoHasPrefix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasPrefix(FieldNombreCompleto, v))
}

// NombreCompletoHasSuffix applies the HasSuffix predicate on the "nombre_completo" field.
func NombreCompletoHasSuffix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasSuffix(FieldNombreCompleto, v))
}

// NombreCompletoEqualFold applies the EqualFold predicate on the "nombre_completo" field.
func NombreCompletoEqualFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEqualFold(FieldNombreCompleto, v))
}

// NombreCompletoContainsFold applies the ContainsFold predicate on the "nombre_completo" field.
func NombreCompletoContainsFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContainsFold(FieldNombreCompleto, v))
}

// TelefonoEQ applies the EQ predicate on the "telefono" field.
func TelefonoEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldTelefono, v))
}

// TelefonoNEQ applies the NEQ predicate on the "telefono" field.
func TelefonoNEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNEQ(FieldTelefono, v))
}

// TelefonoIn applies the In predicate on the "telefono" field.
func TelefonoIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldIn(FieldTelefono, vs...))
}

// TelefonoNotIn applies the NotIn predicate on the "telefono" field.
func TelefonoNotIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNotIn(FieldTelefono, vs...))
}

// TelefonoGT applies the GT predicate on the "telefono" field.
func TelefonoGT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGT(FieldTelefono, v))
}

// TelefonoGTE applies the GTE predicate on the "telefono" field.
func TelefonoGTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGTE(FieldTelefono, v))
}

// TelefonoLT applies the LT predicate on the "telefono" field.
func TelefonoLT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLT(FieldTelefono, v))
}

// TelefonoLTE applies the LTE predicate on the "telefono" field.
func TelefonoLTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLTE(FieldTelefono, v))
}

// TelefonoContains applies the Contains predicate on the "telefono" field.
func TelefonoContains(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContains(FieldTelefono, v))
}

// TelefonoHasPrefix applies the HasPrefix predicate on the "telefono" field.
func TelefonoHasPrefix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasPrefix(FieldTelefono, v))
}

// TelefonoHasSuffix applies the HasSuffix predicate on the "telefono" field.
func TelefonoHasSuffix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasSuffix(FieldTelefono, v))
}

// TelefonoIsNil applies the IsNil predicate on the "telefono" field.
func TelefonoIsNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldIsNull(FieldTelefono))
}

// TelefonoNotNil applies the NotNil predicate on the "telefono" field.
func TelefonoNotNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldNotNull(FieldTelefono))
}

// TelefonoEqualFold applies the EqualFold predicate on the "telefono" field.
func TelefonoEqualFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEqualFold(FieldTelefono, v))
}

// TelefonoContainsFold applies the ContainsFold predicate on the "telefono" field.
func TelefonoContainsFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContainsFold(FieldTelefono, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContainsFold(FieldEmail, v))
}

// DireccionEQ applies the EQ predicate on the "direccion" field.
func DireccionEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEQ(FieldDireccion, v))
}

// DireccionNEQ applies the NEQ predicate on the "direccion" field.
func DireccionNEQ(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNEQ(FieldDireccion, v))
}

// DireccionIn applies the In predicate on the "direccion" field.
func DireccionIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldIn(FieldDireccion, vs...))
}

// DireccionNotIn applies the NotIn predicate on the "direccion" field.
func DireccionNotIn(vs ...string) predicate.Clientes {
	return predicate.Clientes(sql.FieldNotIn(FieldDireccion, vs...))
}

// DireccionGT applies the GT predicate on the "direccion" field.
func DireccionGT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGT(FieldDireccion, v))
}

// DireccionGTE applies the GTE predicate on the "direccion" field.
func DireccionGTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldGTE(FieldDireccion, v))
}

// DireccionLT applies the LT predicate on the "direccion" field.
func DireccionLT(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLT(FieldDireccion, v))
}

// DireccionLTE applies the LTE predicate on the "direccion" field.
func DireccionLTE(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldLTE(FieldDireccion, v))
}

// DireccionContains applies the Contains predicate on the "direccion" field.
func DireccionContains(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContains(FieldDireccion, v))
}

// DireccionHasPrefix applies the HasPrefix predicate on the "direccion" field.
func DireccionHasPrefix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasPrefix(FieldDireccion, v))
}

// DireccionHasSuffix applies the HasSuffix predicate on the "direccion" field.
func DireccionHasSuffix(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldHasSuffix(FieldDireccion, v))
}

// DireccionIsNil applies the IsNil predicate on the "direccion" field.
func DireccionIsNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldIsNull(FieldDireccion))
}

// DireccionNotNil applies the NotNil predicate on the "direccion" field.
func DireccionNotNil() predicate.Clientes {
	return predicate.Clientes(sql.FieldNotNull(FieldDireccion))
}

// DireccionEqualFold applies the EqualFold predicate on the "direccion" field.
func DireccionEqualFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldEqualFold(FieldDireccion, v))
}

// DireccionContainsFold applies the ContainsFold predicate on the "direccion" field.
func DireccionContainsFold(v string) predicate.Clientes {
	return predicate.Clientes(sql.FieldContainsFold(FieldDireccion, v))
}

// HasPedidos applies the HasEdge predicate on the "pedidos" edge.
func HasPedidos() predicate.Clientes {
	return predicate.Clientes(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PedidosTable, PedidosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPedidosWith applies the HasEdge predicate on the "pedidos" edge with a given conditions (other predicates).
func HasPedidosWith(preds ...predicate.Pedidos) predicate.Clientes {
	return predicate.Clientes(func(s *sql.Selector) {
		step := newPedidosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Clientes) predicate.Clientes {
	return predicate.Clientes(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Clientes) predicate.Clientes {
	return predicate.Clientes(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Clientes) predicate.Clientes {
	return predicate.Clientes(sql.NotPredicates(p))
}
