// Code generated by ent, DO NOT EDIT.

package pedidos

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pedidos type in the database.
	Label = "pedidos"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFechaPedido holds the string denoting the fecha_pedido field in the database.
	FieldFechaPedido = "fecha_pedido"
	// FieldEstado holds the string denoting the estado field in the database.
	FieldEstado = "estado"
	// FieldTotalPedido holds the string denoting the total_pedido field in the database.
	FieldTotalPedido = "total_pedido"
	// FieldClienteID holds the string denoting the cliente_id field in the database.
	FieldClienteID = "cliente_id"
	// EdgeCliente holds the string denoting the cliente edge name in mutations.
	EdgeCliente = "cliente"
	// EdgeDetalles holds the string denoting the detalles edge name in mutations.
	EdgeDetalles = "detalles"
	// Table holds the table name of the pedidos in the database.
	Table = "pedidos"
	// ClienteTable is the table that holds the cliente relation/edge.
	ClienteTable = "pedidos"
	// ClienteInverseTable is the table name for the Clientes entity.
	// It exists in this package in order to avoid circular dependency with the "clientes" package.
	ClienteInverseTable = "clientes"
	// ClienteColumn is the table column denoting the cliente relation/edge.
	ClienteColumn = "cliente_id"
	// DetallesTable is the table that holds the detalles relation/edge.
	DetallesTable = "detalles_pedido"
	// DetallesInverseTable is the table name for the DetallesPedido entity.
	// It exists in this package in order to avoid circular dependency with the "detallespedido" package.
	DetallesInverseTable = "detalles_pedido"
	// DetallesColumn is the table column denoting the detalles relation/edge.
	DetallesColumn = "pedido_id"
)

// Columns holds all SQL columns for pedidos fields.
var Columns = []string{
	FieldID,
	FieldFechaPedido,
	FieldEstado,
	FieldTotalPedido,
	FieldClienteID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFechaPedido holds the default value on creation for the "fecha_pedido" field.
	DefaultFechaPedido func() time.Time
	// DefaultEstado holds the default value on creation for the "estado" field.
	DefaultEstado string
)

// OrderOption defines the ordering options for the Pedidos queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFechaPedido orders the results by the fecha_pedido field.
func ByFechaPedido(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFechaPedido, opts...).ToFunc()
}

// ByEstado orders the results by the estado field.
func ByEstado(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstado, opts...).ToFunc()
}

// ByTotalPedido orders the results by the total_pedido field.
func ByTotalPedido(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPedido, opts...).ToFunc()
}

// ByClienteID orders the results by the cliente_id field.
func ByClienteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClienteID, opts...).ToFunc()
}

// ByClienteField orders the results by cliente field.
func ByClienteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClienteStep(), sql.OrderByField(field, opts...))
	}
}

// ByDetallesCount orders the results by detalles count.
func ByDetallesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDetallesStep(), opts...)
	}
}

// ByDetalles orders the results by detalles terms.
func ByDetalles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDetallesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClienteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClienteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClienteTable, ClienteColumn),
	)
}
func newDetallesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DetallesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DetallesTable, DetallesColumn),
	)
}
