// Code generated by ent, DO NOT EDIT.

package pedidos

import (
	"boloneria-app/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLTE(FieldID, id))
}

// FechaPedido applies equality check predicate on the "fecha_pedido" field. It's identical to FechaPedidoEQ.
func FechaPedido(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldFechaPedido, v))
}

// Estado applies equality check predicate on the "estado" field. It's identical to EstadoEQ.
func Estado(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldEstado, v))
}

// TotalPedido applies equality check predicate on the "total_pedido" field. It's identical to TotalPedidoEQ.
func TotalPedido(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldTotalPedido, v))
}

// ClienteID applies equality check predicate on the "cliente_id" field. It's identical to ClienteIDEQ.
func ClienteID(v int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldClienteID, v))
}

// FechaPedidoEQ applies the EQ predicate on the "fecha_pedido" field.
func FechaPedidoEQ(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldFechaPedido, v))
}

// FechaPedidoNEQ applies the NEQ predicate on the "fecha_pedido" field.
func FechaPedidoNEQ(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNEQ(FieldFechaPedido, v))
}

// FechaPedidoIn applies the In predicate on the "fecha_pedido" field.
func FechaPedidoIn(vs ...time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIn(FieldFechaPedido, vs...))
}

// FechaPedidoNotIn applies the NotIn predicate on the "fecha_pedido" field.
func FechaPedidoNotIn(vs ...time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotIn(FieldFechaPedido, vs...))
}

// FechaPedidoGT applies the GT predicate on the "fecha_pedido" field.
func FechaPedidoGT(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGT(FieldFechaPedido, v))
}

// FechaPedidoGTE applies the GTE predicate on the "fecha_pedido" field.
func FechaPedidoGTE(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGTE(FieldFechaPedido, v))
}

// FechaPedidoLT applies the LT predicate on the "fecha_pedido" field.
func FechaPedidoLT(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLT(FieldFechaPedido, v))
}

// FechaPedidoLTE applies the LTE predicate on the "fecha_pedido" field.
func FechaPedidoLTE(v time.Time) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLTE(FieldFechaPedido, v))
}

// EstadoEQ applies the EQ predicate on the "estado" field.
func EstadoEQ(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldEstado, v))
}

// EstadoNEQ applies the NEQ predicate on the "estado" field.
func EstadoNEQ(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNEQ(FieldEstado, v))
}

// EstadoIn applies the In predicate on the "estado" field.
func EstadoIn(vs ...string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIn(FieldEstado, vs...))
}

// EstadoNotIn applies the NotIn predicate on the "estado" field.
func EstadoNotIn(vs ...string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotIn(FieldEstado, vs...))
}

// EstadoGT applies the GT predicate on the "estado" field.
func EstadoGT(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGT(FieldEstado, v))
}

// EstadoGTE applies the GTE predicate on the "estado" field.
func EstadoGTE(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGTE(FieldEstado, v))
}

// EstadoLT applies the LT predicate on the "estado" field.
func EstadoLT(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLT(FieldEstado, v))
}

// EstadoLTE applies the LTE predicate on the "estado" field.
func EstadoLTE(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLTE(FieldEstado, v))
}

// EstadoContains applies the Contains predicate on the "estado" field.
func EstadoContains(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldContains(FieldEstado, v))
}

// EstadoHasPrefix applies the HasPrefix predicate on the "estado" field.
func EstadoHasPrefix(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldHasPrefix(FieldEstado, v))
}

// EstadoHasSuffix applies the HasSuffix predicate on the "estado" field.
func EstadoHasSuffix(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldHasSuffix(FieldEstado, v))
}

// EstadoEqualFold applies the EqualFold predicate on the "estado" field.
func EstadoEqualFold(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEqualFold(FieldEstado, v))
}

// EstadoContainsFold applies the ContainsFold predicate on the "estado" field.
func EstadoContainsFold(v string) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldContainsFold(FieldEstado, v))
}

// TotalPedidoEQ applies the EQ predicate on the "total_pedido" field.
func TotalPedidoEQ(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldTotalPedido, v))
}

// TotalPedidoNEQ applies the NEQ predicate on the "total_pedido" field.
func TotalPedidoNEQ(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNEQ(FieldTotalPedido, v))
}

// TotalPedidoIn applies the In predicate on the "total_pedido" field.
func TotalPedidoIn(vs ...float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIn(FieldTotalPedido, vs...))
}

// TotalPedidoNotIn applies the NotIn predicate on the "total_pedido" field.
func TotalPedidoNotIn(vs ...float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotIn(FieldTotalPedido, vs...))
}

// TotalPedidoGT applies the GT predicate on the "total_pedido" field.
func TotalPedidoGT(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGT(FieldTotalPedido, v))
}

// TotalPedidoGTE applies the GTE predicate on the "total_pedido" field.
func TotalPedidoGTE(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldGTE(FieldTotalPedido, v))
}

// TotalPedidoLT applies the LT predicate on the "total_pedido" field.
func TotalPedidoLT(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLT(FieldTotalPedido, v))
}

// TotalPedidoLTE applies the LTE predicate on the "total_pedido" field.
func TotalPedidoLTE(v float64) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldLTE(FieldTotalPedido, v))
}

// ClienteIDEQ applies the EQ predicate on the "cliente_id" field.
func ClienteIDEQ(v int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldEQ(FieldClienteID, v))
}

// ClienteIDNEQ applies the NEQ predicate on the "cliente_id" field.
func ClienteIDNEQ(v int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNEQ(FieldClienteID, v))
}

// ClienteIDIn applies the In predicate on the "cliente_id" field.
func ClienteIDIn(vs ...int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIn(FieldClienteID, vs...))
}

// ClienteIDNotIn applies the NotIn predicate on the "cliente_id" field.
func ClienteIDNotIn(vs ...int) predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotIn(FieldClienteID, vs...))
}

// ClienteIDIsNil applies the IsNil predicate on the "cliente_id" field.
func ClienteIDIsNil() predicate.Pedidos {
	return predicate.Pedidos(sql.FieldIsNull(FieldClienteID))
}

// ClienteIDNotNil applies the NotNil predicate on the "cliente_id" field.
func ClienteIDNotNil() predicate.Pedidos {
	return predicate.Pedidos(sql.FieldNotNull(FieldClienteID))
}

// HasCliente applies the HasEdge predicate on the "cliente" edge.
func HasCliente() predicate.Pedidos {
	return predicate.Pedidos(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClienteTable, ClienteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClienteWith applies the HasEdge predicate on the "cliente" edge with a given conditions (other predicates).
func HasClienteWith(preds ...predicate.Clientes) predicate.Pedidos {
	return predicate.Pedidos(func(s *sql.Selector) {
		step := newClienteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDetalles applies the HasEdge predicate on the "detalles" edge.
func HasDetalles() predicate.Pedidos {
	return predicate.Pedidos(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DetallesTable, DetallesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDetallesWith applies the HasEdge predicate on the "detalles" edge with a given conditions (other predicates).
func HasDetallesWith(preds ...predicate.DetallesPedido) predicate.Pedidos {
	return predicate.Pedidos(func(s *sql.Selector) {
		step := newDetallesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Pedidos) predicate.Pedidos {
	return predicate.Pedidos(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Pedidos) predicate.Pedidos {
	return predicate.Pedidos(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pedidos) predicate.Pedidos {
	return predicate.Pedidos(sql.NotPredicates(p))
}
