// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Clientes is the predicate function for clientes builders.
type Clientes func(*sql.Selector)

// DetallesPedido is the predicate function for detallespedido builders.
type DetallesPedido func(*sql.Selector)

// MateriaPrima is the predicate function for materiaprima builders.
type MateriaPrima func(*sql.Selector)

// Pedidos is the predicate function for pedidos builders.
type Pedidos func(*sql.Selector)

// ProductosMenu is the predicate function for productosmenu builders.
type ProductosMenu func(*sql.Selector)

// Recetas is the predicate function for recetas builders.
type Recetas func(*sql.Selector)
